-- =================================================================
-- My Diary V3 — CONSOLIDATED ORACLE PRODUCTION MIGRATION SCRIPT
-- Run as the target application schema owner on the production PDB.
-- NOTE: DDL below is qualified with "RP_OWNER".  If your production
--       schema differs, run a find/replace "RP_OWNER". -> ""  (empty)
--       and connect AS the target owner, OR keep RP_OWNER as the owner.
-- Order: (1) STRUCTURE  (2) REQUEST-PORTAL SEED  (3) SUPER ADMIN  (4) MY-DIARY SEED
-- =================================================================

-- ##################### 1. STRUCTURE (tables, sequences, indexes, FKs, views) #####################
-- ============ SEQUENCES ============

   CREATE SEQUENCE  "RP_OWNER"."MD_SEQ_GLOBAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1229 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "RP_OWNER"."RP_SEQ_GLOBAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1501 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "RP_OWNER"."RP_SEQ_REQUEST"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 50 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

-- ============ TABLES (PK/UK/CHECK inline; FKs added later) ============

  CREATE TABLE "RP_OWNER"."EASE_ATR"
   (	"ID" NUMBER NOT NULL ENABLE,
	"DIRECTION_ID" NUMBER NOT NULL ENABLE,
	"ATR_TEXT" CLOB NOT NULL ENABLE,
	"SUBMITTED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"SUBMITTED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"ACCEPTED_AT" TIMESTAMP (6),
	"ACCEPTED_BY_EMP" VARCHAR2(20),
	 CONSTRAINT "PK_EASE_ATR" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_ATTACHMENT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"REF_TYPE" VARCHAR2(15) NOT NULL ENABLE,
	"REF_ID" NUMBER NOT NULL ENABLE,
	"FILE_NAME" VARCHAR2(500) NOT NULL ENABLE,
	"MIME" VARCHAR2(100),
	"SIZE_BYTES" NUMBER,
	"STORAGE_KEY" VARCHAR2(1000) NOT NULL ENABLE,
	"UPLOADED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"UPLOADED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_EASE_ATT_TYP" CHECK (REF_TYPE IN ('RESPONSE','CLARIF','INITIATIVE')) ENABLE,
	 CONSTRAINT "PK_EASE_ATT" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_CAMPAIGN"
   (	"ID" NUMBER NOT NULL ENABLE,
	"PILLAR" VARCHAR2(2) NOT NULL ENABLE,
	"CAMPAIGN_TYPE" VARCHAR2(15) NOT NULL ENABLE,
	"TITLE" VARCHAR2(200) NOT NULL ENABLE,
	"PERIOD_MONTH" NUMBER(2,0),
	"PERIOD_YEAR" NUMBER(4,0) NOT NULL ENABLE,
	"PERIOD_QUARTER" NUMBER(1,0),
	"FREQ" VARCHAR2(1) NOT NULL ENABLE,
	"STATUS" VARCHAR2(10) DEFAULT 'DRAFT' NOT NULL ENABLE,
	"OPEN_DATE" DATE,
	"CLOSE_DATE" DATE,
	"CREATED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_EASE_CAMP_PIL" CHECK (PILLAR IN ('I','II')) ENABLE,
	 CONSTRAINT "CK_EASE_CAMP_TYP" CHECK (CAMPAIGN_TYPE IN ('KCI','KPI','INITIATIVE')) ENABLE,
	 CONSTRAINT "CK_EASE_CAMP_FRQ" CHECK (FREQ IN ('M','Q')) ENABLE,
	 CONSTRAINT "CK_EASE_CAMP_STS" CHECK (STATUS IN ('DRAFT','OPEN','CLOSED')) ENABLE,
	 CONSTRAINT "PK_EASE_CAMP" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_CLARIFICATION"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ASSIGNMENT_ID" NUMBER NOT NULL ENABLE,
	"RAISED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"RAISED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"QUESTION_TEXT" CLOB NOT NULL ENABLE,
	"ANSWERED_BY_EMP" VARCHAR2(20),
	"ANSWERED_AT" TIMESTAMP (6),
	"ANSWER_TEXT" CLOB,
	"STATUS" VARCHAR2(10) DEFAULT 'OPEN' NOT NULL ENABLE,
	 CONSTRAINT "CK_EASE_CLARIF_STS" CHECK (STATUS IN ('OPEN','ANSWERED','CLOSED')) ENABLE,
	 CONSTRAINT "PK_EASE_CLARIF" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_DIRECTION"
   (	"ID" NUMBER NOT NULL ENABLE,
	"REF_TYPE" VARCHAR2(15) NOT NULL ENABLE,
	"REF_ID" NUMBER NOT NULL ENABLE,
	"MEETING_DATE" DATE NOT NULL ENABLE,
	"DIRECTION_TEXT" CLOB NOT NULL ENABLE,
	"DIRECTED_TO_EMP" VARCHAR2(20),
	"STATUS" VARCHAR2(15) DEFAULT 'OPEN' NOT NULL ENABLE,
	"RECORDED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"RECORDED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_EASE_DIR_TYP" CHECK (REF_TYPE IN ('METRIC','INITIATIVE')) ENABLE,
	 CONSTRAINT "CK_EASE_DIR_STS" CHECK (STATUS IN ('OPEN','ATR_SUBMITTED','CLOSED')) ENABLE,
	 CONSTRAINT "PK_EASE_DIR" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_INITIATIVE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"CAMPAIGN_ID" NUMBER NOT NULL ENABLE,
	"INITIATIVE_NAME" VARCHAR2(500) NOT NULL ENABLE,
	"OBJECTIVE" CLOB,
	"RATIONALE" CLOB,
	"SOLUTION_DETAILS" CLOB,
	"BUSINESS_IMPACT" CLOB,
	"COST_INCURRED" VARCHAR2(3),
	"EXPECTED_COST" NUMBER(20,2),
	"VENDOR_REQUIRED" VARCHAR2(3),
	"VENDOR_NAME" VARCHAR2(300),
	"PO_ISSUED" VARCHAR2(3),
	"MGMT_APPROVED" VARCHAR2(3),
	"RBI_STRATEGY_LINKED" VARCHAR2(3),
	"PREV_STR_LINKED" VARCHAR2(3),
	"INIT_REVISION" NUMBER(1,0) DEFAULT 0,
	"OWNER_EMP_CODE" VARCHAR2(20),
	"OWNER_DEPT" VARCHAR2(200),
	"OWNER_CONTACT" VARCHAR2(20),
	"STATUS" VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL ENABLE,
	"CREATED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "PK_EASE_INIT" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_INITIATIVE_METRIC"
   (	"ID" NUMBER NOT NULL ENABLE,
	"INITIATIVE_ID" NUMBER NOT NULL ENABLE,
	"SEQ_NO" NUMBER NOT NULL ENABLE,
	"METRIC_DESC" VARCHAR2(500) NOT NULL ENABLE,
	"FY25_ACTUAL" NUMBER(20,2),
	 CONSTRAINT "PK_EASE_INIT_MET" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_INITIATIVE_PERF"
   (	"ID" NUMBER NOT NULL ENABLE,
	"INITIATIVE_METRIC_ID" NUMBER NOT NULL ENABLE,
	"FY" NUMBER(4,0) NOT NULL ENABLE,
	"QUARTER" VARCHAR2(10) NOT NULL ENABLE,
	"PERIOD_TYPE" VARCHAR2(10) NOT NULL ENABLE,
	"PERF_VALUE" NUMBER(20,2),
	"ENTERED_BY_EMP" VARCHAR2(20),
	"ENTERED_AT" TIMESTAMP (6),
	 CONSTRAINT "CK_EASE_PERF_QRT" CHECK (QUARTER IN ('Q1','Q2','Q3','Q4','ANNUAL')) ENABLE,
	 CONSTRAINT "CK_EASE_PERF_TYP" CHECK (PERIOD_TYPE IN ('ACTUAL','TARGET')) ENABLE,
	 CONSTRAINT "PK_EASE_PERF" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_METRIC_MASTER"
   (	"ID" NUMBER NOT NULL ENABLE,
	"CAMPAIGN_ID" NUMBER NOT NULL ENABLE,
	"ROW_ID" NUMBER NOT NULL ENABLE,
	"METRIC_TYPE" VARCHAR2(100),
	"METRIC_SORT" NUMBER,
	"METRIC_ID" VARCHAR2(50),
	"METRIC_DESC" VARCHAR2(2000),
	"EXPL_COMMENTS" CLOB,
	"RESP_TYPE_ACCOUNTS" NUMBER(1,0) DEFAULT 0,
	"RESP_TYPE_AMOUNT" NUMBER(1,0) DEFAULT 0,
	"RESP_TYPE_YESNO" NUMBER(1,0) DEFAULT 0,
	"HAS_SEGMENTS" NUMBER(1,0) DEFAULT 0,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1,
	 CONSTRAINT "PK_EASE_METRIC" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_METRIC_RESPONSE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ASSIGNMENT_ID" NUMBER NOT NULL ENABLE,
	"VERSION" NUMBER DEFAULT 1 NOT NULL ENABLE,
	"RESP_VALUE" VARCHAR2(4000),
	"RESP_ACCOUNTS" NUMBER,
	"RESP_AMOUNT" NUMBER(20,2),
	"RESP_YESNO" VARCHAR2(3),
	"DATA_SOURCE" VARCHAR2(500),
	"BANK_COMMENTS" CLOB,
	"BMO_EMP_CODE" VARCHAR2(20),
	"BMO_CONTACT" VARCHAR2(20),
	"IS_DRAFT" NUMBER(1,0) DEFAULT 1,
	"SUBMITTED_AT" TIMESTAMP (6),
	"SUBMITTED_BY_EMP" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "PK_EASE_RESP" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_METRIC_SEGMENT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"RESPONSE_ID" NUMBER NOT NULL ENABLE,
	"SEGMENT_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"SEGMENT_NAME" VARCHAR2(100),
	"VALUE_ACCOUNTS" NUMBER,
	"VALUE_AMOUNT" NUMBER(20,2),
	 CONSTRAINT "PK_EASE_SEG" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_ROLE_ASSIGNMENT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"ROLE_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"UNIT_ID" NUMBER,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"GRANTED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"GRANTED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"REVOKED_AT" TIMESTAMP (6),
	 CONSTRAINT "PK_EASE_ROLE" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"CAMPAIGN_ID" NUMBER NOT NULL ENABLE,
	"METRIC_ID" NUMBER NOT NULL ENABLE,
	"UNIT_ID" NUMBER NOT NULL ENABLE,
	"SPOC_EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"ORIGINAL_DUE_DATE" DATE NOT NULL ENABLE,
	"REVISED_DUE_DATE" DATE,
	"REVISION_REASON" VARCHAR2(500),
	"STATUS" VARCHAR2(20) DEFAULT 'PENDING' NOT NULL ENABLE,
	"ASSIGNED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"ASSIGNED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_EASE_VASN_STS" CHECK (STATUS IN ('PENDING','SUBMITTED','UNDER_REVIEW','CLARIFICATION','ACCEPTED','REJECTED')) ENABLE,
	 CONSTRAINT "PK_EASE_VASN" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_VERT_INITIATIVE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"INITIATIVE_ID" NUMBER NOT NULL ENABLE,
	"UNIT_ID" NUMBER NOT NULL ENABLE,
	"SPOC_EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"DUE_DATE" DATE,
	"STATUS" VARCHAR2(20) DEFAULT 'PENDING' NOT NULL ENABLE,
	 CONSTRAINT "CK_EASE_VI_STS" CHECK (STATUS IN ('PENDING','SUBMITTED','ACCEPTED','REJECTED')) ENABLE,
	 CONSTRAINT "PK_EASE_VI" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_DELEGATION"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"FROM_EMPL_ID" VARCHAR2(50) NOT NULL ENABLE,
	"TO_EMPL_ID" VARCHAR2(50) NOT NULL ENABLE,
	"ROLE_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"VERTICAL_CODE" VARCHAR2(50),
	"VALID_FROM" DATE NOT NULL ENABLE,
	"VALID_TO" DATE NOT NULL ENABLE,
	"REASON" VARCHAR2(500),
	"MODIFIED_BY_EMP" VARCHAR2(50),
	"MODIFIED_AT" TIMESTAMP (6),
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_INAPP_NOTIF"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"EMPL_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"TITLE" VARCHAR2(200) NOT NULL ENABLE,
	"BODY" VARCHAR2(2000),
	"HREF" VARCHAR2(500),
	"IS_READ" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_NOTIF_OUTBOX"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"EVENT_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"CHANNEL" NUMBER(2,0) NOT NULL ENABLE,
	"TO_ADDRESS" VARCHAR2(200) NOT NULL ENABLE,
	"TO_EMPL_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"PAYLOAD_JSON" CLOB,
	"STATUS" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"ATTEMPTS" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE,
	"LAST_ERROR" VARCHAR2(500),
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"SENT_AT" TIMESTAMP (6),
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_NOTIF_TEMPLATE"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"EVENT_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"CHANNEL" NUMBER(2,0) NOT NULL ENABLE,
	"SUBJECT" VARCHAR2(500),
	"BODY" CLOB NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_NOTIF_TEMPLATE" UNIQUE ("EVENT_CODE", "CHANNEL")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_RBAC_MENU"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"MODULE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"LABEL" VARCHAR2(200) NOT NULL ENABLE,
	"HREF" VARCHAR2(500),
	"ICON" VARCHAR2(100),
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_RBAC_MODULE"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"CODE" VARCHAR2(100) NOT NULL ENABLE,
	"DISPLAY_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"PARENT_ID" NUMBER(19,0),
	"KIND" NUMBER(2,0) NOT NULL ENABLE,
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_MD_RBAC_MODULE_CODE" UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_ROLE"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"CODE" NUMBER(5,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(100) NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_MD_ROLE_CODE" UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_ROLE_MODULE_PERM"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"ROLE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"MODULE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"CAN_VIEW" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_ADD" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_MODIFY" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_DELETE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_AUTHORIZE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_ROLE_MODULE" UNIQUE ("ROLE_ID", "MODULE_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_USER"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"EMPL_ID" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(200),
	"MOBILE" VARCHAR2(20),
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6),
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_MD_USER_EMPL_ID" UNIQUE ("EMPL_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_USER_MODULE_PERM"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"EMPL_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"MODULE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"CAN_VIEW" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_ADD" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_MODIFY" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_DELETE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_AUTHORIZE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"IS_DENY" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_USER_MODULE" UNIQUE ("EMPL_CODE", "MODULE_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_USER_ROLE"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"USER_ID" NUMBER(19,0) NOT NULL ENABLE,
	"ROLE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"VALID_FROM" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"VALID_TO" DATE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MYDIARY_LANDING_SITEMAP"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"URL" VARCHAR2(500) NOT NULL ENABLE,
	"CATEGORY" VARCHAR2(100),
	"SUB_CATEGORY" VARCHAR2(100),
	"DESCRIPTION" VARCHAR2(2000),
	"KEYWORDS" VARCHAR2(2000),
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_AUDIT_LOG"
   (	"ID" NUMBER(19,0),
	"ENTITY" VARCHAR2(60) NOT NULL ENABLE,
	"ENTITY_ID" NUMBER(19,0) NOT NULL ENABLE,
	"ACTION" VARCHAR2(40) NOT NULL ENABLE,
	"ACTOR_EMP_CODE" VARCHAR2(20),
	"ACTED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"OLD_JSON" CLOB,
	"NEW_JSON" CLOB,
	"IP" VARCHAR2(64),
	"USER_AGENT" VARCHAR2(500),
	"HASH_PREV" VARCHAR2(64),
	"HASH_CURR" VARCHAR2(64) NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_DELEGATION"
   (	"ID" NUMBER(19,0),
	"FROM_EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"TO_EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"ROLE_CODE" VARCHAR2(30) NOT NULL ENABLE,
	"VERTICAL_CODE" VARCHAR2(50),
	"VALID_FROM" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE,
	"VALID_TO" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE,
	"REASON" VARCHAR2(500),
	"MODIFIED_BY_EMP" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 CONSTRAINT "CK_DELEG_DIFF" CHECK (FROM_EMP_CODE <> TO_EMP_CODE) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_ACTIVITY"
   (	"ID" NUMBER(19,0),
	"DEPARTMENT_ID" NUMBER(19,0) NOT NULL ENABLE,
	"CODE" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_DEPARTMENT"
   (	"ID" NUMBER(19,0),
	"VERTICAL_ID" NUMBER(19,0) NOT NULL ENABLE,
	"CODE" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_HOLIDAY"
   (	"ID" NUMBER(19,0),
	"CAL_ID" NUMBER(19,0) NOT NULL ENABLE,
	"HOLIDAY_DATE" DATE NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(200),
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UK_HOLIDAY" UNIQUE ("CAL_ID", "HOLIDAY_DATE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_HOLIDAY_CAL"
   (	"ID" NUMBER(19,0),
	"CODE" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_NOTIF_TEMPLATE"
   (	"ID" NUMBER(19,0),
	"EVENT_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"CHANNEL" NUMBER(1,0) NOT NULL ENABLE,
	"SUBJECT" VARCHAR2(500),
	"BODY" CLOB NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 CONSTRAINT "CK_NOTIF_CHN" CHECK (CHANNEL IN (1, 2)) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UK_NOTIF_TPL" UNIQUE ("EVENT_CODE", "CHANNEL")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_REQUEST_TYPE"
   (	"ID" NUMBER(19,0),
	"CODE" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_ROUTING_ASSIGNEE"
   (	"ID" NUMBER(19,0),
	"RULE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"IS_PRIMARY" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_ROUTING_RULE"
   (	"ID" NUMBER(19,0),
	"REQUEST_TYPE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"UNIT_TYPE_ID" NUMBER(19,0),
	"VERTICAL_ID" NUMBER(19,0),
	"DEPARTMENT_ID" NUMBER(19,0),
	"ACTIVITY_ID" NUMBER(19,0),
	"PRIORITY" NUMBER(5,0) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_SLA_CONFIG"
   (	"ID" NUMBER(19,0),
	"REQUEST_TYPE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"LEVEL_NO" NUMBER(2,0) NOT NULL ENABLE,
	"WORKING_DAYS" NUMBER(3,0) NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 CONSTRAINT "CK_SLA_LEVEL" CHECK (LEVEL_NO BETWEEN 1 AND 5) ENABLE,
	 CONSTRAINT "CK_SLA_DAYS" CHECK (WORKING_DAYS > 0) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UK_SLA" UNIQUE ("REQUEST_TYPE_ID", "LEVEL_NO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_UNIT"
   (	"ID" NUMBER(19,0),
	"UNIT_TYPE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"PARENT_UNIT_ID" NUMBER(19,0),
	"CODE" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"HOLIDAY_CAL_ID" NUMBER(19,0),
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_UNIT_TYPE"
   (	"ID" NUMBER(19,0),
	"CODE" VARCHAR2(20) NOT NULL ENABLE,
	"NAME" VARCHAR2(100) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_VERTICAL"
   (	"ID" NUMBER(19,0),
	"CODE" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_NOTIFICATION"
   (	"ID" NUMBER(19,0),
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"TITLE" VARCHAR2(200) NOT NULL ENABLE,
	"MESSAGE" VARCHAR2(2000),
	"CATEGORY" VARCHAR2(50),
	"REDIRECT_URL" VARCHAR2(500),
	"SOURCE" VARCHAR2(20) NOT NULL ENABLE,
	"EVENT_CODE" VARCHAR2(50),
	"REQUEST_ID" NUMBER(19,0),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"READ_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_NOTIF_OUTBOX"
   (	"ID" NUMBER(19,0),
	"EVENT_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"CHANNEL" NUMBER(1,0) NOT NULL ENABLE,
	"TO_ADDR" VARCHAR2(300) NOT NULL ENABLE,
	"PAYLOAD_JSON" CLOB NOT NULL ENABLE,
	"STATUS" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"ATTEMPTS" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE,
	"LAST_ERROR" VARCHAR2(2000),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"SENT_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_PAGE_INFO"
   (	"PAGE_KEY" VARCHAR2(100) NOT NULL ENABLE,
	"PAGE_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"PAGE_TYPE" VARCHAR2(50) DEFAULT 'Dashboard' NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(1000),
	"OWNER_VERTICAL" VARCHAR2(200),
	"MODULE_OWNER" VARCHAR2(200),
	"IP_NUMBER" VARCHAR2(100),
	"MAIL_ID" VARCHAR2(200),
	"VERSION" VARCHAR2(20) DEFAULT 'v1.0',
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE',
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"UPDATED_DATE" DATE,
	 CONSTRAINT "CHK_PI_STATUS" CHECK (STATUS   IN ('ACTIVE','INACTIVE','DEPRECATED')) ENABLE,
	 CONSTRAINT "CHK_PI_TYPE" CHECK (PAGE_TYPE IN ('Dashboard','Report','Upload','Approve','Enquiry','Maintenance','Other')) ENABLE,
	 CONSTRAINT "PK_RP_PAGE_INFO" PRIMARY KEY ("PAGE_KEY")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_APP_ADMIN"
   (	"ID" NUMBER(19,0),
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"ASSIGNED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"ASSIGNED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"NOTE" VARCHAR2(1000),
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("EMP_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_AUDIT"
   (	"ID" NUMBER(19,0),
	"AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"ACTOR_EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"ACTION" VARCHAR2(40) NOT NULL ENABLE,
	"TARGET" VARCHAR2(300) NOT NULL ENABLE,
	"DETAILS" VARCHAR2(2000),
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_MENU"
   (	"ID" NUMBER(19,0),
	"MODULE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"CODE" VARCHAR2(80) NOT NULL ENABLE,
	"LABEL" VARCHAR2(200) NOT NULL ENABLE,
	"ICON" VARCHAR2(60),
	"ROUTE" VARCHAR2(300) NOT NULL ENABLE,
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE,
	"IS_ENABLED" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_MODULE"
   (	"ID" NUMBER(19,0),
	"CODE" VARCHAR2(60) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"KIND" NUMBER(2,0) DEFAULT 1 NOT NULL ENABLE,
	"PARENT_ID" NUMBER(19,0),
	"ICON" VARCHAR2(60),
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_RBAC_MOD_KIND" CHECK (KIND BETWEEN 1 AND 5) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_ROLE_PERM"
   (	"ID" NUMBER(19,0),
	"ROLE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"MODULE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"CAN_VIEW" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_ADD" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_MODIFY" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_DELETE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_AUTHORIZE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"UPDATED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UK_RBAC_ROLE_MOD" UNIQUE ("ROLE_ID", "MODULE_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_SUPER_ADMIN"
   (	"ID" NUMBER(19,0),
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"ASSIGNED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"ASSIGNED_BY" VARCHAR2(60) DEFAULT 'BOOT' NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("EMP_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_USER_PERM"
   (	"ID" NUMBER(19,0),
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"MODULE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"IS_DENY" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_VIEW" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_ADD" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_MODIFY" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_DELETE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_AUTHORIZE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"UPDATED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UK_RBAC_USER_MOD" UNIQUE ("EMP_CODE", "MODULE_ID", "IS_DENY")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_VERTICAL_ADMIN"
   (	"ID" NUMBER(19,0),
	"VERTICAL_ID" NUMBER(19,0) NOT NULL ENABLE,
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"ASSIGNED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"ASSIGNED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"REVOKED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UK_VERT_ADMIN" UNIQUE ("VERTICAL_ID", "EMP_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_VERTICAL_LEVEL"
   (	"ID" NUMBER(19,0),
	"VERTICAL_ID" NUMBER(19,0) NOT NULL ENABLE,
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"LEVEL_CODE" VARCHAR2(10) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"ASSIGNED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"ASSIGNED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"REVOKED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE,
	 CONSTRAINT "CK_LEVEL_CODE" CHECK (LEVEL_CODE IN ('VERT_L1','VERT_L2','VERT_L3','VERT_L4','VERT_L5')) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UK_VERT_LEVEL" UNIQUE ("VERTICAL_ID", "EMP_CODE", "LEVEL_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_REQUEST"
   (	"ID" NUMBER(19,0),
	"REQ_NO" VARCHAR2(20) NOT NULL ENABLE,
	"REQUEST_TYPE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"UNIT_ID" NUMBER(19,0) NOT NULL ENABLE,
	"VERTICAL_ID" NUMBER(19,0) NOT NULL ENABLE,
	"DEPARTMENT_ID" NUMBER(19,0) NOT NULL ENABLE,
	"ACTIVITY_ID" NUMBER(19,0) NOT NULL ENABLE,
	"RAISED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"SUBJECT" VARCHAR2(500) NOT NULL ENABLE,
	"DESCRIPTION" CLOB NOT NULL ENABLE,
	"CURRENT_LEVEL" NUMBER(2,0) DEFAULT 1 NOT NULL ENABLE,
	"STATUS" NUMBER(2,0) DEFAULT 1 NOT NULL ENABLE,
	"SLA_DUE_UTC" TIMESTAMP (6) WITH TIME ZONE,
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"CLOSED_AT" TIMESTAMP (6) WITH TIME ZONE,
	"ROW_VERSION" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
	"RAISED_BY" NUMBER,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("REQ_NO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_REQUEST_ACTION"
   (	"ID" NUMBER(19,0),
	"REQUEST_ID" NUMBER(19,0) NOT NULL ENABLE,
	"LEVEL_NO" NUMBER(2,0) NOT NULL ENABLE,
	"ACTOR_EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"ACTION" VARCHAR2(50) NOT NULL ENABLE,
	"REMARKS" VARCHAR2(2000),
	"ACTED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_REQUEST_ASSIGNEE"
   (	"ID" NUMBER(19,0),
	"REQUEST_ID" NUMBER(19,0) NOT NULL ENABLE,
	"LEVEL_NO" NUMBER(2,0) NOT NULL ENABLE,
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"ASSIGNED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"ASSIGNED_BY_EMP" VARCHAR2(20),
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_REQUEST_ATTACHMENT"
   (	"ID" NUMBER(19,0),
	"REQUEST_ID" NUMBER(19,0) NOT NULL ENABLE,
	"ACTION_ID" NUMBER(19,0),
	"FILE_NAME" VARCHAR2(300) NOT NULL ENABLE,
	"MIME" VARCHAR2(100) NOT NULL ENABLE,
	"SIZE_BYTES" NUMBER(19,0) NOT NULL ENABLE,
	"STORAGE_KEY" VARCHAR2(500) NOT NULL ENABLE,
	"UPLOADED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"UPLOADED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"SHA256" VARCHAR2(64) NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_REQUEST_CLARIFICATION"
   (	"ID" NUMBER(19,0),
	"REQUEST_ID" NUMBER(19,0) NOT NULL ENABLE,
	"ASKED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"ASKED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"REPLIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	"QUESTION" VARCHAR2(2000) NOT NULL ENABLE,
	"ANSWER" VARCHAR2(2000),
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_REQUEST_FEEDBACK"
   (	"ID" NUMBER(19,0),
	"REQUEST_ID" NUMBER(19,0) NOT NULL ENABLE,
	"RATING" NUMBER(1,0) NOT NULL ENABLE,
	"COMMENTS" VARCHAR2(2000),
	"GIVEN_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_FEEDBACK_RATING" CHECK (RATING BETWEEN 1 AND 5) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("REQUEST_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_ROLE"
   (	"ID" NUMBER(19,0),
	"CODE" VARCHAR2(30) NOT NULL ENABLE,
	"NAME" VARCHAR2(100) NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_SLA_PAUSE_LOG"
   (	"ID" NUMBER(19,0),
	"REQUEST_ID" NUMBER(19,0) NOT NULL ENABLE,
	"PAUSED_AT" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE,
	"RESUMED_AT" TIMESTAMP (6) WITH TIME ZONE,
	"REASON" VARCHAR2(500),
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_UAT_AUTH"
   (	"EMPLOYEE_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"PWD_HASH" VARCHAR2(200) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	 CONSTRAINT "PK_UAT_AUTH" PRIMARY KEY ("EMPLOYEE_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_UAT_STAFF"
   (	"EMPLOYEE_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"EMPLOYEE_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"UNIT_TYPE" VARCHAR2(10) NOT NULL ENABLE,
	"USER_LEVEL" VARCHAR2(10) NOT NULL ENABLE,
	"UNIT_CODE" VARCHAR2(20),
	"UNIT_NAME" VARCHAR2(100),
	"VERTICAL_CODE" VARCHAR2(20),
	"VERTICAL_NAME" VARCHAR2(100),
	"IS_HEAD" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"DESIGNATION" VARCHAR2(100),
	"EMAIL" VARCHAR2(100),
	"MOBILE" VARCHAR2(15),
	 CONSTRAINT "CK_UAT_UNIT_TYPE" CHECK (UNIT_TYPE  IN ('RO','ZO','CO','ADMIN')) ENABLE,
	 CONSTRAINT "CK_UAT_USER_LEVEL" CHECK (USER_LEVEL IN ('BRANCH','RO','ZO','CO','ADMIN')) ENABLE,
	 CONSTRAINT "CK_UAT_IS_HEAD" CHECK (IS_HEAD    IN (0,1)) ENABLE,
	 CONSTRAINT "PK_UAT_STAFF" PRIMARY KEY ("EMPLOYEE_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_USER"
   (	"ID" NUMBER NOT NULL ENABLE,
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"AD_SAM" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(200),
	"MOBILE" VARCHAR2(20),
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6),
	 CONSTRAINT "PK_RP_USER" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_RP_USER_EMP" UNIQUE ("EMP_CODE")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_RP_USER_SAM" UNIQUE ("AD_SAM")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_USER_ROLE"
   (	"ID" NUMBER(19,0),
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"ROLE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"UNIT_CODE" VARCHAR2(50),
	"VERTICAL_CODE" VARCHAR2(50),
	"VALID_FROM" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"VALID_TO" TIMESTAMP (6) WITH TIME ZONE,
	"GRANTED_BY" VARCHAR2(20) NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UK_USER_ROLE" UNIQUE ("EMP_CODE", "ROLE_ID")
  USING INDEX  ENABLE
   ) ;

-- ============ NON-CONSTRAINT INDEXES ============

  CREATE INDEX "RP_OWNER"."IDX_EASE_ATR_DIR" ON "RP_OWNER"."EASE_ATR" ("DIRECTION_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_ATT_REF" ON "RP_OWNER"."EASE_ATTACHMENT" ("REF_TYPE", "REF_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_CLARIF_SPOC" ON "RP_OWNER"."EASE_CLARIFICATION" ("RAISED_BY_EMP", "STATUS")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_CLARIF_VASN" ON "RP_OWNER"."EASE_CLARIFICATION" ("ASSIGNMENT_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_DIR_REF" ON "RP_OWNER"."EASE_DIRECTION" ("REF_TYPE", "REF_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_INIT_CAMP" ON "RP_OWNER"."EASE_INITIATIVE" ("CAMPAIGN_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_METRIC_CAMP" ON "RP_OWNER"."EASE_METRIC_MASTER" ("CAMPAIGN_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_RESP_VASN" ON "RP_OWNER"."EASE_METRIC_RESPONSE" ("ASSIGNMENT_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_ROLE_EMP" ON "RP_OWNER"."EASE_ROLE_ASSIGNMENT" ("EMP_CODE", "IS_ACTIVE")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_SEG_RESP" ON "RP_OWNER"."EASE_METRIC_SEGMENT" ("RESPONSE_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_VASN_CAMP" ON "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ("CAMPAIGN_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_VASN_SPOC" ON "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ("SPOC_EMP_CODE", "STATUS")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_VASN_UNIT" ON "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ("UNIT_ID")
  ;


  CREATE INDEX "RP_OWNER"."IX_MD_INAPP_NOTIF_EMP" ON "RP_OWNER"."MD_INAPP_NOTIF" ("EMPL_CODE", "IS_READ", "CREATED_AT")
  ;


  CREATE INDEX "RP_OWNER"."IX_MD_NOTIF_OUTBOX_STATUS" ON "RP_OWNER"."MD_NOTIF_OUTBOX" ("STATUS", "ATTEMPTS")
  ;


  CREATE UNIQUE INDEX "RP_OWNER"."UQ_EASE_PERF" ON "RP_OWNER"."EASE_INITIATIVE_PERF" ("INITIATIVE_METRIC_ID", "FY", "QUARTER", "PERIOD_TYPE")
  ;


  CREATE UNIQUE INDEX "RP_OWNER"."UQ_EASE_VASN" ON "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ("METRIC_ID", "UNIT_ID")
  ;


  CREATE UNIQUE INDEX "RP_OWNER"."UQ_EASE_VI" ON "RP_OWNER"."EASE_VERT_INITIATIVE" ("INITIATIVE_ID", "UNIT_ID")
  ;

-- ============ FOREIGN KEYS ============

  ALTER TABLE "RP_OWNER"."EASE_ATR" ADD CONSTRAINT "FK_EASE_ATR_DIR" FOREIGN KEY ("DIRECTION_ID")
	  REFERENCES "RP_OWNER"."EASE_DIRECTION" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_CLARIFICATION" ADD CONSTRAINT "FK_EASE_CLARIF_VASN" FOREIGN KEY ("ASSIGNMENT_ID")
	  REFERENCES "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_INITIATIVE" ADD CONSTRAINT "FK_EASE_INIT_CAMP" FOREIGN KEY ("CAMPAIGN_ID")
	  REFERENCES "RP_OWNER"."EASE_CAMPAIGN" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_INITIATIVE_METRIC" ADD CONSTRAINT "FK_EASE_INIT_MET_INIT" FOREIGN KEY ("INITIATIVE_ID")
	  REFERENCES "RP_OWNER"."EASE_INITIATIVE" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_INITIATIVE_PERF" ADD CONSTRAINT "FK_EASE_PERF_MET" FOREIGN KEY ("INITIATIVE_METRIC_ID")
	  REFERENCES "RP_OWNER"."EASE_INITIATIVE_METRIC" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_METRIC_MASTER" ADD CONSTRAINT "FK_EASE_METRIC_CAMP" FOREIGN KEY ("CAMPAIGN_ID")
	  REFERENCES "RP_OWNER"."EASE_CAMPAIGN" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_METRIC_RESPONSE" ADD CONSTRAINT "FK_EASE_RESP_VASN" FOREIGN KEY ("ASSIGNMENT_ID")
	  REFERENCES "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_METRIC_SEGMENT" ADD CONSTRAINT "FK_EASE_SEG_RESP" FOREIGN KEY ("RESPONSE_ID")
	  REFERENCES "RP_OWNER"."EASE_METRIC_RESPONSE" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_ROLE_ASSIGNMENT" ADD CONSTRAINT "FK_EASE_ROLE_UNIT" FOREIGN KEY ("UNIT_ID")
	  REFERENCES "RP_OWNER"."RP_M_UNIT" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ADD CONSTRAINT "FK_EASE_VASN_CAMP" FOREIGN KEY ("CAMPAIGN_ID")
	  REFERENCES "RP_OWNER"."EASE_CAMPAIGN" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ADD CONSTRAINT "FK_EASE_VASN_METRIC" FOREIGN KEY ("METRIC_ID")
	  REFERENCES "RP_OWNER"."EASE_METRIC_MASTER" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ADD CONSTRAINT "FK_EASE_VASN_UNIT" FOREIGN KEY ("UNIT_ID")
	  REFERENCES "RP_OWNER"."RP_M_UNIT" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_VERT_INITIATIVE" ADD CONSTRAINT "FK_EASE_VI_INIT" FOREIGN KEY ("INITIATIVE_ID")
	  REFERENCES "RP_OWNER"."EASE_INITIATIVE" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."EASE_VERT_INITIATIVE" ADD CONSTRAINT "FK_EASE_VI_UNIT" FOREIGN KEY ("UNIT_ID")
	  REFERENCES "RP_OWNER"."RP_M_UNIT" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."MD_RBAC_MENU" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "RP_OWNER"."MD_RBAC_MODULE" ("ID") ON DELETE CASCADE ENABLE;


  ALTER TABLE "RP_OWNER"."MD_RBAC_MODULE" ADD FOREIGN KEY ("PARENT_ID")
	  REFERENCES "RP_OWNER"."MD_RBAC_MODULE" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."MD_ROLE_MODULE_PERM" ADD FOREIGN KEY ("ROLE_ID")
	  REFERENCES "RP_OWNER"."MD_ROLE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "RP_OWNER"."MD_ROLE_MODULE_PERM" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "RP_OWNER"."MD_RBAC_MODULE" ("ID") ON DELETE CASCADE ENABLE;


  ALTER TABLE "RP_OWNER"."MD_USER_MODULE_PERM" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "RP_OWNER"."MD_RBAC_MODULE" ("ID") ON DELETE CASCADE ENABLE;


  ALTER TABLE "RP_OWNER"."MD_USER_ROLE" ADD FOREIGN KEY ("ROLE_ID")
	  REFERENCES "RP_OWNER"."MD_ROLE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "RP_OWNER"."MD_USER_ROLE" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "RP_OWNER"."MD_USER" ("ID") ON DELETE CASCADE ENABLE;


  ALTER TABLE "RP_OWNER"."RP_M_ACTIVITY" ADD FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "RP_OWNER"."RP_M_DEPARTMENT" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_M_DEPARTMENT" ADD FOREIGN KEY ("VERTICAL_ID")
	  REFERENCES "RP_OWNER"."RP_M_VERTICAL" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_M_HOLIDAY" ADD FOREIGN KEY ("CAL_ID")
	  REFERENCES "RP_OWNER"."RP_M_HOLIDAY_CAL" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_M_ROUTING_ASSIGNEE" ADD FOREIGN KEY ("RULE_ID")
	  REFERENCES "RP_OWNER"."RP_M_ROUTING_RULE" ("ID") ON DELETE CASCADE ENABLE;


  ALTER TABLE "RP_OWNER"."RP_M_ROUTING_RULE" ADD FOREIGN KEY ("REQUEST_TYPE_ID")
	  REFERENCES "RP_OWNER"."RP_M_REQUEST_TYPE" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_M_ROUTING_RULE" ADD FOREIGN KEY ("UNIT_TYPE_ID")
	  REFERENCES "RP_OWNER"."RP_M_UNIT_TYPE" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_M_ROUTING_RULE" ADD FOREIGN KEY ("VERTICAL_ID")
	  REFERENCES "RP_OWNER"."RP_M_VERTICAL" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_M_ROUTING_RULE" ADD FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "RP_OWNER"."RP_M_DEPARTMENT" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_M_ROUTING_RULE" ADD FOREIGN KEY ("ACTIVITY_ID")
	  REFERENCES "RP_OWNER"."RP_M_ACTIVITY" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_M_SLA_CONFIG" ADD FOREIGN KEY ("REQUEST_TYPE_ID")
	  REFERENCES "RP_OWNER"."RP_M_REQUEST_TYPE" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_M_UNIT" ADD FOREIGN KEY ("UNIT_TYPE_ID")
	  REFERENCES "RP_OWNER"."RP_M_UNIT_TYPE" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_M_UNIT" ADD FOREIGN KEY ("PARENT_UNIT_ID")
	  REFERENCES "RP_OWNER"."RP_M_UNIT" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_M_UNIT" ADD FOREIGN KEY ("HOLIDAY_CAL_ID")
	  REFERENCES "RP_OWNER"."RP_M_HOLIDAY_CAL" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_RBAC_MENU" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "RP_OWNER"."RP_RBAC_MODULE" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_RBAC_MODULE" ADD FOREIGN KEY ("PARENT_ID")
	  REFERENCES "RP_OWNER"."RP_RBAC_MODULE" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_RBAC_ROLE_PERM" ADD FOREIGN KEY ("ROLE_ID")
	  REFERENCES "RP_OWNER"."RP_ROLE" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_RBAC_ROLE_PERM" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "RP_OWNER"."RP_RBAC_MODULE" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_RBAC_USER_PERM" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "RP_OWNER"."RP_RBAC_MODULE" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_RBAC_VERTICAL_ADMIN" ADD FOREIGN KEY ("VERTICAL_ID")
	  REFERENCES "RP_OWNER"."RP_M_VERTICAL" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_RBAC_VERTICAL_LEVEL" ADD FOREIGN KEY ("VERTICAL_ID")
	  REFERENCES "RP_OWNER"."RP_M_VERTICAL" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_REQUEST" ADD FOREIGN KEY ("REQUEST_TYPE_ID")
	  REFERENCES "RP_OWNER"."RP_M_REQUEST_TYPE" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_REQUEST" ADD FOREIGN KEY ("UNIT_ID")
	  REFERENCES "RP_OWNER"."RP_M_UNIT" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_REQUEST" ADD FOREIGN KEY ("VERTICAL_ID")
	  REFERENCES "RP_OWNER"."RP_M_VERTICAL" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_REQUEST" ADD FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "RP_OWNER"."RP_M_DEPARTMENT" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_REQUEST" ADD FOREIGN KEY ("ACTIVITY_ID")
	  REFERENCES "RP_OWNER"."RP_M_ACTIVITY" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_REQUEST_ACTION" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_OWNER"."RP_REQUEST" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_REQUEST_ASSIGNEE" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_OWNER"."RP_REQUEST" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_REQUEST_ATTACHMENT" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_OWNER"."RP_REQUEST" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_REQUEST_ATTACHMENT" ADD FOREIGN KEY ("ACTION_ID")
	  REFERENCES "RP_OWNER"."RP_REQUEST_ACTION" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_REQUEST_CLARIFICATION" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_OWNER"."RP_REQUEST" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_REQUEST_FEEDBACK" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_OWNER"."RP_REQUEST" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_SLA_PAUSE_LOG" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_OWNER"."RP_REQUEST" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_UAT_AUTH" ADD CONSTRAINT "FK_UAT_AUTH_STAFF" FOREIGN KEY ("EMPLOYEE_CODE")
	  REFERENCES "RP_OWNER"."RP_UAT_STAFF" ("EMPLOYEE_CODE") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_USER_ROLE" ADD FOREIGN KEY ("ROLE_ID")
	  REFERENCES "RP_OWNER"."RP_ROLE" ("ID") ENABLE;

-- ============ VIEWS ============

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "RP_OWNER"."VW_STAFF_USER_SUMMARY" ("EMPLOYEE_CODE", "EMPLOYEE_NAME", "UNIT_TYPE", "USER_LEVEL", "UNIT_CODE", "UNIT_NAME", "VERTICAL_CODE", "VERTICAL_NAME", "IS_HEAD", "DESIGNATION", "EMAIL", "MOBILE") AS
  SELECT
  EMPLOYEE_CODE,
  EMPLOYEE_NAME,
  UNIT_TYPE,
  USER_LEVEL,
  UNIT_CODE,
  UNIT_NAME,
  VERTICAL_CODE,
  VERTICAL_NAME,
  IS_HEAD,
  DESIGNATION,
  EMAIL,
  MOBILE
FROM RP_UAT_STAFF;


-- ##################### 2. REQUEST PORTAL SEED (roles, RBAC, masters, SLA, routing, templates) #####################
-- ============================================================================
-- Request Portal — Complete Seed Data v3.0
-- Schema   : RP_OWNER
-- Run after: 01_schema.sql
-- Run order: 01_schema.sql → 02_seed.sql → 04_superadmin.sql → 05_uat_data.sql
--
-- ROLE ARCHITECTURE (3 tiers):
--   Tier 1 — Organisational role (DERIVED at login from VW_STAFF_USER_SUMMARY):
--     BRANCH_USER  BRANCH_HEAD  RO_USER  RO_HEAD  ZO_USER  ZO_HEAD
--     CO_USER  CO_HEAD  CO_VERT_ADMIN  APP_ADMIN
--   Tier 2 — Super Admin (from RP_RBAC_SUPER_ADMIN, max 2):
--     SUPER_ADMIN
--   Tier 3 — Vertical process levels (ASSIGNED by CO_VERT_ADMIN, stored in
--             RP_RBAC_VERTICAL_LEVEL, additive to org role):
--     VERT_L1  VERT_L2  VERT_L3  VERT_L4  VERT_L5
-- ============================================================================

SET SERVEROUTPUT ON;

-- ---------------------------------------------------------------------------
-- 1. ROLES  (16 total)
-- ---------------------------------------------------------------------------
MERGE INTO RP_ROLE t USING (
  -- Tier 1 — Organisational (derived from view)
  SELECT 'BRANCH_USER'    AS CODE, 'Branch User'                    AS NAME FROM DUAL UNION ALL
  SELECT 'BRANCH_HEAD',            'Branch Head'                            FROM DUAL UNION ALL
  SELECT 'RO_USER',                'Regional Office User'                   FROM DUAL UNION ALL
  SELECT 'RO_HEAD',                'Regional Office Head'                   FROM DUAL UNION ALL
  SELECT 'ZO_USER',                'Zonal Office User'                      FROM DUAL UNION ALL
  SELECT 'ZO_HEAD',                'Zonal Office Head'                      FROM DUAL UNION ALL
  SELECT 'CO_USER',                'Corporate Office User'                  FROM DUAL UNION ALL
  SELECT 'CO_HEAD',                'Corporate Office Head'                  FROM DUAL UNION ALL
  SELECT 'CO_VERT_ADMIN',          'CO Vertical Admin'                      FROM DUAL UNION ALL
  SELECT 'APP_ADMIN',              'Application Admin'                      FROM DUAL UNION ALL
  -- Tier 2 — Super Admin
  SELECT 'SUPER_ADMIN',            'Super Admin'                            FROM DUAL UNION ALL
  -- Tier 3 — Vertical process levels (assigned by CO_VERT_ADMIN)
  SELECT 'VERT_L1',                'Vertical Level 1'                       FROM DUAL UNION ALL
  SELECT 'VERT_L2',                'Vertical Level 2'                       FROM DUAL UNION ALL
  SELECT 'VERT_L3',                'Vertical Level 3'                       FROM DUAL UNION ALL
  SELECT 'VERT_L4',                'Vertical Level 4'                       FROM DUAL UNION ALL
  SELECT 'VERT_L5',                'Vertical Level 5 (Oversight)'           FROM DUAL
) s ON (t.CODE = s.CODE)
WHEN NOT MATCHED THEN INSERT (ID, CODE, NAME)
  VALUES (RP_SEQ_GLOBAL.NEXTVAL, s.CODE, s.NAME)
WHEN MATCHED THEN UPDATE SET NAME = s.NAME;

-- ---------------------------------------------------------------------------
-- 2. REQUEST TYPES
-- ---------------------------------------------------------------------------
MERGE INTO RP_M_REQUEST_TYPE t USING (
  SELECT 'GRIEVANCE' AS CODE, 'Grievance' AS NAME FROM DUAL UNION ALL
  SELECT 'REQUEST',           'Request'           FROM DUAL UNION ALL
  SELECT 'INQUIRY',           'Inquiry'           FROM DUAL
) s ON (t.CODE = s.CODE)
WHEN NOT MATCHED THEN INSERT (ID, CODE, NAME)
  VALUES (RP_SEQ_GLOBAL.NEXTVAL, s.CODE, s.NAME);

-- ---------------------------------------------------------------------------
-- 3. UNIT TYPES  (5: BRANCH + the 4 as per VW_STAFF_USER_SUMMARY UNIT_TYPE)
-- ---------------------------------------------------------------------------
MERGE INTO RP_M_UNIT_TYPE t USING (
  SELECT 'BRANCH' AS CODE, 'Branch'           AS NAME FROM DUAL UNION ALL
  SELECT 'RO',             'Regional Office'          FROM DUAL UNION ALL
  SELECT 'ZO',             'Zonal Office'             FROM DUAL UNION ALL
  SELECT 'CO',             'Corporate Office'         FROM DUAL UNION ALL
  SELECT 'ADMIN',          'Administration'           FROM DUAL
) s ON (t.CODE = s.CODE)
WHEN NOT MATCHED THEN INSERT (ID, CODE, NAME)
  VALUES (RP_SEQ_GLOBAL.NEXTVAL, s.CODE, s.NAME);

-- ---------------------------------------------------------------------------
-- 4. DEFAULT HOLIDAY CALENDAR
-- ---------------------------------------------------------------------------
MERGE INTO RP_M_HOLIDAY_CAL t USING (
  SELECT 'NATIONAL' AS CODE, 'National Holiday Calendar' AS NAME FROM DUAL
) s ON (t.CODE = s.CODE)
WHEN NOT MATCHED THEN INSERT (ID, CODE, NAME)
  VALUES (RP_SEQ_GLOBAL.NEXTVAL, s.CODE, s.NAME);

-- ---------------------------------------------------------------------------
-- 5. DEFAULT SLA — 2 working days per level (L1–L5) for every request type
-- ---------------------------------------------------------------------------
DECLARE
  CURSOR c IS SELECT ID FROM RP_M_REQUEST_TYPE;
  v_exists NUMBER;
BEGIN
  FOR r IN c LOOP
    FOR lvl IN 1..5 LOOP
      SELECT COUNT(*) INTO v_exists
        FROM RP_M_SLA_CONFIG
       WHERE REQUEST_TYPE_ID = r.ID AND LEVEL_NO = lvl;
      IF v_exists = 0 THEN
        INSERT INTO RP_M_SLA_CONFIG (ID, REQUEST_TYPE_ID, LEVEL_NO, WORKING_DAYS)
        VALUES (RP_SEQ_GLOBAL.NEXTVAL, r.ID, lvl, 2);
      END IF;
    END LOOP;
  END LOOP;
END;
/

-- ---------------------------------------------------------------------------
-- 6. NOTIFICATION TEMPLATES
-- ---------------------------------------------------------------------------
MERGE INTO RP_M_NOTIF_TEMPLATE t USING (
  SELECT 'Created'            AS EC, 1 AS CH FROM DUAL UNION ALL
  SELECT 'Escalated',                1        FROM DUAL UNION ALL
  SELECT 'Resolved',                 1        FROM DUAL UNION ALL
  SELECT 'Closed',                   1        FROM DUAL UNION ALL
  SELECT 'ClarificationSought',      1        FROM DUAL UNION ALL
  SELECT 'Reopened',                 1        FROM DUAL UNION ALL
  SELECT 'Broadcast',                1        FROM DUAL
) s ON (t.EVENT_CODE = s.EC AND t.CHANNEL = s.CH)
WHEN NOT MATCHED THEN INSERT (ID, EVENT_CODE, CHANNEL, SUBJECT, BODY)
  VALUES (
    RP_SEQ_GLOBAL.NEXTVAL, s.EC, s.CH,
    CASE s.EC
      WHEN 'Created'             THEN '[#{{ReqNo}}] {{Subject}} — created'
      WHEN 'Escalated'           THEN '[#{{ReqNo}}] Escalated to Level {{CurrentLevel}}'
      WHEN 'Resolved'            THEN '[#{{ReqNo}}] Resolved'
      WHEN 'Closed'              THEN '[#{{ReqNo}}] Closed'
      WHEN 'ClarificationSought' THEN '[#{{ReqNo}}] Clarification needed'
      WHEN 'Reopened'            THEN '[#{{ReqNo}}] Reopened'
      WHEN 'Broadcast'           THEN '{{Subject}}'
    END,
    CASE s.EC
      WHEN 'Created'             THEN 'Hello {{RecipientName}},' || CHR(10) || CHR(10) || 'Request #{{ReqNo}} has been created by {{RaisedByName}}.' || CHR(10) || 'Type: {{RequestTypeName}}' || CHR(10) || 'Subject: {{Subject}}' || CHR(10) || CHR(10) || 'Please log in to the Request Portal to act.'
      WHEN 'Escalated'           THEN 'Hello {{RecipientName}},' || CHR(10) || CHR(10) || 'Request #{{ReqNo}} has been escalated to Level {{CurrentLevel}} due to SLA breach.' || CHR(10) || 'Please take action.'
      WHEN 'Resolved'            THEN 'Hello {{RecipientName}},' || CHR(10) || CHR(10) || 'Request #{{ReqNo}} has been resolved. Please review and provide feedback.'
      WHEN 'Closed'              THEN 'Hello {{RecipientName}},' || CHR(10) || CHR(10) || 'Request #{{ReqNo}} is now closed.'
      WHEN 'ClarificationSought' THEN 'Hello {{RecipientName}},' || CHR(10) || CHR(10) || 'Clarification has been requested on request #{{ReqNo}}.'
      WHEN 'Reopened'            THEN 'Hello {{RecipientName}},' || CHR(10) || CHR(10) || 'Request #{{ReqNo}} has been reopened.'
      WHEN 'Broadcast'           THEN '{{Message}}'
    END
  );

-- ---------------------------------------------------------------------------
-- 7. RBAC MODULE TREE
-- ---------------------------------------------------------------------------

-- Root modules
MERGE INTO RP_RBAC_MODULE t USING (
  SELECT 'MASTERS' AS CODE,'Masters'       AS NAME,1 AS KIND,'Settings'           AS ICON,10  AS SORT_ORDER FROM DUAL UNION ALL
  SELECT 'OPS',            'Operations',           1,         'Assignment',                 20              FROM DUAL UNION ALL
  SELECT 'INQ',            'Inquiry',              2,         'ManageSearch',               30              FROM DUAL UNION ALL
  SELECT 'REPORTS',        'Reports',              3,         'Description',                40              FROM DUAL UNION ALL
  SELECT 'MIS',            'MIS',                  4,         'QueryStats',                 50              FROM DUAL UNION ALL
  SELECT 'DASH',           'Dashboards',           5,         'Dashboard',                  60              FROM DUAL UNION ALL
  SELECT 'ADMIN',          'Administration',       1,         'AdminPanelSettings',         90              FROM DUAL
) s ON (t.CODE = s.CODE)
WHEN NOT MATCHED THEN INSERT (ID, CODE, NAME, KIND, PARENT_ID, ICON, SORT_ORDER, IS_ACTIVE)
  VALUES (RP_SEQ_GLOBAL.NEXTVAL, s.CODE, s.NAME, s.KIND, NULL, s.ICON, s.SORT_ORDER, 1);

-- Child modules
MERGE INTO RP_RBAC_MODULE t USING (
  SELECT CODE, NAME, KIND, PARENT_CODE, ICON, SORT_ORDER FROM (
    -- Masters
    SELECT 'MASTERS.USERS'       AS CODE,'Users'                  AS NAME,1 AS KIND,'MASTERS' AS PARENT_CODE,'PersonOutline'       AS ICON,10  AS SORT_ORDER FROM DUAL UNION ALL
    SELECT 'MASTERS.ROLES',             'Roles',                        1,           'MASTERS',               'BadgeOutlined',           20             FROM DUAL UNION ALL
    SELECT 'MASTERS.UNITS',             'Units',                        1,           'MASTERS',               'AccountTree',             30             FROM DUAL UNION ALL
    SELECT 'MASTERS.VERTICALS',         'Verticals',                    1,           'MASTERS',               'Hub',                     40             FROM DUAL UNION ALL
    SELECT 'MASTERS.DEPARTMENTS',       'Departments',                  1,           'MASTERS',               'GroupWork',               50             FROM DUAL UNION ALL
    SELECT 'MASTERS.ACTIVITIES',        'Activities',                   1,           'MASTERS',               'LocalActivity',           60             FROM DUAL UNION ALL
    SELECT 'MASTERS.REQTYPES',          'Request Types',                1,           'MASTERS',               'Category',                70             FROM DUAL UNION ALL
    SELECT 'MASTERS.HOLIDAYS',          'Holiday Calendar',             1,           'MASTERS',               'Event',                   80             FROM DUAL UNION ALL
    SELECT 'MASTERS.SLA',               'SLA Configuration',            1,           'MASTERS',               'Schedule',                90             FROM DUAL UNION ALL
    SELECT 'MASTERS.NOTIFTPL',          'Notification Templates',       1,           'MASTERS',               'Mail',                    100            FROM DUAL UNION ALL
    SELECT 'MASTERS.ROUTING',           'Routing Rules',                1,           'MASTERS',               'AltRoute',                110            FROM DUAL UNION ALL
    -- Operations
    SELECT 'OPS.NEW',                   'New Request',                  1,           'OPS',                   'Add',                     10             FROM DUAL UNION ALL
    SELECT 'OPS.MINE',                  'My Requests',                  1,           'OPS',                   'InboxOutlined',           20             FROM DUAL UNION ALL
    SELECT 'OPS.ASSIGNED',              'Assigned to Me',               1,           'OPS',                   'AssignmentInd',           30             FROM DUAL UNION ALL
    SELECT 'OPS.TEAM',                  'Team Queue',                   1,           'OPS',                   'Groups',                  40             FROM DUAL UNION ALL
    SELECT 'OPS.DELEGATE',              'Delegations',                  1,           'OPS',                   'SwapHoriz',               50             FROM DUAL UNION ALL
    SELECT 'OPS.BROADCAST',             'Broadcast',                    1,           'OPS',                   'Campaign',                60             FROM DUAL UNION ALL
    -- Inquiry
    SELECT 'INQ.REQ',                   'Request Inquiry',              2,           'INQ',                   'Search',                  10             FROM DUAL UNION ALL
    SELECT 'INQ.USER',                  'User Inquiry',                 2,           'INQ',                   'PersonSearch',            20             FROM DUAL UNION ALL
    SELECT 'INQ.AUDIT',                 'Audit Inquiry',                2,           'INQ',                   'HistoryToggleOff',        30             FROM DUAL UNION ALL
    -- Reports
    SELECT 'REPORTS.DAILY',             'Daily Operations',             3,           'REPORTS',               'Today',                   10             FROM DUAL UNION ALL
    SELECT 'REPORTS.SLA',               'SLA Breach Report',            3,           'REPORTS',               'Timer',                   20             FROM DUAL UNION ALL
    SELECT 'REPORTS.AGING',             'Aging Report',                 3,           'REPORTS',               'HourglassEmpty',          30             FROM DUAL UNION ALL
    -- MIS
    SELECT 'MIS.VOL',                   'Volume MIS',                   4,           'MIS',                   'BarChart',                10             FROM DUAL UNION ALL
    SELECT 'MIS.PROD',                  'Productivity MIS',             4,           'MIS',                   'TrendingUp',              20             FROM DUAL UNION ALL
    -- Dashboards
    SELECT 'DASH.OPS',                  'Operations Dashboard',         5,           'DASH',                  'Speed',                   10             FROM DUAL UNION ALL
    SELECT 'DASH.EXEC',                 'Executive Dashboard',          5,           'DASH',                  'Insights',                20             FROM DUAL UNION ALL
    -- Administration
    SELECT 'ADMIN.RIGHTS',              'Admin Rights',                 1,           'ADMIN',                 'AdminPanelSettings',      10             FROM DUAL UNION ALL
    SELECT 'ADMIN.MODULES',             'Modules & Sub-modules',        1,           'ADMIN',                 'AccountTree',             20             FROM DUAL UNION ALL
    SELECT 'ADMIN.MENUS',               'Menus',                        1,           'ADMIN',                 'Menu',                    30             FROM DUAL UNION ALL
    SELECT 'ADMIN.ROLEPERMS',           'Role Permissions',             1,           'ADMIN',                 'VerifiedUser',            40             FROM DUAL UNION ALL
    SELECT 'ADMIN.USEROVER',            'User Overrides',               1,           'ADMIN',                 'ManageAccounts',          50             FROM DUAL UNION ALL
    SELECT 'ADMIN.VERT_ASSIGN',         'Vertical Level Assignment',    1,           'ADMIN',                 'SupervisedUserCircle',    55             FROM DUAL UNION ALL
    SELECT 'ADMIN.AUDIT',               'RBAC Audit Log',               2,           'ADMIN',                 'HistoryEdu',              60             FROM DUAL
  )
) s ON (t.CODE = s.CODE)
WHEN NOT MATCHED THEN INSERT (ID, CODE, NAME, KIND, PARENT_ID, ICON, SORT_ORDER, IS_ACTIVE)
  VALUES (
    RP_SEQ_GLOBAL.NEXTVAL, s.CODE, s.NAME, s.KIND,
    (SELECT ID FROM RP_RBAC_MODULE WHERE CODE = s.PARENT_CODE),
    s.ICON, s.SORT_ORDER, 1
  );

-- ---------------------------------------------------------------------------
-- 8. RBAC MENUS
-- ---------------------------------------------------------------------------
MERGE INTO RP_RBAC_MENU t USING (
  SELECT CODE, LABEL, MOD_CODE, ROUTE, ICON, SORT_ORDER FROM (
    SELECT 'MENU.NEWREQ'       AS CODE,'New Request'              AS LABEL,'OPS.NEW'              AS MOD_CODE,'/requests/new'                     AS ROUTE,'Add'                    AS ICON,10  AS SORT_ORDER FROM DUAL UNION ALL
    SELECT 'MENU.MINE',               'My Requests',                       'OPS.MINE',                        '/requests/mine',                           'InboxOutlined',              20             FROM DUAL UNION ALL
    SELECT 'MENU.ASSIGNED',           'Assigned to Me',                    'OPS.ASSIGNED',                    '/requests/assigned',                       'AssignmentInd',              30             FROM DUAL UNION ALL
    SELECT 'MENU.TEAM',               'Team Queue',                        'OPS.TEAM',                        '/requests/team',                           'Groups',                     40             FROM DUAL UNION ALL
    SELECT 'MENU.DELEGATE',           'Delegations',                       'OPS.DELEGATE',                    '/requests/delegations',                    'SwapHoriz',                  50             FROM DUAL UNION ALL
    SELECT 'MENU.BROADCAST',          'Broadcast',                         'OPS.BROADCAST',                   '/admin/broadcast',                         'Campaign',                   60             FROM DUAL UNION ALL
    SELECT 'MENU.INQ.REQ',            'Request Inquiry',                   'INQ.REQ',                         '/inquiry/requests',                        'Search',                     10             FROM DUAL UNION ALL
    SELECT 'MENU.INQ.USER',           'User Inquiry',                      'INQ.USER',                        '/inquiry/users',                           'PersonSearch',               20             FROM DUAL UNION ALL
    SELECT 'MENU.REP.SLA',            'SLA Report',                        'REPORTS.SLA',                     '/reports/sla',                             'Timer',                      20             FROM DUAL UNION ALL
    SELECT 'MENU.DASH.OPS',           'Operations Dashboard',              'DASH.OPS',                        '/dashboards/ops',                          'Speed',                      10             FROM DUAL UNION ALL
    SELECT 'MENU.DASH.EXEC',          'Executive Dashboard',               'DASH.EXEC',                       '/dashboards/exec',                         'Insights',                   20             FROM DUAL UNION ALL
    SELECT 'MENU.MAS.USERS',          'Users',                             'MASTERS.USERS',                   '/masters/users',                           'PersonOutline',              10             FROM DUAL UNION ALL
    SELECT 'MENU.MAS.ROLES',          'Roles',                             'MASTERS.ROLES',                   '/masters/roles',                           'BadgeOutlined',              20             FROM DUAL UNION ALL
    SELECT 'MENU.MAS.UNITS',          'Units',                             'MASTERS.UNITS',                   '/masters/units',                           'AccountTree',                30             FROM DUAL UNION ALL
    SELECT 'MENU.MAS.HOL',            'Holiday Calendar',                  'MASTERS.HOLIDAYS',                '/masters/holidays',                        'Event',                      80             FROM DUAL UNION ALL
    SELECT 'MENU.MAS.SLA',            'SLA Configuration',                 'MASTERS.SLA',                     '/masters/sla',                             'Schedule',                   90             FROM DUAL UNION ALL
    SELECT 'MENU.MAS.NOTIF',          'Notification Templates',            'MASTERS.NOTIFTPL',                '/masters/notif-templates',                 'Mail',                       100            FROM DUAL UNION ALL
    SELECT 'MENU.MAS.ROUTING',        'Routing Rules',                     'MASTERS.ROUTING',                 '/masters/routing',                         'AltRoute',                   110            FROM DUAL UNION ALL
    SELECT 'MENU.ADM.RIGHTS',         'Admin Rights',                      'ADMIN.RIGHTS',                    '/admin/rbac/admin-rights',                 'AdminPanelSettings',         10             FROM DUAL UNION ALL
    SELECT 'MENU.ADM.MODULES',        'Modules & Sub-modules',             'ADMIN.MODULES',                   '/admin/rbac/modules',                      'AccountTree',                20             FROM DUAL UNION ALL
    SELECT 'MENU.ADM.MENUS',          'Menus',                             'ADMIN.MENUS',                     '/admin/rbac/menus',                        'Menu',                       30             FROM DUAL UNION ALL
    SELECT 'MENU.ADM.PERMS',          'Role Permissions',                  'ADMIN.ROLEPERMS',                 '/admin/rbac/role-permissions',             'VerifiedUser',               40             FROM DUAL UNION ALL
    SELECT 'MENU.ADM.VERT_ASSIGN',    'Vertical Level Assignment',         'ADMIN.VERT_ASSIGN',               '/admin/rbac/vertical-assignment',          'SupervisedUserCircle',       55             FROM DUAL UNION ALL
    SELECT 'MENU.ADM.AUDIT',          'RBAC Audit Log',                    'ADMIN.AUDIT',                     '/admin/rbac/audit',                        'HistoryEdu',                 60             FROM DUAL
  )
) s ON (t.CODE = s.CODE)
WHEN NOT MATCHED THEN INSERT (ID, MODULE_ID, CODE, LABEL, ICON, ROUTE, SORT_ORDER, IS_ENABLED, IS_ACTIVE)
  VALUES (
    RP_SEQ_GLOBAL.NEXTVAL,
    (SELECT ID FROM RP_RBAC_MODULE WHERE CODE = s.MOD_CODE),
    s.CODE, s.LABEL, s.ICON, s.ROUTE, s.SORT_ORDER, 1, 1
  );

-- ---------------------------------------------------------------------------
-- 9. BASELINE ROLE × MODULE PERMISSION GRID
--
-- Permission logic:
--   Org roles (BRANCH_USER..CO_HEAD): access proportional to hierarchy level.
--   CO_VERT_ADMIN: full operational control + vertical assignment in ADMIN.
--   VERT_L1..L5: additive to org role; enables ticket-processing capabilities.
--   APP_ADMIN / SUPER_ADMIN: full access to everything.
-- ---------------------------------------------------------------------------
DECLARE
  -- Grant or update a role→module permission row
  PROCEDURE grant_perm(
    p_role_code   IN VARCHAR2,
    p_module_code IN VARCHAR2,
    p_view        IN NUMBER DEFAULT 0,
    p_add         IN NUMBER DEFAULT 0,
    p_mod         IN NUMBER DEFAULT 0,
    p_del         IN NUMBER DEFAULT 0,
    p_auth        IN NUMBER DEFAULT 0
  ) IS
    v_role_id   NUMBER(19);
    v_module_id NUMBER(19);
  BEGIN
    BEGIN
      SELECT ID INTO v_role_id   FROM RP_ROLE        WHERE CODE = p_role_code;
      SELECT ID INTO v_module_id FROM RP_RBAC_MODULE WHERE CODE = p_module_code;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      DBMS_OUTPUT.PUT_LINE('WARN: skip grant ' || p_role_code || '->' || p_module_code);
      RETURN;
    END;
    MERGE INTO RP_RBAC_ROLE_PERM t
    USING (SELECT v_role_id AS RID, v_module_id AS MID FROM DUAL) s
    ON (t.ROLE_ID = s.RID AND t.MODULE_ID = s.MID)
    WHEN MATCHED THEN UPDATE SET
      CAN_VIEW=p_view, CAN_ADD=p_add, CAN_MODIFY=p_mod,
      CAN_DELETE=p_del, CAN_AUTHORIZE=p_auth,
      UPDATED_AT_UTC=SYSTIMESTAMP, UPDATED_BY_EMP='SEED'
    WHEN NOT MATCHED THEN INSERT
      (ID,ROLE_ID,MODULE_ID,CAN_VIEW,CAN_ADD,CAN_MODIFY,CAN_DELETE,CAN_AUTHORIZE,UPDATED_AT_UTC,UPDATED_BY_EMP)
      VALUES (RP_SEQ_GLOBAL.NEXTVAL,s.RID,s.MID,p_view,p_add,p_mod,p_del,p_auth,SYSTIMESTAMP,'SEED');
  END;

  PROCEDURE view_only(p_role IN VARCHAR2, p_mod IN VARCHAR2) IS
  BEGIN grant_perm(p_role, p_mod, 1,0,0,0,0); END;

  PROCEDURE full_access(p_role IN VARCHAR2, p_mod IN VARCHAR2) IS
  BEGIN grant_perm(p_role, p_mod, 1,1,1,1,1); END;

  -- Grant full access for APP_ADMIN and SUPER_ADMIN to all modules
  PROCEDURE admin_full IS
    CURSOR c IS SELECT CODE FROM RP_RBAC_MODULE;
  BEGIN
    FOR m IN c LOOP
      full_access('APP_ADMIN',   m.CODE);
      full_access('SUPER_ADMIN', m.CODE);
    END LOOP;
  END;

BEGIN
  -- ── BRANCH_USER: raise requests + view own + basic dashboard ─────────────
  grant_perm('BRANCH_USER','OPS',     1,1,0,0,0);
  grant_perm('BRANCH_USER','OPS.NEW', 1,1,0,0,0);
  grant_perm('BRANCH_USER','OPS.MINE',1,0,0,0,0);
  view_only('BRANCH_USER','INQ');      view_only('BRANCH_USER','INQ.REQ');
  view_only('BRANCH_USER','DASH');     view_only('BRANCH_USER','DASH.OPS');

  -- ── BRANCH_HEAD: + can see team queue + act on assigned tickets ──────────
  grant_perm('BRANCH_HEAD','OPS',         1,1,0,0,0);
  grant_perm('BRANCH_HEAD','OPS.NEW',     1,1,0,0,0);
  grant_perm('BRANCH_HEAD','OPS.MINE',    1,0,0,0,0);
  grant_perm('BRANCH_HEAD','OPS.ASSIGNED',1,0,1,0,0);
  grant_perm('BRANCH_HEAD','OPS.TEAM',    1,0,0,0,0);
  view_only('BRANCH_HEAD','INQ');         view_only('BRANCH_HEAD','INQ.REQ');
  view_only('BRANCH_HEAD','DASH');        view_only('BRANCH_HEAD','DASH.OPS');

  -- ── RO_USER: branch-head level ops ───────────────────────────────────────
  grant_perm('RO_USER','OPS',         1,1,0,0,0);
  grant_perm('RO_USER','OPS.NEW',     1,1,0,0,0);
  grant_perm('RO_USER','OPS.MINE',    1,0,0,0,0);
  grant_perm('RO_USER','OPS.ASSIGNED',1,0,1,0,0);
  grant_perm('RO_USER','OPS.TEAM',    1,0,0,0,0);
  view_only('RO_USER','INQ');         view_only('RO_USER','INQ.REQ');
  view_only('RO_USER','DASH');        view_only('RO_USER','DASH.OPS');
  view_only('RO_USER','REPORTS');     view_only('RO_USER','REPORTS.SLA');

  -- ── RO_HEAD: + delegation + user inquiry + reports ───────────────────────
  grant_perm('RO_HEAD','OPS',           1,1,0,0,0);
  grant_perm('RO_HEAD','OPS.NEW',       1,1,0,0,0);
  grant_perm('RO_HEAD','OPS.MINE',      1,0,0,0,0);
  grant_perm('RO_HEAD','OPS.ASSIGNED',  1,0,1,0,0);
  grant_perm('RO_HEAD','OPS.TEAM',      1,0,1,0,0);
  grant_perm('RO_HEAD','OPS.DELEGATE',  1,1,1,0,0);
  view_only('RO_HEAD','INQ');           view_only('RO_HEAD','INQ.REQ');
  view_only('RO_HEAD','INQ.USER');
  view_only('RO_HEAD','DASH');          view_only('RO_HEAD','DASH.OPS');
  view_only('RO_HEAD','REPORTS');       view_only('RO_HEAD','REPORTS.SLA');
  view_only('RO_HEAD','REPORTS.AGING');

  -- ── ZO_USER: RO_HEAD level + MIS ─────────────────────────────────────────
  grant_perm('ZO_USER','OPS',           1,1,0,0,0);
  grant_perm('ZO_USER','OPS.NEW',       1,1,0,0,0);
  grant_perm('ZO_USER','OPS.MINE',      1,0,0,0,0);
  grant_perm('ZO_USER','OPS.ASSIGNED',  1,0,1,0,0);
  grant_perm('ZO_USER','OPS.TEAM',      1,0,0,0,0);
  grant_perm('ZO_USER','OPS.DELEGATE',  1,1,1,0,0);
  view_only('ZO_USER','INQ');           view_only('ZO_USER','INQ.REQ');
  view_only('ZO_USER','INQ.USER');      view_only('ZO_USER','INQ.AUDIT');
  view_only('ZO_USER','REPORTS');       view_only('ZO_USER','REPORTS.SLA');
  view_only('ZO_USER','REPORTS.AGING');
  view_only('ZO_USER','MIS');           view_only('ZO_USER','MIS.VOL');
  view_only('ZO_USER','DASH');          view_only('ZO_USER','DASH.OPS');
  view_only('ZO_USER','DASH.EXEC');

  -- ── ZO_HEAD: + modify team queue ─────────────────────────────────────────
  grant_perm('ZO_HEAD','OPS',           1,1,0,0,0);
  grant_perm('ZO_HEAD','OPS.NEW',       1,1,0,0,0);
  grant_perm('ZO_HEAD','OPS.MINE',      1,0,0,0,0);
  grant_perm('ZO_HEAD','OPS.ASSIGNED',  1,0,1,0,0);
  grant_perm('ZO_HEAD','OPS.TEAM',      1,0,1,0,0);
  grant_perm('ZO_HEAD','OPS.DELEGATE',  1,1,1,0,0);
  view_only('ZO_HEAD','INQ');           view_only('ZO_HEAD','INQ.REQ');
  view_only('ZO_HEAD','INQ.USER');      view_only('ZO_HEAD','INQ.AUDIT');
  view_only('ZO_HEAD','REPORTS');       view_only('ZO_HEAD','REPORTS.DAILY');
  view_only('ZO_HEAD','REPORTS.SLA');   view_only('ZO_HEAD','REPORTS.AGING');
  view_only('ZO_HEAD','MIS');           view_only('ZO_HEAD','MIS.VOL');
  view_only('ZO_HEAD','MIS.PROD');
  view_only('ZO_HEAD','DASH');          view_only('ZO_HEAD','DASH.OPS');
  view_only('ZO_HEAD','DASH.EXEC');

  -- ── CO_USER: ZO_HEAD level ────────────────────────────────────────────────
  grant_perm('CO_USER','OPS',           1,1,0,0,0);
  grant_perm('CO_USER','OPS.NEW',       1,1,0,0,0);
  grant_perm('CO_USER','OPS.MINE',      1,0,0,0,0);
  grant_perm('CO_USER','OPS.ASSIGNED',  1,0,1,0,0);
  grant_perm('CO_USER','OPS.TEAM',      1,0,0,0,0);
  grant_perm('CO_USER','OPS.DELEGATE',  1,1,1,0,0);
  view_only('CO_USER','INQ');           view_only('CO_USER','INQ.REQ');
  view_only('CO_USER','INQ.USER');      view_only('CO_USER','INQ.AUDIT');
  view_only('CO_USER','REPORTS');       view_only('CO_USER','REPORTS.DAILY');
  view_only('CO_USER','REPORTS.SLA');   view_only('CO_USER','REPORTS.AGING');
  view_only('CO_USER','MIS');           view_only('CO_USER','MIS.VOL');
  view_only('CO_USER','MIS.PROD');
  view_only('CO_USER','DASH');          view_only('CO_USER','DASH.OPS');
  view_only('CO_USER','DASH.EXEC');

  -- ── CO_HEAD: + authorize delegations + can view broadcast ────────────────
  grant_perm('CO_HEAD','OPS',           1,1,0,0,0);
  grant_perm('CO_HEAD','OPS.NEW',       1,1,0,0,0);
  grant_perm('CO_HEAD','OPS.MINE',      1,0,0,0,0);
  grant_perm('CO_HEAD','OPS.ASSIGNED',  1,0,1,0,0);
  grant_perm('CO_HEAD','OPS.TEAM',      1,0,1,0,0);
  grant_perm('CO_HEAD','OPS.DELEGATE',  1,1,1,0,1);
  grant_perm('CO_HEAD','OPS.BROADCAST', 1,0,0,0,0);
  view_only('CO_HEAD','INQ');           view_only('CO_HEAD','INQ.REQ');
  view_only('CO_HEAD','INQ.USER');      view_only('CO_HEAD','INQ.AUDIT');
  view_only('CO_HEAD','REPORTS');       view_only('CO_HEAD','REPORTS.DAILY');
  view_only('CO_HEAD','REPORTS.SLA');   view_only('CO_HEAD','REPORTS.AGING');
  view_only('CO_HEAD','MIS');           view_only('CO_HEAD','MIS.VOL');
  view_only('CO_HEAD','MIS.PROD');
  view_only('CO_HEAD','DASH');          view_only('CO_HEAD','DASH.OPS');
  view_only('CO_HEAD','DASH.EXEC');

  -- ── CO_VERT_ADMIN: full ops + broadcast + vertical-level assignment ───────
  -- Can reassign tickets, manage delegations for their vertical, send broadcast.
  -- Access to ADMIN.VERT_ASSIGN restricted to their own vertical in application.
  grant_perm('CO_VERT_ADMIN','OPS',             1,1,0,0,0);
  grant_perm('CO_VERT_ADMIN','OPS.NEW',         1,1,0,0,0);
  grant_perm('CO_VERT_ADMIN','OPS.MINE',        1,0,0,0,0);
  grant_perm('CO_VERT_ADMIN','OPS.ASSIGNED',    1,0,1,0,1);
  grant_perm('CO_VERT_ADMIN','OPS.TEAM',        1,0,1,0,1);
  grant_perm('CO_VERT_ADMIN','OPS.DELEGATE',    1,1,1,1,1);
  grant_perm('CO_VERT_ADMIN','OPS.BROADCAST',   1,1,1,0,1);
  view_only('CO_VERT_ADMIN','INQ');             view_only('CO_VERT_ADMIN','INQ.REQ');
  view_only('CO_VERT_ADMIN','INQ.USER');        view_only('CO_VERT_ADMIN','INQ.AUDIT');
  view_only('CO_VERT_ADMIN','REPORTS');         view_only('CO_VERT_ADMIN','REPORTS.DAILY');
  view_only('CO_VERT_ADMIN','REPORTS.SLA');     view_only('CO_VERT_ADMIN','REPORTS.AGING');
  view_only('CO_VERT_ADMIN','MIS');             view_only('CO_VERT_ADMIN','MIS.VOL');
  view_only('CO_VERT_ADMIN','MIS.PROD');
  view_only('CO_VERT_ADMIN','DASH');            view_only('CO_VERT_ADMIN','DASH.OPS');
  view_only('CO_VERT_ADMIN','DASH.EXEC');
  -- Vertical level assignment (their vertical only — scoped in application code)
  grant_perm('CO_VERT_ADMIN','ADMIN',            1,0,0,0,0);
  grant_perm('CO_VERT_ADMIN','ADMIN.VERT_ASSIGN',1,1,1,1,0);

  -- ── VERT_L1: entry-level vertical processor ───────────────────────────────
  grant_perm('VERT_L1','OPS',         1,1,0,0,0);
  grant_perm('VERT_L1','OPS.NEW',     1,1,0,0,0);
  grant_perm('VERT_L1','OPS.MINE',    1,0,0,0,0);
  grant_perm('VERT_L1','OPS.ASSIGNED',1,0,1,0,0);
  grant_perm('VERT_L1','OPS.TEAM',    1,0,0,0,0);
  view_only('VERT_L1','INQ');         view_only('VERT_L1','INQ.REQ');
  view_only('VERT_L1','DASH');        view_only('VERT_L1','DASH.OPS');

  -- ── VERT_L2: + delegation + inquiry audit + reports ───────────────────────
  grant_perm('VERT_L2','OPS',          1,1,0,0,0);
  grant_perm('VERT_L2','OPS.NEW',      1,1,0,0,0);
  grant_perm('VERT_L2','OPS.MINE',     1,0,0,0,0);
  grant_perm('VERT_L2','OPS.ASSIGNED', 1,0,1,0,0);
  grant_perm('VERT_L2','OPS.TEAM',     1,0,0,0,0);
  grant_perm('VERT_L2','OPS.DELEGATE', 1,1,1,0,0);
  view_only('VERT_L2','INQ');          view_only('VERT_L2','INQ.REQ');
  view_only('VERT_L2','INQ.AUDIT');
  view_only('VERT_L2','REPORTS');      view_only('VERT_L2','REPORTS.SLA');
  view_only('VERT_L2','DASH');         view_only('VERT_L2','DASH.OPS');

  -- ── VERT_L3: + delete on assigned + MIS + exec dashboard ──────────────────
  grant_perm('VERT_L3','OPS',          1,1,0,0,0);
  grant_perm('VERT_L3','OPS.NEW',      1,1,0,0,0);
  grant_perm('VERT_L3','OPS.MINE',     1,0,0,0,0);
  grant_perm('VERT_L3','OPS.ASSIGNED', 1,0,1,1,0);
  grant_perm('VERT_L3','OPS.TEAM',     1,0,1,0,0);
  grant_perm('VERT_L3','OPS.DELEGATE', 1,1,1,0,0);
  view_only('VERT_L3','INQ');          view_only('VERT_L3','INQ.REQ');
  view_only('VERT_L3','INQ.USER');     view_only('VERT_L3','INQ.AUDIT');
  view_only('VERT_L3','REPORTS');      view_only('VERT_L3','REPORTS.SLA');
  view_only('VERT_L3','REPORTS.AGING');
  view_only('VERT_L3','MIS');          view_only('VERT_L3','MIS.VOL');
  view_only('VERT_L3','DASH');         view_only('VERT_L3','DASH.OPS');
  view_only('VERT_L3','DASH.EXEC');

  -- ── VERT_L4: + authorize on assigned/team + broadcast ─────────────────────
  grant_perm('VERT_L4','OPS',          1,1,0,0,0);
  grant_perm('VERT_L4','OPS.NEW',      1,1,0,0,0);
  grant_perm('VERT_L4','OPS.MINE',     1,0,0,0,0);
  grant_perm('VERT_L4','OPS.ASSIGNED', 1,0,1,1,1);
  grant_perm('VERT_L4','OPS.TEAM',     1,0,1,0,1);
  grant_perm('VERT_L4','OPS.DELEGATE', 1,1,1,0,1);
  grant_perm('VERT_L4','OPS.BROADCAST',1,1,1,0,0);
  view_only('VERT_L4','INQ');          view_only('VERT_L4','INQ.REQ');
  view_only('VERT_L4','INQ.USER');     view_only('VERT_L4','INQ.AUDIT');
  view_only('VERT_L4','REPORTS');      view_only('VERT_L4','REPORTS.DAILY');
  view_only('VERT_L4','REPORTS.SLA');  view_only('VERT_L4','REPORTS.AGING');
  view_only('VERT_L4','MIS');          view_only('VERT_L4','MIS.VOL');
  view_only('VERT_L4','MIS.PROD');
  view_only('VERT_L4','DASH');         view_only('VERT_L4','DASH.OPS');
  view_only('VERT_L4','DASH.EXEC');

  -- ── VERT_L5: oversight — view everything, no destructive ops ──────────────
  FOR m IN (
    SELECT CODE FROM RP_RBAC_MODULE
     WHERE CODE NOT LIKE 'MASTERS%' AND CODE NOT LIKE 'ADMIN%'
  ) LOOP
    view_only('VERT_L5', m.CODE);
  END LOOP;

  -- ── APP_ADMIN / SUPER_ADMIN: full access to every module ─────────────────
  admin_full;

END;
/

-- ---------------------------------------------------------------------------
-- 10. PAGE INFO SEED
-- ---------------------------------------------------------------------------
DECLARE
  PROCEDURE upsert_page(
    p_key IN VARCHAR2, p_name IN VARCHAR2, p_type IN VARCHAR2,
    p_desc IN VARCHAR2, p_vert IN VARCHAR2, p_owner IN VARCHAR2,
    p_ip IN VARCHAR2, p_mail IN VARCHAR2, p_ver IN VARCHAR2
  ) IS
    v_n NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_n FROM RP_PAGE_INFO WHERE PAGE_KEY = p_key;
    IF v_n = 0 THEN
      INSERT INTO RP_PAGE_INFO
        (PAGE_KEY,PAGE_NAME,PAGE_TYPE,DESCRIPTION,OWNER_VERTICAL,MODULE_OWNER,IP_NUMBER,MAIL_ID,VERSION,STATUS)
      VALUES (p_key,p_name,p_type,p_desc,p_vert,p_owner,p_ip,p_mail,p_ver,'ACTIVE');
    END IF;
  END;
BEGIN
  upsert_page('app-home','App Home','Dashboard','Landing page.','IT','IT Team','IP-RP-2024-0001','it.support@company.in','v1.0');
  upsert_page('requests-new','New Request','Upload','Submit a new service request.','Operations','Ops Team','IP-RP-2024-0010','ops@company.in','v1.0');
  upsert_page('requests-mine','My Requests','Enquiry','Personal request dashboard.','Operations','Ops Team','IP-RP-2024-0011','ops@company.in','v1.0');
  upsert_page('requests-detail','Request Detail','Enquiry','Full detail view for a single request.','Operations','Ops Team','IP-RP-2024-0012','ops@company.in','v1.0');
  upsert_page('requests-assigned','Assigned to Me','Approve','Handler inbox for pending requests.','Operations','Ops Team','IP-RP-2024-0020','ops@company.in','v1.0');
  upsert_page('requests-team','Team Queue','Approve','Team queue for all pending requests.','Operations','Ops Team','IP-RP-2024-0021','ops@company.in','v1.0');
  upsert_page('requests-delegations','Delegations','Maintenance','Manage delegation rules when a handler is absent.','Operations','Ops Admin','IP-RP-2024-0055','ops.admin@company.in','v1.0');
  upsert_page('oversight-dashboard','Operations Dashboard','Dashboard','Supervisory dashboard with cross-team request metrics.','Operations','Ops Team','IP-RP-2024-0030','ops@company.in','v1.0');
  upsert_page('dashboards-exec','Executive Dashboard','Dashboard','Executive view with vertical-level KPI summaries.','Operations','Ops Admin','IP-RP-2024-0031','ops.admin@company.in','v1.0');
  upsert_page('masters-users','Users Master','Maintenance','Manage employee role overrides.','HR / IT','HR Admin','IP-RP-2024-0040','hr.admin@company.in','v1.0');
  upsert_page('masters-roles','Roles Master','Maintenance','Define and manage portal roles.','IT','IT Admin','IP-RP-2024-0041','it.admin@company.in','v1.0');
  upsert_page('masters-units','Units Master','Maintenance','Business units master.','Operations','Ops Admin','IP-RP-2024-0044','ops.admin@company.in','v1.0');
  upsert_page('admin-broadcast','Broadcast','Maintenance','Send portal-wide announcements.','IT','IT Admin','IP-RP-2024-0056','it.admin@company.in','v1.0');
  upsert_page('admin-audit-search','Audit Search','Report','Search and export audit trail.','Compliance','Compliance Team','IP-RP-2024-0057','compliance@company.in','v1.0');
  upsert_page('rbac-menus','Menu Management','Maintenance','Add and toggle navigation menus.','IT','IT Admin','IP-RP-2024-0060','it.admin@company.in','v1.0');
  upsert_page('rbac-modules','Module Management','Maintenance','Configure portal modules.','IT','IT Admin','IP-RP-2024-0061','it.admin@company.in','v1.0');
  upsert_page('rbac-role-permissions','Role Permissions','Maintenance','Define what each role can do.','IT','IT Admin','IP-RP-2024-0062','it.admin@company.in','v1.0');
  upsert_page('rbac-admin-rights','Admin Rights','Maintenance','Grant or revoke App Admin privileges.','IT','IT Admin','IP-RP-2024-0063','it.admin@company.in','v1.0');
  upsert_page('rbac-vertical-assignment','Vertical Level Assignment','Maintenance','CO Vertical Admin assigns VERT_L1–L5 to employees within their vertical.','IT','IT Admin','IP-RP-2024-0064','it.admin@company.in','v1.0');
  upsert_page('rbac-audit-log','RBAC Audit Log','Report','Audit log of all RBAC changes.','Compliance','Compliance Team','IP-RP-2024-0065','compliance@company.in','v1.0');
  upsert_page('reports-sla','SLA Report','Report','SLA compliance with breach analysis.','Operations','Ops Admin','IP-RP-2024-0070','ops.admin@company.in','v1.0');
  upsert_page('notifications','Notifications','Enquiry','User notification centre.','IT','IT Admin','IP-RP-2024-0080','it.admin@company.in','v1.0');
  upsert_page('profile-user','User Profile','Maintenance','View personal profile.','HR / IT','IT Admin','IP-RP-2024-0081','it.admin@company.in','v1.0');
  upsert_page('inquiry-requests','Request Inquiry','Enquiry','Search request status.','Operations','Ops Team','IP-RP-2024-0083','ops@company.in','v1.0');
  upsert_page('inquiry-users','User Inquiry','Enquiry','View employee details and role assignments.','IT','IT Admin','IP-RP-2024-0084','it.admin@company.in','v1.0');
END;
/

COMMIT;

-- ##################### 3. SUPER ADMIN SEED #####################
-- ============================================================================
-- Request Portal — Super Admin Seeding v3.0
-- Schema   : RP_OWNER
-- Run after: 01_schema.sql + 02_seed.sql
-- Cap      : Application enforces max 2 Super Admins (RbacConstants.MaxSuperAdmins)
--
-- RP_RBAC_SUPER_ADMIN now uses EMP_CODE VARCHAR2(20) directly —
-- no dependency on RP_USER table.
-- ============================================================================

SET SERVEROUTPUT ON;

-- ---------------------------------------------------------------------------
-- Section A — Primary Super Admin  (EMP_CODE = 860921)
-- ---------------------------------------------------------------------------
DECLARE
BEGIN
  MERGE INTO RP_RBAC_SUPER_ADMIN t
  USING (SELECT '860921' AS EMP_CODE FROM DUAL) s ON (t.EMP_CODE = s.EMP_CODE)
  WHEN NOT MATCHED THEN
    INSERT (ID, EMP_CODE, ASSIGNED_AT_UTC, ASSIGNED_BY)
    VALUES (RP_SEQ_GLOBAL.NEXTVAL, '860921', SYSTIMESTAMP, 'BOOT_SEED');

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('SuperAdmin seeded: EMP_CODE=860921');
EXCEPTION
  WHEN OTHERS THEN ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM); RAISE;
END;
/

-- ---------------------------------------------------------------------------
-- Section B — Second Super Admin (uncomment and fill in EMP_CODE before running)
-- ---------------------------------------------------------------------------
--
-- DECLARE
-- BEGIN
--   MERGE INTO RP_RBAC_SUPER_ADMIN t
--   USING (SELECT 'REPLACE_EMP_CODE' AS EMP_CODE FROM DUAL) s ON (t.EMP_CODE = s.EMP_CODE)
--   WHEN NOT MATCHED THEN
--     INSERT (ID, EMP_CODE, ASSIGNED_AT_UTC, ASSIGNED_BY)
--     VALUES (RP_SEQ_GLOBAL.NEXTVAL, 'REPLACE_EMP_CODE', SYSTIMESTAMP, 'BOOT_SEED');
--   COMMIT;
--   DBMS_OUTPUT.PUT_LINE('SuperAdmin seeded: second super admin');
-- EXCEPTION
--   WHEN OTHERS THEN ROLLBACK;
--     DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM); RAISE;
-- END;
-- /

-- ##################### 4. MY DIARY CORE SEED (MD_* roles/modules/perms, sitemap) #####################
SET SQLBLANKLINES ON
-- ============================================================
-- My Diary V3 — Oracle Seed Data
-- Roles, RBAC modules, notification templates
-- ============================================================

-- ── Roles (maps to RoleCode enum) ────────────────────────────────────────

INSERT INTO MD_ROLE (CODE, NAME) VALUES (1,  'BranchUser');
INSERT INTO MD_ROLE (CODE, NAME) VALUES (2,  'BranchHead');
INSERT INTO MD_ROLE (CODE, NAME) VALUES (3,  'RoUser');
INSERT INTO MD_ROLE (CODE, NAME) VALUES (4,  'RoHead');
INSERT INTO MD_ROLE (CODE, NAME) VALUES (5,  'ZoUser');
INSERT INTO MD_ROLE (CODE, NAME) VALUES (6,  'ZoHead');
INSERT INTO MD_ROLE (CODE, NAME) VALUES (7,  'CoUser');
INSERT INTO MD_ROLE (CODE, NAME) VALUES (8,  'CoHead');
INSERT INTO MD_ROLE (CODE, NAME) VALUES (9,  'CoVertAdmin');
INSERT INTO MD_ROLE (CODE, NAME) VALUES (10, 'AppAdmin');
INSERT INTO MD_ROLE (CODE, NAME) VALUES (11, 'SuperAdmin');
INSERT INTO MD_ROLE (CODE, NAME) VALUES (12, 'VertL1');
INSERT INTO MD_ROLE (CODE, NAME) VALUES (13, 'VertL2');
INSERT INTO MD_ROLE (CODE, NAME) VALUES (14, 'VertL3');
INSERT INTO MD_ROLE (CODE, NAME) VALUES (15, 'VertL4');
INSERT INTO MD_ROLE (CODE, NAME) VALUES (16, 'VertL5');

-- ── RBAC Modules ─────────────────────────────────────────────────────────

INSERT INTO MD_RBAC_MODULE (CODE, DISPLAY_NAME, KIND, SORT_ORDER)
VALUES ('HOME',             'Home Dashboard',       5, 1);

INSERT INTO MD_RBAC_MODULE (CODE, DISPLAY_NAME, KIND, SORT_ORDER)
VALUES ('KPI',              'Key Performance',      5, 2);

INSERT INTO MD_RBAC_MODULE (CODE, DISPLAY_NAME, KIND, SORT_ORDER)
VALUES ('FOCUS360',         'Focus 360',            5, 3);

INSERT INTO MD_RBAC_MODULE (CODE, DISPLAY_NAME, KIND, SORT_ORDER)
VALUES ('BUSINESS360',      'Business 360',         5, 4);

INSERT INTO MD_RBAC_MODULE (CODE, DISPLAY_NAME, KIND, SORT_ORDER)
VALUES ('ASSURANCE',        'Assurance Corner',     3, 5);

INSERT INTO MD_RBAC_MODULE (CODE, DISPLAY_NAME, KIND, SORT_ORDER)
VALUES ('APPLICATIONS',     'Applications',         5, 6);

INSERT INTO MD_RBAC_MODULE (CODE, DISPLAY_NAME, KIND, SORT_ORDER)
VALUES ('DEPARTMENTS',      'Departments',          5, 7);

INSERT INTO MD_RBAC_MODULE (CODE, DISPLAY_NAME, KIND, SORT_ORDER)
VALUES ('DOWNLOADS',        'Downloads',            5, 8);

INSERT INTO MD_RBAC_MODULE (CODE, DISPLAY_NAME, KIND, SORT_ORDER)
VALUES ('MIS',              'MIS',                  4, 9);

INSERT INTO MD_RBAC_MODULE (CODE, DISPLAY_NAME, KIND, SORT_ORDER)
VALUES ('REQUEST_PORTAL',   'Request Portal',       1, 10);

INSERT INTO MD_RBAC_MODULE (CODE, DISPLAY_NAME, KIND, SORT_ORDER)
VALUES ('NOTIFICATIONS',    'Notifications',        5, 11);

INSERT INTO MD_RBAC_MODULE (CODE, DISPLAY_NAME, KIND, SORT_ORDER)
VALUES ('ADMIN',            'Administration',       1, 99);

-- ── Grant VIEW on all modules to all roles by default ─────────────────────
-- This fulfils the requirement: "All Project B pages accessible to all users initially"

DECLARE
    CURSOR c_roles   IS SELECT ID FROM MD_ROLE;
    CURSOR c_modules IS SELECT ID FROM MD_RBAC_MODULE;
BEGIN
    FOR r IN c_roles LOOP
        FOR m IN c_modules LOOP
            INSERT INTO MD_ROLE_MODULE_PERM
                (ROLE_ID, MODULE_ID, CAN_VIEW, CAN_ADD, CAN_MODIFY, CAN_DELETE, CAN_AUTHORIZE)
            VALUES
                (r.ID, m.ID, 1, 0, 0, 0, 0);
        END LOOP;
    END LOOP;
    COMMIT;
END;
/

-- ── Sample notification templates ─────────────────────────────────────────

INSERT INTO MD_NOTIF_TEMPLATE (EVENT_CODE, CHANNEL, SUBJECT, BODY, IS_ACTIVE)
VALUES (
    'REQUEST_CREATED', 1,
    'New Request Created — {{ReqNo}}',
    'Dear {{RecipientName}},\n\nA new request {{ReqNo}} has been submitted by {{RaisedByName}}.\n\nType: {{RequestTypeName}}\nStatus: {{Status}}\n\nPlease log in to My Diary to review.\n\nRegards,\nMy Diary System',
    1
);

INSERT INTO MD_NOTIF_TEMPLATE (EVENT_CODE, CHANNEL, SUBJECT, BODY, IS_ACTIVE)
VALUES (
    'REQUEST_RESOLVED', 1,
    'Request Resolved — {{ReqNo}}',
    'Dear {{RecipientName}},\n\nYour request {{ReqNo}} has been resolved.\n\nPlease log in to My Diary to provide feedback.\n\nRegards,\nMy Diary System',
    1
);

-- ── Sitemap for search ────────────────────────────────────────────────────

INSERT INTO MYDIARY_LANDING_SITEMAP (NAME, URL, CATEGORY, KEYWORDS)
VALUES ('Home Dashboard', '/Landing_Dashboard_V2_1', 'Dashboard', 'home dashboard main landing');

INSERT INTO MYDIARY_LANDING_SITEMAP (NAME, URL, CATEGORY, KEYWORDS)
VALUES ('KPI Dashboard', '/dashboard_new_1', 'Dashboard', 'kpi key performance indicator metrics');

INSERT INTO MYDIARY_LANDING_SITEMAP (NAME, URL, CATEGORY, KEYWORDS)
VALUES ('Focus 360', '/focus360', 'Analytics', 'focus 360 gap performance report');

INSERT INTO MYDIARY_LANDING_SITEMAP (NAME, URL, CATEGORY, KEYWORDS)
VALUES ('Business 360', '/business-new', 'Analytics', 'business 360 business report');

INSERT INTO MYDIARY_LANDING_SITEMAP (NAME, URL, CATEGORY, KEYWORDS)
VALUES ('New Request', '/requests/new', 'Requests', 'new request create submit ticket');

INSERT INTO MYDIARY_LANDING_SITEMAP (NAME, URL, CATEGORY, KEYWORDS)
VALUES ('My Requests', '/requests/mine', 'Requests', 'my requests status track');

INSERT INTO MYDIARY_LANDING_SITEMAP (NAME, URL, CATEGORY, KEYWORDS)
VALUES ('MIS Reports', '/MIS', 'Reports', 'mis management information system reports');

COMMIT;

COMMIT;
-- ===================== END OF MIGRATION =====================
