-- ============ SEQUENCES ============

   CREATE SEQUENCE  "RP_OWNER"."MD_SEQ_GLOBAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1229 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "RP_OWNER"."RP_SEQ_GLOBAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1501 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "RP_OWNER"."RP_SEQ_REQUEST"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 50 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

-- ============ TABLES (PK/UK/CHECK inline; FKs added later) ============

  CREATE TABLE "RP_OWNER"."EASE_ATR"
   (	"ID" NUMBER NOT NULL ENABLE,
	"DIRECTION_ID" NUMBER NOT NULL ENABLE,
	"ATR_TEXT" CLOB NOT NULL ENABLE,
	"SUBMITTED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"SUBMITTED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"ACCEPTED_AT" TIMESTAMP (6),
	"ACCEPTED_BY_EMP" VARCHAR2(20),
	 CONSTRAINT "PK_EASE_ATR" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_ATTACHMENT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"REF_TYPE" VARCHAR2(15) NOT NULL ENABLE,
	"REF_ID" NUMBER NOT NULL ENABLE,
	"FILE_NAME" VARCHAR2(500) NOT NULL ENABLE,
	"MIME" VARCHAR2(100),
	"SIZE_BYTES" NUMBER,
	"STORAGE_KEY" VARCHAR2(1000) NOT NULL ENABLE,
	"UPLOADED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"UPLOADED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_EASE_ATT_TYP" CHECK (REF_TYPE IN ('RESPONSE','CLARIF','INITIATIVE')) ENABLE,
	 CONSTRAINT "PK_EASE_ATT" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_CAMPAIGN"
   (	"ID" NUMBER NOT NULL ENABLE,
	"PILLAR" VARCHAR2(2) NOT NULL ENABLE,
	"CAMPAIGN_TYPE" VARCHAR2(15) NOT NULL ENABLE,
	"TITLE" VARCHAR2(200) NOT NULL ENABLE,
	"PERIOD_MONTH" NUMBER(2,0),
	"PERIOD_YEAR" NUMBER(4,0) NOT NULL ENABLE,
	"PERIOD_QUARTER" NUMBER(1,0),
	"FREQ" VARCHAR2(1) NOT NULL ENABLE,
	"STATUS" VARCHAR2(10) DEFAULT 'DRAFT' NOT NULL ENABLE,
	"OPEN_DATE" DATE,
	"CLOSE_DATE" DATE,
	"CREATED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_EASE_CAMP_PIL" CHECK (PILLAR IN ('I','II')) ENABLE,
	 CONSTRAINT "CK_EASE_CAMP_TYP" CHECK (CAMPAIGN_TYPE IN ('KCI','KPI','INITIATIVE')) ENABLE,
	 CONSTRAINT "CK_EASE_CAMP_FRQ" CHECK (FREQ IN ('M','Q')) ENABLE,
	 CONSTRAINT "CK_EASE_CAMP_STS" CHECK (STATUS IN ('DRAFT','OPEN','CLOSED')) ENABLE,
	 CONSTRAINT "PK_EASE_CAMP" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_CLARIFICATION"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ASSIGNMENT_ID" NUMBER NOT NULL ENABLE,
	"RAISED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"RAISED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"QUESTION_TEXT" CLOB NOT NULL ENABLE,
	"ANSWERED_BY_EMP" VARCHAR2(20),
	"ANSWERED_AT" TIMESTAMP (6),
	"ANSWER_TEXT" CLOB,
	"STATUS" VARCHAR2(10) DEFAULT 'OPEN' NOT NULL ENABLE,
	 CONSTRAINT "CK_EASE_CLARIF_STS" CHECK (STATUS IN ('OPEN','ANSWERED','CLOSED')) ENABLE,
	 CONSTRAINT "PK_EASE_CLARIF" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_DIRECTION"
   (	"ID" NUMBER NOT NULL ENABLE,
	"REF_TYPE" VARCHAR2(15) NOT NULL ENABLE,
	"REF_ID" NUMBER NOT NULL ENABLE,
	"MEETING_DATE" DATE NOT NULL ENABLE,
	"DIRECTION_TEXT" CLOB NOT NULL ENABLE,
	"DIRECTED_TO_EMP" VARCHAR2(20),
	"STATUS" VARCHAR2(15) DEFAULT 'OPEN' NOT NULL ENABLE,
	"RECORDED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"RECORDED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_EASE_DIR_TYP" CHECK (REF_TYPE IN ('METRIC','INITIATIVE')) ENABLE,
	 CONSTRAINT "CK_EASE_DIR_STS" CHECK (STATUS IN ('OPEN','ATR_SUBMITTED','CLOSED')) ENABLE,
	 CONSTRAINT "PK_EASE_DIR" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_INITIATIVE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"CAMPAIGN_ID" NUMBER NOT NULL ENABLE,
	"INITIATIVE_NAME" VARCHAR2(500) NOT NULL ENABLE,
	"OBJECTIVE" CLOB,
	"RATIONALE" CLOB,
	"SOLUTION_DETAILS" CLOB,
	"BUSINESS_IMPACT" CLOB,
	"COST_INCURRED" VARCHAR2(3),
	"EXPECTED_COST" NUMBER(20,2),
	"VENDOR_REQUIRED" VARCHAR2(3),
	"VENDOR_NAME" VARCHAR2(300),
	"PO_ISSUED" VARCHAR2(3),
	"MGMT_APPROVED" VARCHAR2(3),
	"RBI_STRATEGY_LINKED" VARCHAR2(3),
	"PREV_STR_LINKED" VARCHAR2(3),
	"INIT_REVISION" NUMBER(1,0) DEFAULT 0,
	"OWNER_EMP_CODE" VARCHAR2(20),
	"OWNER_DEPT" VARCHAR2(200),
	"OWNER_CONTACT" VARCHAR2(20),
	"STATUS" VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL ENABLE,
	"CREATED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "PK_EASE_INIT" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_INITIATIVE_METRIC"
   (	"ID" NUMBER NOT NULL ENABLE,
	"INITIATIVE_ID" NUMBER NOT NULL ENABLE,
	"SEQ_NO" NUMBER NOT NULL ENABLE,
	"METRIC_DESC" VARCHAR2(500) NOT NULL ENABLE,
	"FY25_ACTUAL" NUMBER(20,2),
	 CONSTRAINT "PK_EASE_INIT_MET" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_INITIATIVE_PERF"
   (	"ID" NUMBER NOT NULL ENABLE,
	"INITIATIVE_METRIC_ID" NUMBER NOT NULL ENABLE,
	"FY" NUMBER(4,0) NOT NULL ENABLE,
	"QUARTER" VARCHAR2(10) NOT NULL ENABLE,
	"PERIOD_TYPE" VARCHAR2(10) NOT NULL ENABLE,
	"PERF_VALUE" NUMBER(20,2),
	"ENTERED_BY_EMP" VARCHAR2(20),
	"ENTERED_AT" TIMESTAMP (6),
	 CONSTRAINT "CK_EASE_PERF_QRT" CHECK (QUARTER IN ('Q1','Q2','Q3','Q4','ANNUAL')) ENABLE,
	 CONSTRAINT "CK_EASE_PERF_TYP" CHECK (PERIOD_TYPE IN ('ACTUAL','TARGET')) ENABLE,
	 CONSTRAINT "PK_EASE_PERF" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_METRIC_MASTER"
   (	"ID" NUMBER NOT NULL ENABLE,
	"CAMPAIGN_ID" NUMBER NOT NULL ENABLE,
	"ROW_ID" NUMBER NOT NULL ENABLE,
	"METRIC_TYPE" VARCHAR2(100),
	"METRIC_SORT" NUMBER,
	"METRIC_ID" VARCHAR2(50),
	"METRIC_DESC" VARCHAR2(2000),
	"EXPL_COMMENTS" CLOB,
	"RESP_TYPE_ACCOUNTS" NUMBER(1,0) DEFAULT 0,
	"RESP_TYPE_AMOUNT" NUMBER(1,0) DEFAULT 0,
	"RESP_TYPE_YESNO" NUMBER(1,0) DEFAULT 0,
	"HAS_SEGMENTS" NUMBER(1,0) DEFAULT 0,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1,
	 CONSTRAINT "PK_EASE_METRIC" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_METRIC_RESPONSE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ASSIGNMENT_ID" NUMBER NOT NULL ENABLE,
	"VERSION" NUMBER DEFAULT 1 NOT NULL ENABLE,
	"RESP_VALUE" VARCHAR2(4000),
	"RESP_ACCOUNTS" NUMBER,
	"RESP_AMOUNT" NUMBER(20,2),
	"RESP_YESNO" VARCHAR2(3),
	"DATA_SOURCE" VARCHAR2(500),
	"BANK_COMMENTS" CLOB,
	"BMO_EMP_CODE" VARCHAR2(20),
	"BMO_CONTACT" VARCHAR2(20),
	"IS_DRAFT" NUMBER(1,0) DEFAULT 1,
	"SUBMITTED_AT" TIMESTAMP (6),
	"SUBMITTED_BY_EMP" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "PK_EASE_RESP" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_METRIC_SEGMENT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"RESPONSE_ID" NUMBER NOT NULL ENABLE,
	"SEGMENT_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"SEGMENT_NAME" VARCHAR2(100),
	"VALUE_ACCOUNTS" NUMBER,
	"VALUE_AMOUNT" NUMBER(20,2),
	 CONSTRAINT "PK_EASE_SEG" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_ROLE_ASSIGNMENT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"ROLE_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"UNIT_ID" NUMBER,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"GRANTED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"GRANTED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"REVOKED_AT" TIMESTAMP (6),
	 CONSTRAINT "PK_EASE_ROLE" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"CAMPAIGN_ID" NUMBER NOT NULL ENABLE,
	"METRIC_ID" NUMBER NOT NULL ENABLE,
	"UNIT_ID" NUMBER NOT NULL ENABLE,
	"SPOC_EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"ORIGINAL_DUE_DATE" DATE NOT NULL ENABLE,
	"REVISED_DUE_DATE" DATE,
	"REVISION_REASON" VARCHAR2(500),
	"STATUS" VARCHAR2(20) DEFAULT 'PENDING' NOT NULL ENABLE,
	"ASSIGNED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"ASSIGNED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_EASE_VASN_STS" CHECK (STATUS IN ('PENDING','SUBMITTED','UNDER_REVIEW','CLARIFICATION','ACCEPTED','REJECTED')) ENABLE,
	 CONSTRAINT "PK_EASE_VASN" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."EASE_VERT_INITIATIVE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"INITIATIVE_ID" NUMBER NOT NULL ENABLE,
	"UNIT_ID" NUMBER NOT NULL ENABLE,
	"SPOC_EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"DUE_DATE" DATE,
	"STATUS" VARCHAR2(20) DEFAULT 'PENDING' NOT NULL ENABLE,
	 CONSTRAINT "CK_EASE_VI_STS" CHECK (STATUS IN ('PENDING','SUBMITTED','ACCEPTED','REJECTED')) ENABLE,
	 CONSTRAINT "PK_EASE_VI" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_DELEGATION"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"FROM_EMPL_ID" VARCHAR2(50) NOT NULL ENABLE,
	"TO_EMPL_ID" VARCHAR2(50) NOT NULL ENABLE,
	"ROLE_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"VERTICAL_CODE" VARCHAR2(50),
	"VALID_FROM" DATE NOT NULL ENABLE,
	"VALID_TO" DATE NOT NULL ENABLE,
	"REASON" VARCHAR2(500),
	"MODIFIED_BY_EMP" VARCHAR2(50),
	"MODIFIED_AT" TIMESTAMP (6),
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_INAPP_NOTIF"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"EMPL_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"TITLE" VARCHAR2(200) NOT NULL ENABLE,
	"BODY" VARCHAR2(2000),
	"HREF" VARCHAR2(500),
	"IS_READ" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_NOTIF_OUTBOX"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"EVENT_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"CHANNEL" NUMBER(2,0) NOT NULL ENABLE,
	"TO_ADDRESS" VARCHAR2(200) NOT NULL ENABLE,
	"TO_EMPL_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"PAYLOAD_JSON" CLOB,
	"STATUS" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"ATTEMPTS" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE,
	"LAST_ERROR" VARCHAR2(500),
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"SENT_AT" TIMESTAMP (6),
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_NOTIF_TEMPLATE"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"EVENT_CODE" VARCHAR2(100) NOT NULL ENABLE,
	"CHANNEL" NUMBER(2,0) NOT NULL ENABLE,
	"SUBJECT" VARCHAR2(500),
	"BODY" CLOB NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_NOTIF_TEMPLATE" UNIQUE ("EVENT_CODE", "CHANNEL")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_RBAC_MENU"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"MODULE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"LABEL" VARCHAR2(200) NOT NULL ENABLE,
	"HREF" VARCHAR2(500),
	"ICON" VARCHAR2(100),
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_RBAC_MODULE"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"CODE" VARCHAR2(100) NOT NULL ENABLE,
	"DISPLAY_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"PARENT_ID" NUMBER(19,0),
	"KIND" NUMBER(2,0) NOT NULL ENABLE,
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_MD_RBAC_MODULE_CODE" UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_ROLE"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"CODE" NUMBER(5,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(100) NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_MD_ROLE_CODE" UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_ROLE_MODULE_PERM"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"ROLE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"MODULE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"CAN_VIEW" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_ADD" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_MODIFY" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_DELETE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_AUTHORIZE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_ROLE_MODULE" UNIQUE ("ROLE_ID", "MODULE_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_USER"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"EMPL_ID" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(200),
	"MOBILE" VARCHAR2(20),
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6),
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_MD_USER_EMPL_ID" UNIQUE ("EMPL_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_USER_MODULE_PERM"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"EMPL_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"MODULE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"CAN_VIEW" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_ADD" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_MODIFY" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_DELETE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_AUTHORIZE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"IS_DENY" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_USER_MODULE" UNIQUE ("EMPL_CODE", "MODULE_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MD_USER_ROLE"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"USER_ID" NUMBER(19,0) NOT NULL ENABLE,
	"ROLE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"VALID_FROM" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"VALID_TO" DATE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."MYDIARY_LANDING_SITEMAP"
   (	"ID" NUMBER(19,0) DEFAULT "RP_OWNER"."MD_SEQ_GLOBAL"."NEXTVAL",
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"URL" VARCHAR2(500) NOT NULL ENABLE,
	"CATEGORY" VARCHAR2(100),
	"SUB_CATEGORY" VARCHAR2(100),
	"DESCRIPTION" VARCHAR2(2000),
	"KEYWORDS" VARCHAR2(2000),
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_AUDIT_LOG"
   (	"ID" NUMBER(19,0),
	"ENTITY" VARCHAR2(60) NOT NULL ENABLE,
	"ENTITY_ID" NUMBER(19,0) NOT NULL ENABLE,
	"ACTION" VARCHAR2(40) NOT NULL ENABLE,
	"ACTOR_EMP_CODE" VARCHAR2(20),
	"ACTED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"OLD_JSON" CLOB,
	"NEW_JSON" CLOB,
	"IP" VARCHAR2(64),
	"USER_AGENT" VARCHAR2(500),
	"HASH_PREV" VARCHAR2(64),
	"HASH_CURR" VARCHAR2(64) NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_DELEGATION"
   (	"ID" NUMBER(19,0),
	"FROM_EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"TO_EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"ROLE_CODE" VARCHAR2(30) NOT NULL ENABLE,
	"VERTICAL_CODE" VARCHAR2(50),
	"VALID_FROM" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE,
	"VALID_TO" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE,
	"REASON" VARCHAR2(500),
	"MODIFIED_BY_EMP" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 CONSTRAINT "CK_DELEG_DIFF" CHECK (FROM_EMP_CODE <> TO_EMP_CODE) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_ACTIVITY"
   (	"ID" NUMBER(19,0),
	"DEPARTMENT_ID" NUMBER(19,0) NOT NULL ENABLE,
	"CODE" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_DEPARTMENT"
   (	"ID" NUMBER(19,0),
	"VERTICAL_ID" NUMBER(19,0) NOT NULL ENABLE,
	"CODE" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_HOLIDAY"
   (	"ID" NUMBER(19,0),
	"CAL_ID" NUMBER(19,0) NOT NULL ENABLE,
	"HOLIDAY_DATE" DATE NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(200),
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UK_HOLIDAY" UNIQUE ("CAL_ID", "HOLIDAY_DATE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_HOLIDAY_CAL"
   (	"ID" NUMBER(19,0),
	"CODE" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_NOTIF_TEMPLATE"
   (	"ID" NUMBER(19,0),
	"EVENT_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"CHANNEL" NUMBER(1,0) NOT NULL ENABLE,
	"SUBJECT" VARCHAR2(500),
	"BODY" CLOB NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 CONSTRAINT "CK_NOTIF_CHN" CHECK (CHANNEL IN (1, 2)) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UK_NOTIF_TPL" UNIQUE ("EVENT_CODE", "CHANNEL")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_REQUEST_TYPE"
   (	"ID" NUMBER(19,0),
	"CODE" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_ROUTING_ASSIGNEE"
   (	"ID" NUMBER(19,0),
	"RULE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"IS_PRIMARY" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_ROUTING_RULE"
   (	"ID" NUMBER(19,0),
	"REQUEST_TYPE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"UNIT_TYPE_ID" NUMBER(19,0),
	"VERTICAL_ID" NUMBER(19,0),
	"DEPARTMENT_ID" NUMBER(19,0),
	"ACTIVITY_ID" NUMBER(19,0),
	"PRIORITY" NUMBER(5,0) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_SLA_CONFIG"
   (	"ID" NUMBER(19,0),
	"REQUEST_TYPE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"LEVEL_NO" NUMBER(2,0) NOT NULL ENABLE,
	"WORKING_DAYS" NUMBER(3,0) NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 CONSTRAINT "CK_SLA_LEVEL" CHECK (LEVEL_NO BETWEEN 1 AND 5) ENABLE,
	 CONSTRAINT "CK_SLA_DAYS" CHECK (WORKING_DAYS > 0) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UK_SLA" UNIQUE ("REQUEST_TYPE_ID", "LEVEL_NO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_UNIT"
   (	"ID" NUMBER(19,0),
	"UNIT_TYPE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"PARENT_UNIT_ID" NUMBER(19,0),
	"CODE" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"HOLIDAY_CAL_ID" NUMBER(19,0),
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_UNIT_TYPE"
   (	"ID" NUMBER(19,0),
	"CODE" VARCHAR2(20) NOT NULL ENABLE,
	"NAME" VARCHAR2(100) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_M_VERTICAL"
   (	"ID" NUMBER(19,0),
	"CODE" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(20),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP,
	"MODIFIED_BY" VARCHAR2(20),
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_NOTIFICATION"
   (	"ID" NUMBER(19,0),
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"TITLE" VARCHAR2(200) NOT NULL ENABLE,
	"MESSAGE" VARCHAR2(2000),
	"CATEGORY" VARCHAR2(50),
	"REDIRECT_URL" VARCHAR2(500),
	"SOURCE" VARCHAR2(20) NOT NULL ENABLE,
	"EVENT_CODE" VARCHAR2(50),
	"REQUEST_ID" NUMBER(19,0),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"READ_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_NOTIF_OUTBOX"
   (	"ID" NUMBER(19,0),
	"EVENT_CODE" VARCHAR2(50) NOT NULL ENABLE,
	"CHANNEL" NUMBER(1,0) NOT NULL ENABLE,
	"TO_ADDR" VARCHAR2(300) NOT NULL ENABLE,
	"PAYLOAD_JSON" CLOB NOT NULL ENABLE,
	"STATUS" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"ATTEMPTS" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE,
	"LAST_ERROR" VARCHAR2(2000),
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"SENT_AT" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_PAGE_INFO"
   (	"PAGE_KEY" VARCHAR2(100) NOT NULL ENABLE,
	"PAGE_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"PAGE_TYPE" VARCHAR2(50) DEFAULT 'Dashboard' NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(1000),
	"OWNER_VERTICAL" VARCHAR2(200),
	"MODULE_OWNER" VARCHAR2(200),
	"IP_NUMBER" VARCHAR2(100),
	"MAIL_ID" VARCHAR2(200),
	"VERSION" VARCHAR2(20) DEFAULT 'v1.0',
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE',
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"UPDATED_DATE" DATE,
	 CONSTRAINT "CHK_PI_STATUS" CHECK (STATUS   IN ('ACTIVE','INACTIVE','DEPRECATED')) ENABLE,
	 CONSTRAINT "CHK_PI_TYPE" CHECK (PAGE_TYPE IN ('Dashboard','Report','Upload','Approve','Enquiry','Maintenance','Other')) ENABLE,
	 CONSTRAINT "PK_RP_PAGE_INFO" PRIMARY KEY ("PAGE_KEY")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_APP_ADMIN"
   (	"ID" NUMBER(19,0),
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"ASSIGNED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"ASSIGNED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"NOTE" VARCHAR2(1000),
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("EMP_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_AUDIT"
   (	"ID" NUMBER(19,0),
	"AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"ACTOR_EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"ACTION" VARCHAR2(40) NOT NULL ENABLE,
	"TARGET" VARCHAR2(300) NOT NULL ENABLE,
	"DETAILS" VARCHAR2(2000),
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_MENU"
   (	"ID" NUMBER(19,0),
	"MODULE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"CODE" VARCHAR2(80) NOT NULL ENABLE,
	"LABEL" VARCHAR2(200) NOT NULL ENABLE,
	"ICON" VARCHAR2(60),
	"ROUTE" VARCHAR2(300) NOT NULL ENABLE,
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE,
	"IS_ENABLED" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_MODULE"
   (	"ID" NUMBER(19,0),
	"CODE" VARCHAR2(60) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"KIND" NUMBER(2,0) DEFAULT 1 NOT NULL ENABLE,
	"PARENT_ID" NUMBER(19,0),
	"ICON" VARCHAR2(60),
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_RBAC_MOD_KIND" CHECK (KIND BETWEEN 1 AND 5) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_ROLE_PERM"
   (	"ID" NUMBER(19,0),
	"ROLE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"MODULE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"CAN_VIEW" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_ADD" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_MODIFY" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_DELETE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_AUTHORIZE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"UPDATED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UK_RBAC_ROLE_MOD" UNIQUE ("ROLE_ID", "MODULE_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_SUPER_ADMIN"
   (	"ID" NUMBER(19,0),
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"ASSIGNED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"ASSIGNED_BY" VARCHAR2(60) DEFAULT 'BOOT' NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("EMP_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_USER_PERM"
   (	"ID" NUMBER(19,0),
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"MODULE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"IS_DENY" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_VIEW" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_ADD" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_MODIFY" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_DELETE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CAN_AUTHORIZE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"UPDATED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UK_RBAC_USER_MOD" UNIQUE ("EMP_CODE", "MODULE_ID", "IS_DENY")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_VERTICAL_ADMIN"
   (	"ID" NUMBER(19,0),
	"VERTICAL_ID" NUMBER(19,0) NOT NULL ENABLE,
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"ASSIGNED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"ASSIGNED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"REVOKED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UK_VERT_ADMIN" UNIQUE ("VERTICAL_ID", "EMP_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_RBAC_VERTICAL_LEVEL"
   (	"ID" NUMBER(19,0),
	"VERTICAL_ID" NUMBER(19,0) NOT NULL ENABLE,
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"LEVEL_CODE" VARCHAR2(10) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"ASSIGNED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"ASSIGNED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"REVOKED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE,
	 CONSTRAINT "CK_LEVEL_CODE" CHECK (LEVEL_CODE IN ('VERT_L1','VERT_L2','VERT_L3','VERT_L4','VERT_L5')) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UK_VERT_LEVEL" UNIQUE ("VERTICAL_ID", "EMP_CODE", "LEVEL_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_REQUEST"
   (	"ID" NUMBER(19,0),
	"REQ_NO" VARCHAR2(20) NOT NULL ENABLE,
	"REQUEST_TYPE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"UNIT_ID" NUMBER(19,0) NOT NULL ENABLE,
	"VERTICAL_ID" NUMBER(19,0) NOT NULL ENABLE,
	"DEPARTMENT_ID" NUMBER(19,0) NOT NULL ENABLE,
	"ACTIVITY_ID" NUMBER(19,0) NOT NULL ENABLE,
	"RAISED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"SUBJECT" VARCHAR2(500) NOT NULL ENABLE,
	"DESCRIPTION" CLOB NOT NULL ENABLE,
	"CURRENT_LEVEL" NUMBER(2,0) DEFAULT 1 NOT NULL ENABLE,
	"STATUS" NUMBER(2,0) DEFAULT 1 NOT NULL ENABLE,
	"SLA_DUE_UTC" TIMESTAMP (6) WITH TIME ZONE,
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"CLOSED_AT" TIMESTAMP (6) WITH TIME ZONE,
	"ROW_VERSION" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
	"RAISED_BY" NUMBER,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("REQ_NO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_REQUEST_ACTION"
   (	"ID" NUMBER(19,0),
	"REQUEST_ID" NUMBER(19,0) NOT NULL ENABLE,
	"LEVEL_NO" NUMBER(2,0) NOT NULL ENABLE,
	"ACTOR_EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"ACTION" VARCHAR2(50) NOT NULL ENABLE,
	"REMARKS" VARCHAR2(2000),
	"ACTED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_REQUEST_ASSIGNEE"
   (	"ID" NUMBER(19,0),
	"REQUEST_ID" NUMBER(19,0) NOT NULL ENABLE,
	"LEVEL_NO" NUMBER(2,0) NOT NULL ENABLE,
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"ASSIGNED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"ASSIGNED_BY_EMP" VARCHAR2(20),
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_REQUEST_ATTACHMENT"
   (	"ID" NUMBER(19,0),
	"REQUEST_ID" NUMBER(19,0) NOT NULL ENABLE,
	"ACTION_ID" NUMBER(19,0),
	"FILE_NAME" VARCHAR2(300) NOT NULL ENABLE,
	"MIME" VARCHAR2(100) NOT NULL ENABLE,
	"SIZE_BYTES" NUMBER(19,0) NOT NULL ENABLE,
	"STORAGE_KEY" VARCHAR2(500) NOT NULL ENABLE,
	"UPLOADED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"UPLOADED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"SHA256" VARCHAR2(64) NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_REQUEST_CLARIFICATION"
   (	"ID" NUMBER(19,0),
	"REQUEST_ID" NUMBER(19,0) NOT NULL ENABLE,
	"ASKED_BY_EMP" VARCHAR2(20) NOT NULL ENABLE,
	"ASKED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"REPLIED_AT" TIMESTAMP (6) WITH TIME ZONE,
	"QUESTION" VARCHAR2(2000) NOT NULL ENABLE,
	"ANSWER" VARCHAR2(2000),
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_REQUEST_FEEDBACK"
   (	"ID" NUMBER(19,0),
	"REQUEST_ID" NUMBER(19,0) NOT NULL ENABLE,
	"RATING" NUMBER(1,0) NOT NULL ENABLE,
	"COMMENTS" VARCHAR2(2000),
	"GIVEN_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_FEEDBACK_RATING" CHECK (RATING BETWEEN 1 AND 5) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("REQUEST_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_ROLE"
   (	"ID" NUMBER(19,0),
	"CODE" VARCHAR2(30) NOT NULL ENABLE,
	"NAME" VARCHAR2(100) NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 UNIQUE ("CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_SLA_PAUSE_LOG"
   (	"ID" NUMBER(19,0),
	"REQUEST_ID" NUMBER(19,0) NOT NULL ENABLE,
	"PAUSED_AT" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE,
	"RESUMED_AT" TIMESTAMP (6) WITH TIME ZONE,
	"REASON" VARCHAR2(500),
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_UAT_AUTH"
   (	"EMPLOYEE_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"PWD_HASH" VARCHAR2(200) NOT NULL ENABLE,
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	 CONSTRAINT "PK_UAT_AUTH" PRIMARY KEY ("EMPLOYEE_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_UAT_STAFF"
   (	"EMPLOYEE_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"EMPLOYEE_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"UNIT_TYPE" VARCHAR2(10) NOT NULL ENABLE,
	"USER_LEVEL" VARCHAR2(10) NOT NULL ENABLE,
	"UNIT_CODE" VARCHAR2(20),
	"UNIT_NAME" VARCHAR2(100),
	"VERTICAL_CODE" VARCHAR2(20),
	"VERTICAL_NAME" VARCHAR2(100),
	"IS_HEAD" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"DESIGNATION" VARCHAR2(100),
	"EMAIL" VARCHAR2(100),
	"MOBILE" VARCHAR2(15),
	 CONSTRAINT "CK_UAT_UNIT_TYPE" CHECK (UNIT_TYPE  IN ('RO','ZO','CO','ADMIN')) ENABLE,
	 CONSTRAINT "CK_UAT_USER_LEVEL" CHECK (USER_LEVEL IN ('BRANCH','RO','ZO','CO','ADMIN')) ENABLE,
	 CONSTRAINT "CK_UAT_IS_HEAD" CHECK (IS_HEAD    IN (0,1)) ENABLE,
	 CONSTRAINT "PK_UAT_STAFF" PRIMARY KEY ("EMPLOYEE_CODE")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_USER"
   (	"ID" NUMBER NOT NULL ENABLE,
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"AD_SAM" VARCHAR2(50) NOT NULL ENABLE,
	"NAME" VARCHAR2(200) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(200),
	"MOBILE" VARCHAR2(20),
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6),
	 CONSTRAINT "PK_RP_USER" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_RP_USER_EMP" UNIQUE ("EMP_CODE")
  USING INDEX  ENABLE,
	 CONSTRAINT "UQ_RP_USER_SAM" UNIQUE ("AD_SAM")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "RP_OWNER"."RP_USER_ROLE"
   (	"ID" NUMBER(19,0),
	"EMP_CODE" VARCHAR2(20) NOT NULL ENABLE,
	"ROLE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"UNIT_CODE" VARCHAR2(50),
	"VERTICAL_CODE" VARCHAR2(50),
	"VALID_FROM" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"VALID_TO" TIMESTAMP (6) WITH TIME ZONE,
	"GRANTED_BY" VARCHAR2(20) NOT NULL ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "UK_USER_ROLE" UNIQUE ("EMP_CODE", "ROLE_ID")
  USING INDEX  ENABLE
   ) ;

-- ============ NON-CONSTRAINT INDEXES ============

  CREATE INDEX "RP_OWNER"."IDX_EASE_ATR_DIR" ON "RP_OWNER"."EASE_ATR" ("DIRECTION_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_ATT_REF" ON "RP_OWNER"."EASE_ATTACHMENT" ("REF_TYPE", "REF_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_CLARIF_SPOC" ON "RP_OWNER"."EASE_CLARIFICATION" ("RAISED_BY_EMP", "STATUS")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_CLARIF_VASN" ON "RP_OWNER"."EASE_CLARIFICATION" ("ASSIGNMENT_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_DIR_REF" ON "RP_OWNER"."EASE_DIRECTION" ("REF_TYPE", "REF_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_INIT_CAMP" ON "RP_OWNER"."EASE_INITIATIVE" ("CAMPAIGN_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_METRIC_CAMP" ON "RP_OWNER"."EASE_METRIC_MASTER" ("CAMPAIGN_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_RESP_VASN" ON "RP_OWNER"."EASE_METRIC_RESPONSE" ("ASSIGNMENT_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_ROLE_EMP" ON "RP_OWNER"."EASE_ROLE_ASSIGNMENT" ("EMP_CODE", "IS_ACTIVE")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_SEG_RESP" ON "RP_OWNER"."EASE_METRIC_SEGMENT" ("RESPONSE_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_VASN_CAMP" ON "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ("CAMPAIGN_ID")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_VASN_SPOC" ON "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ("SPOC_EMP_CODE", "STATUS")
  ;


  CREATE INDEX "RP_OWNER"."IDX_EASE_VASN_UNIT" ON "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ("UNIT_ID")
  ;


  CREATE INDEX "RP_OWNER"."IX_MD_INAPP_NOTIF_EMP" ON "RP_OWNER"."MD_INAPP_NOTIF" ("EMPL_CODE", "IS_READ", "CREATED_AT")
  ;


  CREATE INDEX "RP_OWNER"."IX_MD_NOTIF_OUTBOX_STATUS" ON "RP_OWNER"."MD_NOTIF_OUTBOX" ("STATUS", "ATTEMPTS")
  ;


  CREATE UNIQUE INDEX "RP_OWNER"."UQ_EASE_PERF" ON "RP_OWNER"."EASE_INITIATIVE_PERF" ("INITIATIVE_METRIC_ID", "FY", "QUARTER", "PERIOD_TYPE")
  ;


  CREATE UNIQUE INDEX "RP_OWNER"."UQ_EASE_VASN" ON "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ("METRIC_ID", "UNIT_ID")
  ;


  CREATE UNIQUE INDEX "RP_OWNER"."UQ_EASE_VI" ON "RP_OWNER"."EASE_VERT_INITIATIVE" ("INITIATIVE_ID", "UNIT_ID")
  ;

-- ============ FOREIGN KEYS ============

  ALTER TABLE "RP_OWNER"."EASE_ATR" ADD CONSTRAINT "FK_EASE_ATR_DIR" FOREIGN KEY ("DIRECTION_ID")
	  REFERENCES "RP_OWNER"."EASE_DIRECTION" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_CLARIFICATION" ADD CONSTRAINT "FK_EASE_CLARIF_VASN" FOREIGN KEY ("ASSIGNMENT_ID")
	  REFERENCES "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_INITIATIVE" ADD CONSTRAINT "FK_EASE_INIT_CAMP" FOREIGN KEY ("CAMPAIGN_ID")
	  REFERENCES "RP_OWNER"."EASE_CAMPAIGN" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_INITIATIVE_METRIC" ADD CONSTRAINT "FK_EASE_INIT_MET_INIT" FOREIGN KEY ("INITIATIVE_ID")
	  REFERENCES "RP_OWNER"."EASE_INITIATIVE" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_INITIATIVE_PERF" ADD CONSTRAINT "FK_EASE_PERF_MET" FOREIGN KEY ("INITIATIVE_METRIC_ID")
	  REFERENCES "RP_OWNER"."EASE_INITIATIVE_METRIC" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_METRIC_MASTER" ADD CONSTRAINT "FK_EASE_METRIC_CAMP" FOREIGN KEY ("CAMPAIGN_ID")
	  REFERENCES "RP_OWNER"."EASE_CAMPAIGN" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_METRIC_RESPONSE" ADD CONSTRAINT "FK_EASE_RESP_VASN" FOREIGN KEY ("ASSIGNMENT_ID")
	  REFERENCES "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_METRIC_SEGMENT" ADD CONSTRAINT "FK_EASE_SEG_RESP" FOREIGN KEY ("RESPONSE_ID")
	  REFERENCES "RP_OWNER"."EASE_METRIC_RESPONSE" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_ROLE_ASSIGNMENT" ADD CONSTRAINT "FK_EASE_ROLE_UNIT" FOREIGN KEY ("UNIT_ID")
	  REFERENCES "RP_OWNER"."RP_M_UNIT" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ADD CONSTRAINT "FK_EASE_VASN_CAMP" FOREIGN KEY ("CAMPAIGN_ID")
	  REFERENCES "RP_OWNER"."EASE_CAMPAIGN" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ADD CONSTRAINT "FK_EASE_VASN_METRIC" FOREIGN KEY ("METRIC_ID")
	  REFERENCES "RP_OWNER"."EASE_METRIC_MASTER" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."EASE_VERTICAL_ASSIGNMENT" ADD CONSTRAINT "FK_EASE_VASN_UNIT" FOREIGN KEY ("UNIT_ID")
	  REFERENCES "RP_OWNER"."RP_M_UNIT" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."EASE_VERT_INITIATIVE" ADD CONSTRAINT "FK_EASE_VI_INIT" FOREIGN KEY ("INITIATIVE_ID")
	  REFERENCES "RP_OWNER"."EASE_INITIATIVE" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."EASE_VERT_INITIATIVE" ADD CONSTRAINT "FK_EASE_VI_UNIT" FOREIGN KEY ("UNIT_ID")
	  REFERENCES "RP_OWNER"."RP_M_UNIT" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."MD_RBAC_MENU" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "RP_OWNER"."MD_RBAC_MODULE" ("ID") ON DELETE CASCADE ENABLE;


  ALTER TABLE "RP_OWNER"."MD_RBAC_MODULE" ADD FOREIGN KEY ("PARENT_ID")
	  REFERENCES "RP_OWNER"."MD_RBAC_MODULE" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."MD_ROLE_MODULE_PERM" ADD FOREIGN KEY ("ROLE_ID")
	  REFERENCES "RP_OWNER"."MD_ROLE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "RP_OWNER"."MD_ROLE_MODULE_PERM" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "RP_OWNER"."MD_RBAC_MODULE" ("ID") ON DELETE CASCADE ENABLE;


  ALTER TABLE "RP_OWNER"."MD_USER_MODULE_PERM" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "RP_OWNER"."MD_RBAC_MODULE" ("ID") ON DELETE CASCADE ENABLE;


  ALTER TABLE "RP_OWNER"."MD_USER_ROLE" ADD FOREIGN KEY ("ROLE_ID")
	  REFERENCES "RP_OWNER"."MD_ROLE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "RP_OWNER"."MD_USER_ROLE" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "RP_OWNER"."MD_USER" ("ID") ON DELETE CASCADE ENABLE;


  ALTER TABLE "RP_OWNER"."RP_M_ACTIVITY" ADD FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "RP_OWNER"."RP_M_DEPARTMENT" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_M_DEPARTMENT" ADD FOREIGN KEY ("VERTICAL_ID")
	  REFERENCES "RP_OWNER"."RP_M_VERTICAL" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_M_HOLIDAY" ADD FOREIGN KEY ("CAL_ID")
	  REFERENCES "RP_OWNER"."RP_M_HOLIDAY_CAL" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_M_ROUTING_ASSIGNEE" ADD FOREIGN KEY ("RULE_ID")
	  REFERENCES "RP_OWNER"."RP_M_ROUTING_RULE" ("ID") ON DELETE CASCADE ENABLE;


  ALTER TABLE "RP_OWNER"."RP_M_ROUTING_RULE" ADD FOREIGN KEY ("REQUEST_TYPE_ID")
	  REFERENCES "RP_OWNER"."RP_M_REQUEST_TYPE" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_M_ROUTING_RULE" ADD FOREIGN KEY ("UNIT_TYPE_ID")
	  REFERENCES "RP_OWNER"."RP_M_UNIT_TYPE" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_M_ROUTING_RULE" ADD FOREIGN KEY ("VERTICAL_ID")
	  REFERENCES "RP_OWNER"."RP_M_VERTICAL" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_M_ROUTING_RULE" ADD FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "RP_OWNER"."RP_M_DEPARTMENT" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_M_ROUTING_RULE" ADD FOREIGN KEY ("ACTIVITY_ID")
	  REFERENCES "RP_OWNER"."RP_M_ACTIVITY" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_M_SLA_CONFIG" ADD FOREIGN KEY ("REQUEST_TYPE_ID")
	  REFERENCES "RP_OWNER"."RP_M_REQUEST_TYPE" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_M_UNIT" ADD FOREIGN KEY ("UNIT_TYPE_ID")
	  REFERENCES "RP_OWNER"."RP_M_UNIT_TYPE" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_M_UNIT" ADD FOREIGN KEY ("PARENT_UNIT_ID")
	  REFERENCES "RP_OWNER"."RP_M_UNIT" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_M_UNIT" ADD FOREIGN KEY ("HOLIDAY_CAL_ID")
	  REFERENCES "RP_OWNER"."RP_M_HOLIDAY_CAL" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_RBAC_MENU" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "RP_OWNER"."RP_RBAC_MODULE" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_RBAC_MODULE" ADD FOREIGN KEY ("PARENT_ID")
	  REFERENCES "RP_OWNER"."RP_RBAC_MODULE" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_RBAC_ROLE_PERM" ADD FOREIGN KEY ("ROLE_ID")
	  REFERENCES "RP_OWNER"."RP_ROLE" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_RBAC_ROLE_PERM" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "RP_OWNER"."RP_RBAC_MODULE" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_RBAC_USER_PERM" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "RP_OWNER"."RP_RBAC_MODULE" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_RBAC_VERTICAL_ADMIN" ADD FOREIGN KEY ("VERTICAL_ID")
	  REFERENCES "RP_OWNER"."RP_M_VERTICAL" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_RBAC_VERTICAL_LEVEL" ADD FOREIGN KEY ("VERTICAL_ID")
	  REFERENCES "RP_OWNER"."RP_M_VERTICAL" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_REQUEST" ADD FOREIGN KEY ("REQUEST_TYPE_ID")
	  REFERENCES "RP_OWNER"."RP_M_REQUEST_TYPE" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_REQUEST" ADD FOREIGN KEY ("UNIT_ID")
	  REFERENCES "RP_OWNER"."RP_M_UNIT" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_REQUEST" ADD FOREIGN KEY ("VERTICAL_ID")
	  REFERENCES "RP_OWNER"."RP_M_VERTICAL" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_REQUEST" ADD FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "RP_OWNER"."RP_M_DEPARTMENT" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_REQUEST" ADD FOREIGN KEY ("ACTIVITY_ID")
	  REFERENCES "RP_OWNER"."RP_M_ACTIVITY" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_REQUEST_ACTION" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_OWNER"."RP_REQUEST" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_REQUEST_ASSIGNEE" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_OWNER"."RP_REQUEST" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_REQUEST_ATTACHMENT" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_OWNER"."RP_REQUEST" ("ID") ENABLE;
  ALTER TABLE "RP_OWNER"."RP_REQUEST_ATTACHMENT" ADD FOREIGN KEY ("ACTION_ID")
	  REFERENCES "RP_OWNER"."RP_REQUEST_ACTION" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_REQUEST_CLARIFICATION" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_OWNER"."RP_REQUEST" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_REQUEST_FEEDBACK" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_OWNER"."RP_REQUEST" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_SLA_PAUSE_LOG" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_OWNER"."RP_REQUEST" ("ID") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_UAT_AUTH" ADD CONSTRAINT "FK_UAT_AUTH_STAFF" FOREIGN KEY ("EMPLOYEE_CODE")
	  REFERENCES "RP_OWNER"."RP_UAT_STAFF" ("EMPLOYEE_CODE") ENABLE;


  ALTER TABLE "RP_OWNER"."RP_USER_ROLE" ADD FOREIGN KEY ("ROLE_ID")
	  REFERENCES "RP_OWNER"."RP_ROLE" ("ID") ENABLE;

-- ============ VIEWS ============

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "RP_OWNER"."VW_STAFF_USER_SUMMARY" ("EMPLOYEE_CODE", "EMPLOYEE_NAME", "UNIT_TYPE", "USER_LEVEL", "UNIT_CODE", "UNIT_NAME", "VERTICAL_CODE", "VERTICAL_NAME", "IS_HEAD", "DESIGNATION", "EMAIL", "MOBILE") AS
  SELECT
  EMPLOYEE_CODE,
  EMPLOYEE_NAME,
  UNIT_TYPE,
  USER_LEVEL,
  UNIT_CODE,
  UNIT_NAME,
  VERTICAL_CODE,
  VERTICAL_NAME,
  IS_HEAD,
  DESIGNATION,
  EMAIL,
  MOBILE
FROM RP_UAT_STAFF;

