-- ============================================================
-- Classification interlink mappings (Request Portal)
--   RequestType  -> UnitType   (RP_M_REQTYPE_UNITTYPE)
--   Unit         -> Vertical   (RP_M_UNIT_VERTICAL)
-- (UnitType->Unit, Vertical->Department, Department->Activity already exist as FKs)
-- Target: rp-oracle / XEPDB1 / RP_OWNER
-- ============================================================
SET SQLBLANKLINES ON

-- ---------- Request Type  ->  Unit Type ----------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RP_M_REQTYPE_UNITTYPE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE RP_M_REQTYPE_UNITTYPE (
    ID              NUMBER(19) NOT NULL,
    REQUEST_TYPE_ID NUMBER(19) NOT NULL,
    UNIT_TYPE_ID    NUMBER(19) NOT NULL,
    CONSTRAINT PK_RP_RT_UT PRIMARY KEY (ID),
    CONSTRAINT UQ_RP_RT_UT UNIQUE (REQUEST_TYPE_ID, UNIT_TYPE_ID),
    CONSTRAINT FK_RP_RT_UT_RT FOREIGN KEY (REQUEST_TYPE_ID) REFERENCES RP_M_REQUEST_TYPE(ID),
    CONSTRAINT FK_RP_RT_UT_UT FOREIGN KEY (UNIT_TYPE_ID)    REFERENCES RP_M_UNIT_TYPE(ID)
);

-- ---------- Unit  ->  Vertical ----------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RP_M_UNIT_VERTICAL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE RP_M_UNIT_VERTICAL (
    ID          NUMBER(19) NOT NULL,
    UNIT_ID     NUMBER(19) NOT NULL,
    VERTICAL_ID NUMBER(19) NOT NULL,
    CONSTRAINT PK_RP_U_V PRIMARY KEY (ID),
    CONSTRAINT UQ_RP_U_V UNIQUE (UNIT_ID, VERTICAL_ID),
    CONSTRAINT FK_RP_U_V_U FOREIGN KEY (UNIT_ID)     REFERENCES RP_M_UNIT(ID),
    CONSTRAINT FK_RP_U_V_V FOREIGN KEY (VERTICAL_ID) REFERENCES RP_M_VERTICAL(ID)
);

-- one sequence shared by both mapping tables
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE RP_MAP_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE RP_MAP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- ---------- Seed: Request Type -> Unit Types ----------
-- Request(1016) -> all unit types
INSERT INTO RP_M_REQTYPE_UNITTYPE (ID,REQUEST_TYPE_ID,UNIT_TYPE_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1016,1019);
INSERT INTO RP_M_REQTYPE_UNITTYPE (ID,REQUEST_TYPE_ID,UNIT_TYPE_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1016,1020);
INSERT INTO RP_M_REQTYPE_UNITTYPE (ID,REQUEST_TYPE_ID,UNIT_TYPE_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1016,1021);
INSERT INTO RP_M_REQTYPE_UNITTYPE (ID,REQUEST_TYPE_ID,UNIT_TYPE_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1016,1022);
INSERT INTO RP_M_REQTYPE_UNITTYPE (ID,REQUEST_TYPE_ID,UNIT_TYPE_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1016,1023);
-- Grievance(1017) -> RO, CO, ZO, Branch
INSERT INTO RP_M_REQTYPE_UNITTYPE (ID,REQUEST_TYPE_ID,UNIT_TYPE_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1017,1020);
INSERT INTO RP_M_REQTYPE_UNITTYPE (ID,REQUEST_TYPE_ID,UNIT_TYPE_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1017,1021);
INSERT INTO RP_M_REQTYPE_UNITTYPE (ID,REQUEST_TYPE_ID,UNIT_TYPE_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1017,1022);
INSERT INTO RP_M_REQTYPE_UNITTYPE (ID,REQUEST_TYPE_ID,UNIT_TYPE_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1017,1023);
-- Inquiry(1018) -> Administration, Branch
INSERT INTO RP_M_REQTYPE_UNITTYPE (ID,REQUEST_TYPE_ID,UNIT_TYPE_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1018,1019);
INSERT INTO RP_M_REQTYPE_UNITTYPE (ID,REQUEST_TYPE_ID,UNIT_TYPE_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1018,1023);

-- ---------- Seed: Unit -> Verticals ----------
-- Corporate Office Head(1424) -> all verticals
INSERT INTO RP_M_UNIT_VERTICAL (ID,UNIT_ID,VERTICAL_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1424,1420);
INSERT INTO RP_M_UNIT_VERTICAL (ID,UNIT_ID,VERTICAL_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1424,1421);
INSERT INTO RP_M_UNIT_VERTICAL (ID,UNIT_ID,VERTICAL_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1424,1422);
INSERT INTO RP_M_UNIT_VERTICAL (ID,UNIT_ID,VERTICAL_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1424,1423);
-- Administration - Head Office(1425) -> Retail, MSME
INSERT INTO RP_M_UNIT_VERTICAL (ID,UNIT_ID,VERTICAL_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1425,1420);
INSERT INTO RP_M_UNIT_VERTICAL (ID,UNIT_ID,VERTICAL_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1425,1422);
-- Northern Zonal Office(1426) -> all
INSERT INTO RP_M_UNIT_VERTICAL (ID,UNIT_ID,VERTICAL_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1426,1420);
INSERT INTO RP_M_UNIT_VERTICAL (ID,UNIT_ID,VERTICAL_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1426,1421);
INSERT INTO RP_M_UNIT_VERTICAL (ID,UNIT_ID,VERTICAL_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1426,1422);
INSERT INTO RP_M_UNIT_VERTICAL (ID,UNIT_ID,VERTICAL_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1426,1423);
-- Delhi Regional Office(1427) -> Retail, MSME, Agriculture
INSERT INTO RP_M_UNIT_VERTICAL (ID,UNIT_ID,VERTICAL_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1427,1420);
INSERT INTO RP_M_UNIT_VERTICAL (ID,UNIT_ID,VERTICAL_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1427,1422);
INSERT INTO RP_M_UNIT_VERTICAL (ID,UNIT_ID,VERTICAL_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1427,1423);
-- Delhi Main Branch(1428) -> all verticals
INSERT INTO RP_M_UNIT_VERTICAL (ID,UNIT_ID,VERTICAL_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1428,1420);
INSERT INTO RP_M_UNIT_VERTICAL (ID,UNIT_ID,VERTICAL_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1428,1421);
INSERT INTO RP_M_UNIT_VERTICAL (ID,UNIT_ID,VERTICAL_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1428,1422);
INSERT INTO RP_M_UNIT_VERTICAL (ID,UNIT_ID,VERTICAL_ID) VALUES (RP_MAP_SEQ.NEXTVAL,1428,1423);

-- ---------- Backfill existing escalation rows so download shows Request Type / Unit Type / Unit ----------
-- KYC Update(1430) & Crop Loan Processing(1488) -> Request(1016), Delhi Main Branch(1428)
UPDATE RP_ESCALATION_MATRIX SET REQUEST_TYPE_ID = 1016, UNIT_ID = 1428
 WHERE ACTIVITY_ID IN (1430, 1488);

COMMIT;
