-- ============================================================
-- Escalation Matrix feature — Request Portal
-- Objects: RP_M_EMPLOYEE (sample "employee view"), RP_ESCALATION_MATRIX
-- Target: rp-oracle / XEPDB1 / RP_OWNER
-- ============================================================
SET SQLBLANKLINES ON

-- ---------- Sample Employee View (production: replace with HRMS view keyed by PF) ----------
-- Scale, Role, Email, Mobile are sourced from here by PF number.
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RP_M_EMPLOYEE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE TABLE RP_M_EMPLOYEE (
    PF_NUMBER   VARCHAR2(20)  NOT NULL,
    EMP_NAME    VARCHAR2(150) NOT NULL,
    SCALE       VARCHAR2(20),
    EMP_ROLE    VARCHAR2(80),
    EMAIL       VARCHAR2(150),
    MOBILE      VARCHAR2(20),
    IS_ACTIVE   NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_RP_M_EMPLOYEE PRIMARY KEY (PF_NUMBER)
);

INSERT INTO RP_M_EMPLOYEE (PF_NUMBER,EMP_NAME,SCALE,EMP_ROLE,EMAIL,MOBILE) VALUES ('10001','Anita Sharma','JMGS-I','Officer','anita.sharma@bank.co.in','9810000001');
INSERT INTO RP_M_EMPLOYEE (PF_NUMBER,EMP_NAME,SCALE,EMP_ROLE,EMAIL,MOBILE) VALUES ('10002','Rakesh Verma','MMGS-II','Manager','rakesh.verma@bank.co.in','9810000002');
INSERT INTO RP_M_EMPLOYEE (PF_NUMBER,EMP_NAME,SCALE,EMP_ROLE,EMAIL,MOBILE) VALUES ('10003','Priya Nair','MMGS-III','Senior Manager','priya.nair@bank.co.in','9810000003');
INSERT INTO RP_M_EMPLOYEE (PF_NUMBER,EMP_NAME,SCALE,EMP_ROLE,EMAIL,MOBILE) VALUES ('10004','Sudhir Rao','SMGS-IV','Chief Manager','sudhir.rao@bank.co.in','9810000004');
INSERT INTO RP_M_EMPLOYEE (PF_NUMBER,EMP_NAME,SCALE,EMP_ROLE,EMAIL,MOBILE) VALUES ('10005','Meena Iyer','SMGS-V','Asst. General Manager','meena.iyer@bank.co.in','9810000005');
INSERT INTO RP_M_EMPLOYEE (PF_NUMBER,EMP_NAME,SCALE,EMP_ROLE,EMAIL,MOBILE) VALUES ('10006','Vikram Singh','JMGS-I','Officer','vikram.singh@bank.co.in','9810000006');
INSERT INTO RP_M_EMPLOYEE (PF_NUMBER,EMP_NAME,SCALE,EMP_ROLE,EMAIL,MOBILE) VALUES ('10007','Deepa Menon','MMGS-II','Manager','deepa.menon@bank.co.in','9810000007');
INSERT INTO RP_M_EMPLOYEE (PF_NUMBER,EMP_NAME,SCALE,EMP_ROLE,EMAIL,MOBILE) VALUES ('10008','Arun Kumar','MMGS-III','Senior Manager','arun.kumar@bank.co.in','9810000008');
INSERT INTO RP_M_EMPLOYEE (PF_NUMBER,EMP_NAME,SCALE,EMP_ROLE,EMAIL,MOBILE) VALUES ('10009','Neha Gupta','SMGS-IV','Chief Manager','neha.gupta@bank.co.in','9810000009');
INSERT INTO RP_M_EMPLOYEE (PF_NUMBER,EMP_NAME,SCALE,EMP_ROLE,EMAIL,MOBILE) VALUES ('10010','Ramesh Pillai','SMGS-V','Deputy General Manager','ramesh.pillai@bank.co.in','9810000010');
INSERT INTO RP_M_EMPLOYEE (PF_NUMBER,EMP_NAME,SCALE,EMP_ROLE,EMAIL,MOBILE) VALUES ('10011','Kavita Desai','MMGS-II','Manager','kavita.desai@bank.co.in','9810000011');
INSERT INTO RP_M_EMPLOYEE (PF_NUMBER,EMP_NAME,SCALE,EMP_ROLE,EMAIL,MOBILE) VALUES ('10012','Sanjay Joshi','MMGS-III','Senior Manager','sanjay.joshi@bank.co.in','9810000012');
INSERT INTO RP_M_EMPLOYEE (PF_NUMBER,EMP_NAME,SCALE,EMP_ROLE,EMAIL,MOBILE) VALUES ('860921','Super Admin','TEGS-VI','General Manager','super.admin@bank.co.in','9810000000');

-- ---------- Escalation Matrix ----------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RP_ESCALATION_MATRIX CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE RP_ESCALATION_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE RP_ESCALATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE RP_ESCALATION_MATRIX (
    ID            NUMBER(19)   NOT NULL,
    ACTIVITY_ID   NUMBER(19)   NOT NULL,
    UNIT_ID       NUMBER(19),
    LEVEL_NO      NUMBER(2)    NOT NULL,
    PF_NUMBER     VARCHAR2(20) NOT NULL,
    IP_NUMBER     VARCHAR2(50),
    GENERIC_MAIL  VARCHAR2(150),
    IS_ACTIVE     NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_BY    VARCHAR2(50),
    CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_BY    VARCHAR2(50),
    UPDATED_AT    TIMESTAMP,
    CONSTRAINT PK_RP_ESC_MATRIX PRIMARY KEY (ID),
    CONSTRAINT CK_RP_ESC_LEVEL CHECK (LEVEL_NO BETWEEN 1 AND 5),
    CONSTRAINT FK_RP_ESC_ACTIVITY FOREIGN KEY (ACTIVITY_ID) REFERENCES RP_M_ACTIVITY(ID)
);
CREATE INDEX IX_RP_ESC_ACTIVITY ON RP_ESCALATION_MATRIX (ACTIVITY_ID, UNIT_ID, LEVEL_NO);

-- ---------- Sample matrix: KYC Update (activity 1430) L1-L5 ----------
INSERT INTO RP_ESCALATION_MATRIX (ID,ACTIVITY_ID,UNIT_ID,LEVEL_NO,PF_NUMBER,IP_NUMBER,GENERIC_MAIL,CREATED_BY)
  VALUES (RP_ESCALATION_SEQ.NEXTVAL,1430,NULL,1,'10001','10.20.1.11','kyc.l1@bank.co.in','BOOT_SEED');
INSERT INTO RP_ESCALATION_MATRIX (ID,ACTIVITY_ID,UNIT_ID,LEVEL_NO,PF_NUMBER,IP_NUMBER,GENERIC_MAIL,CREATED_BY)
  VALUES (RP_ESCALATION_SEQ.NEXTVAL,1430,NULL,2,'10002','10.20.1.12','kyc.l2@bank.co.in','BOOT_SEED');
INSERT INTO RP_ESCALATION_MATRIX (ID,ACTIVITY_ID,UNIT_ID,LEVEL_NO,PF_NUMBER,IP_NUMBER,GENERIC_MAIL,CREATED_BY)
  VALUES (RP_ESCALATION_SEQ.NEXTVAL,1430,NULL,3,'10003','10.20.1.13','kyc.l3@bank.co.in','BOOT_SEED');
INSERT INTO RP_ESCALATION_MATRIX (ID,ACTIVITY_ID,UNIT_ID,LEVEL_NO,PF_NUMBER,IP_NUMBER,GENERIC_MAIL,CREATED_BY)
  VALUES (RP_ESCALATION_SEQ.NEXTVAL,1430,NULL,4,'10004','10.20.1.14','kyc.l4@bank.co.in','BOOT_SEED');
INSERT INTO RP_ESCALATION_MATRIX (ID,ACTIVITY_ID,UNIT_ID,LEVEL_NO,PF_NUMBER,IP_NUMBER,GENERIC_MAIL,CREATED_BY)
  VALUES (RP_ESCALATION_SEQ.NEXTVAL,1430,NULL,5,'10005','10.20.1.15','kyc.l5@bank.co.in','BOOT_SEED');

-- ---------- Sample matrix: Crop Loan Processing (activity 1488) L1-L5 ----------
INSERT INTO RP_ESCALATION_MATRIX (ID,ACTIVITY_ID,UNIT_ID,LEVEL_NO,PF_NUMBER,IP_NUMBER,GENERIC_MAIL,CREATED_BY)
  VALUES (RP_ESCALATION_SEQ.NEXTVAL,1488,NULL,1,'10006','10.30.2.11','crop.l1@bank.co.in','BOOT_SEED');
INSERT INTO RP_ESCALATION_MATRIX (ID,ACTIVITY_ID,UNIT_ID,LEVEL_NO,PF_NUMBER,IP_NUMBER,GENERIC_MAIL,CREATED_BY)
  VALUES (RP_ESCALATION_SEQ.NEXTVAL,1488,NULL,2,'10007','10.30.2.12','crop.l2@bank.co.in','BOOT_SEED');
INSERT INTO RP_ESCALATION_MATRIX (ID,ACTIVITY_ID,UNIT_ID,LEVEL_NO,PF_NUMBER,IP_NUMBER,GENERIC_MAIL,CREATED_BY)
  VALUES (RP_ESCALATION_SEQ.NEXTVAL,1488,NULL,3,'10008','10.30.2.13','crop.l3@bank.co.in','BOOT_SEED');
INSERT INTO RP_ESCALATION_MATRIX (ID,ACTIVITY_ID,UNIT_ID,LEVEL_NO,PF_NUMBER,IP_NUMBER,GENERIC_MAIL,CREATED_BY)
  VALUES (RP_ESCALATION_SEQ.NEXTVAL,1488,NULL,4,'10009','10.30.2.14','crop.l4@bank.co.in','BOOT_SEED');
INSERT INTO RP_ESCALATION_MATRIX (ID,ACTIVITY_ID,UNIT_ID,LEVEL_NO,PF_NUMBER,IP_NUMBER,GENERIC_MAIL,CREATED_BY)
  VALUES (RP_ESCALATION_SEQ.NEXTVAL,1488,NULL,5,'10010','10.30.2.15','crop.l5@bank.co.in','BOOT_SEED');

COMMIT;
