-- ============================================================================
-- RP_25_report_dr_and_audit.sql — Report Module: DC/DR source pairs + audit/access logs
--
-- 1) RP_M_REPORT_DEF gets a mirrored DR_* column for every connection detail
--    (the existing columns become the DC side) plus RUNNING_FROM ('DC'/'DR')
--    telling the execution engine which site to read from. SQL_QUERY and
--    FILE_TYPE are shared across DC/DR (same logical report, same shape).
-- 2) RP_REPORT_AUDIT_LOG — who created/edited/deleted/enabled/disabled a
--    report definition, and when.
-- 3) RP_REPORT_ACCESS_LOG — who loaded a report (or hit a disabled/failed
--    report), when, from which site, and how many rows came back.
--
-- Idempotent: guarded ALTER/CREATE (ORA-01430/ORA-00955 already-exists ignored).
-- ============================================================================
SET SERVEROUTPUT ON

DECLARE
  PROCEDURE ddl(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-1430, -955, -1442, -2261) THEN RAISE; END IF;
  END;
BEGIN
  -- ── DR mirror columns on RP_M_REPORT_DEF ─────────────────────────────────
  ddl('ALTER TABLE RP_M_REPORT_DEF ADD RUNNING_FROM VARCHAR2(2) DEFAULT ''DC'' NOT NULL');
  ddl('ALTER TABLE RP_M_REPORT_DEF ADD CONSTRAINT CK_RP_REPORT_RUNFROM CHECK (RUNNING_FROM IN (''DC'',''DR''))');

  ddl('ALTER TABLE RP_M_REPORT_DEF ADD FILE_PATH_DR      VARCHAR2(1000)');
  ddl('ALTER TABLE RP_M_REPORT_DEF ADD SFTP_HOST_DR      VARCHAR2(200)');
  ddl('ALTER TABLE RP_M_REPORT_DEF ADD SFTP_PORT_DR      NUMBER');
  ddl('ALTER TABLE RP_M_REPORT_DEF ADD SFTP_USER_DR      VARCHAR2(100)');
  ddl('ALTER TABLE RP_M_REPORT_DEF ADD SFTP_PASSWORD_DR  VARCHAR2(500)');
  ddl('ALTER TABLE RP_M_REPORT_DEF ADD DB_CONN_STRING_DR VARCHAR2(1000)');

  -- ── Audit log: who created/edited/deleted/enabled/disabled a definition ──
  ddl(q'[
    CREATE TABLE RP_REPORT_AUDIT_LOG (
      ID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      REPORT_ID   NUMBER NOT NULL,
      REPORT_NAME VARCHAR2(200) NOT NULL,
      ACTION      VARCHAR2(20) NOT NULL,
      ACTOR_EMP   VARCHAR2(20) NOT NULL,
      ACTOR_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      DETAILS     VARCHAR2(2000),
      CONSTRAINT PK_RP_REPORT_AUDIT PRIMARY KEY (ID),
      CONSTRAINT CK_RP_REPORT_AUDIT_ACT CHECK (ACTION IN ('CREATE','UPDATE','DELETE','ENABLE','DISABLE'))
    )]');
  ddl('CREATE INDEX IX_RP_REPORT_AUDIT_RID ON RP_REPORT_AUDIT_LOG (REPORT_ID, ACTOR_AT DESC)');

  -- ── Access log: who loaded (or attempted to load) a report ───────────────
  ddl(q'[
    CREATE TABLE RP_REPORT_ACCESS_LOG (
      ID            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      REPORT_ID     NUMBER NOT NULL,
      REPORT_NAME   VARCHAR2(200) NOT NULL,
      ACCESSED_BY   VARCHAR2(20) NOT NULL,
      ACCESSED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      RUNNING_FROM  VARCHAR2(2),
      ROWS_RETURNED NUMBER,
      SUCCESS       NUMBER(1) NOT NULL,
      ERROR_MSG     VARCHAR2(2000),
      CONSTRAINT PK_RP_REPORT_ACCESS PRIMARY KEY (ID)
    )]');
  ddl('CREATE INDEX IX_RP_REPORT_ACCESS_RID ON RP_REPORT_ACCESS_LOG (REPORT_ID, ACCESSED_AT DESC)');
END;
/

PROMPT === RP_25 DC/DR + audit/access log objects applied. Verify: ===
SELECT table_name FROM user_tables WHERE table_name IN ('RP_REPORT_AUDIT_LOG','RP_REPORT_ACCESS_LOG') ORDER BY table_name;
SELECT column_name FROM user_tab_columns WHERE table_name = 'RP_M_REPORT_DEF' AND column_name LIKE '%DR%' ORDER BY column_name;
