-- ============================================================================
-- RP_22_unionhub_tables.sql — Union Hub (Corporate Events feed) table structures
--
-- Provisions the EV_* tables read/written by RequestPortal.Data.Repositories.
-- EventFeedRepo, plus the RP_RBAC_VERTICAL_ADMIN mapping used to scope which
-- verticals an employee may post to. Menu/RBAC seed is in RP_19_unionhub_menu.sql.
--
-- Idempotent: each CREATE is guarded (ORA-00955 = name already used is ignored),
-- so re-running is safe. Run as RP_OWNER (or the target application schema owner).
-- Depends on RP_M_VERTICAL (created by PROD_FULL_MIGRATION.sql).
-- ============================================================================
SET SERVEROUTPUT ON
SET SQLBLANKLINES ON

DECLARE
  PROCEDURE ddl(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -955 THEN RAISE; END IF;  -- -955 = object already exists
  END;
BEGIN
  -- ── Tags ──────────────────────────────────────────────────────────────────
  ddl(q'[
    CREATE TABLE EV_TAG (
      ID             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      NAME           VARCHAR2(100) NOT NULL,
      IS_ENABLED     NUMBER(1) DEFAULT 1 NOT NULL,
      CREATED_BY_EMP VARCHAR2(20),
      CREATED_AT     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_EV_TAG PRIMARY KEY (ID),
      CONSTRAINT UQ_EV_TAG_NAME UNIQUE (NAME)
    )]');

  -- ── Events ────────────────────────────────────────────────────────────────
  ddl(q'[
    CREATE TABLE EV_EVENT (
      ID             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      VERTICAL_ID    NUMBER NOT NULL,
      NAME           VARCHAR2(300) NOT NULL,
      EVENT_DATE     DATE,
      TIME_TEXT      VARCHAR2(100),
      VENUE          VARCHAR2(300),
      POSTED_BY_EMP  VARCHAR2(20) NOT NULL,
      POSTED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      IS_ACTIVE      NUMBER(1) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_EV_EVENT PRIMARY KEY (ID),
      CONSTRAINT FK_EV_EVENT_VERT FOREIGN KEY (VERTICAL_ID) REFERENCES RP_M_VERTICAL (ID)
    )]');

  -- ── Posts ─────────────────────────────────────────────────────────────────
  ddl(q'[
    CREATE TABLE EV_POST (
      ID             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      VERTICAL_ID    NUMBER NOT NULL,
      EVENT_ID       NUMBER,
      TAG_ID         NUMBER,
      CAPTION        CLOB,
      POSTED_BY_EMP  VARCHAR2(20) NOT NULL,
      POSTED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      IS_ARCHIVED    NUMBER(1) DEFAULT 0 NOT NULL,
      ARCHIVED_AT    TIMESTAMP(6),
      CONSTRAINT PK_EV_POST PRIMARY KEY (ID),
      CONSTRAINT FK_EV_POST_VERT  FOREIGN KEY (VERTICAL_ID) REFERENCES RP_M_VERTICAL (ID),
      CONSTRAINT FK_EV_POST_EVENT FOREIGN KEY (EVENT_ID)    REFERENCES EV_EVENT (ID),
      CONSTRAINT FK_EV_POST_TAG   FOREIGN KEY (TAG_ID)      REFERENCES EV_TAG (ID)
    )]');

  -- ── Post images ───────────────────────────────────────────────────────────
  ddl(q'[
    CREATE TABLE EV_POST_IMAGE (
      ID            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      POST_ID       NUMBER NOT NULL,
      FILE_PATH     VARCHAR2(1000) NOT NULL,
      FILE_NAME     VARCHAR2(500) NOT NULL,
      CONTENT_TYPE  VARCHAR2(150),
      FILE_SIZE     NUMBER,
      SEQ_NO        NUMBER DEFAULT 0 NOT NULL,
      IS_ARCHIVED   NUMBER(1) DEFAULT 0 NOT NULL,
      CONSTRAINT PK_EV_POST_IMAGE PRIMARY KEY (ID),
      CONSTRAINT FK_EV_IMG_POST FOREIGN KEY (POST_ID) REFERENCES EV_POST (ID)
    )]');

  -- ── Activity log ──────────────────────────────────────────────────────────
  ddl(q'[
    CREATE TABLE EV_ACTIVITY_LOG (
      ID           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      ACTIVITY     VARCHAR2(100) NOT NULL,
      ENTITY_TYPE  VARCHAR2(50),
      ENTITY_ID    NUMBER,
      ACTOR_EMP    VARCHAR2(20),
      VERTICAL_ID  NUMBER,
      DETAILS      VARCHAR2(2000),
      CREATED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_EV_ACTIVITY_LOG PRIMARY KEY (ID)
    )]');

  -- ── Vertical admin mapping (who may post to which vertical) ────────────────
  ddl(q'[
    CREATE TABLE RP_RBAC_VERTICAL_ADMIN (
      ID           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      EMP_CODE     VARCHAR2(20) NOT NULL,
      VERTICAL_ID  NUMBER NOT NULL,
      IS_ACTIVE    NUMBER(1) DEFAULT 1 NOT NULL,
      CREATED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_RP_RBAC_VERT_ADMIN PRIMARY KEY (ID),
      CONSTRAINT UQ_RP_RBAC_VERT_ADMIN UNIQUE (EMP_CODE, VERTICAL_ID),
      CONSTRAINT FK_RP_RBAC_VERT FOREIGN KEY (VERTICAL_ID) REFERENCES RP_M_VERTICAL (ID)
    )]');

  -- ── Indexes for feed queries ──────────────────────────────────────────────
  ddl('CREATE INDEX IX_EV_POST_FEED  ON EV_POST (IS_ARCHIVED, POSTED_AT DESC)');
  ddl('CREATE INDEX IX_EV_POST_VERT  ON EV_POST (VERTICAL_ID)');
  ddl('CREATE INDEX IX_EV_IMG_POST   ON EV_POST_IMAGE (POST_ID)');
  ddl('CREATE INDEX IX_EV_EVENT_VERT ON EV_EVENT (VERTICAL_ID, IS_ACTIVE)');
END;
/

PROMPT === RP_22 Union Hub tables applied. Verify: ===
SELECT table_name FROM user_tables
 WHERE table_name IN ('EV_TAG','EV_EVENT','EV_POST','EV_POST_IMAGE','EV_ACTIVITY_LOG','RP_RBAC_VERTICAL_ADMIN')
 ORDER BY table_name;
