-- ============================================================================
-- RP_24_report_module.sql — Report Module: report definitions master
--
-- RP_M_REPORT_DEF holds admin-authored report definitions. Report Developer
-- (SuperAdmin) creates rows here; Reports (all users) filters by Vertical /
-- Department / Report Name and loads the report on demand.
--
-- SOURCE_TYPE: FILE_PATH | SFTP | ORACLE_DB | SQLSERVER_DB
--   FILE_PATH / SFTP  → FILE_TYPE (XLSX/CSV) + FILE_PATH (+ SFTP_* for SFTP)
--   ORACLE_DB / SQLSERVER_DB → DB_CONN_STRING + SQL_QUERY
--
-- SFTP_PASSWORD / DB_CONN_STRING are stored as entered by the SuperAdmin.
-- Treat this table as sensitive (admin-only DML) — for a hardened production
-- rollout, encrypt these two columns the same way ConnectionStringDecryptor
-- encrypts appsettings connection strings, and decrypt only inside
-- ReportExecutionService.
--
-- Idempotent: guarded CREATE (ORA-00955 = already exists is ignored).
-- ============================================================================
SET SERVEROUTPUT ON

DECLARE
  PROCEDURE ddl(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -955 THEN RAISE; END IF;
  END;
BEGIN
  ddl(q'[
    CREATE TABLE RP_M_REPORT_DEF (
      ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      REPORT_NAME     VARCHAR2(200) NOT NULL,
      VERTICAL_ID     NUMBER NOT NULL,
      DEPARTMENT_ID   NUMBER NOT NULL,
      SOURCE_TYPE     VARCHAR2(20) NOT NULL,
      FILE_TYPE       VARCHAR2(10),
      FILE_PATH       VARCHAR2(1000),
      SFTP_HOST       VARCHAR2(200),
      SFTP_PORT       NUMBER,
      SFTP_USER       VARCHAR2(100),
      SFTP_PASSWORD   VARCHAR2(500),
      DB_CONN_STRING  VARCHAR2(1000),
      SQL_QUERY       CLOB,
      IS_ACTIVE       NUMBER(1) DEFAULT 1 NOT NULL,
      CREATED_BY_EMP  VARCHAR2(20) NOT NULL,
      CREATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT      TIMESTAMP(6),
      CONSTRAINT PK_RP_M_REPORT_DEF PRIMARY KEY (ID),
      CONSTRAINT CK_RP_REPORT_SRC CHECK (SOURCE_TYPE IN ('FILE_PATH','SFTP','ORACLE_DB','SQLSERVER_DB')),
      CONSTRAINT FK_RP_REPORT_VERT FOREIGN KEY (VERTICAL_ID)   REFERENCES RP_M_VERTICAL (ID),
      CONSTRAINT FK_RP_REPORT_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES RP_M_DEPARTMENT (ID)
    )]');

  ddl('CREATE INDEX IX_RP_REPORT_DEF_FILT ON RP_M_REPORT_DEF (VERTICAL_ID, DEPARTMENT_ID, IS_ACTIVE)');
END;
/

PROMPT === RP_24 Report Module table applied. Verify: ===
SELECT table_name FROM user_tables WHERE table_name = 'RP_M_REPORT_DEF';
