-- RP_32_report_filters.sql
-- Report Developer: admin-defined filters (Zone/Region/Branch/Custom) exposed
-- on a report's viewing page (Reports.razor). Each row names a query-result
-- column the filter binds to and a display label. COLUMN_NAME is admin-entered
-- free text (validated as a plain identifier by the app before use in SQL,
-- since column names can't be bind-parameterized).
-- Idempotent: guarded CREATE (ORA-00955 = already exists is ignored).

DECLARE
  PROCEDURE ddl(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -955 THEN RAISE; END IF;
  END;
BEGIN
  ddl(q'[
    CREATE TABLE RP_M_REPORT_FILTER (
      ID           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      REPORT_ID    NUMBER NOT NULL,
      FILTER_TYPE  VARCHAR2(20) NOT NULL,
      COLUMN_NAME  VARCHAR2(100) NOT NULL,
      LABEL        VARCHAR2(100) NOT NULL,
      SORT_ORDER   NUMBER DEFAULT 0 NOT NULL,
      IS_ACTIVE    NUMBER(1) DEFAULT 1 NOT NULL,
      CONSTRAINT PK_RP_REPORT_FILTER PRIMARY KEY (ID),
      CONSTRAINT CK_RP_REPORT_FILTER_TYPE CHECK (FILTER_TYPE IN ('ZONE','REGION','BRANCH','CUSTOM')),
      CONSTRAINT FK_RP_REPORT_FILTER_DEF FOREIGN KEY (REPORT_ID) REFERENCES RP_M_REPORT_DEF (ID) ON DELETE CASCADE
    )]');

  ddl('CREATE INDEX IX_RP_REPORT_FILTER_RPT ON RP_M_REPORT_FILTER (REPORT_ID)');
END;
/
