-- ===================== SEQUENCES =====================

   CREATE SEQUENCE  "HF_JOB_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1461 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "HF_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21961 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "MD_SEQ_GLOBAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1229 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "RP_ESCALATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "RP_MAP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 31 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "RP_SEQ_GLOBAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10355 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


   CREATE SEQUENCE  "RP_SEQ_REQUEST"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 50 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

-- ===================== TABLES (columns only, no out-of-line constraints) =====================

  CREATE TABLE "EASE_P1_ENTRY" 
   (	"ID" NUMBER DEFAULT "RP_SEQ_GLOBAL"."NEXTVAL", 
	"METRIC_ID" NUMBER, 
	"FY" NUMBER(4,0), 
	"RESP_APR" VARCHAR2(4000), 
	"RESP_MAY" VARCHAR2(4000), 
	"RESP_JUN" VARCHAR2(4000), 
	"RESP_JUL" VARCHAR2(4000), 
	"RESP_AUG" VARCHAR2(4000), 
	"RESP_SEP" VARCHAR2(4000), 
	"RESP_OCT" VARCHAR2(4000), 
	"RESP_NOV" VARCHAR2(4000), 
	"RESP_DEC" VARCHAR2(4000), 
	"RESP_JAN" VARCHAR2(4000), 
	"RESP_FEB" VARCHAR2(4000), 
	"RESP_MAR" VARCHAR2(4000), 
	"IMPL_STATUS" VARCHAR2(200), 
	"DATA_SOURCE" VARCHAR2(2000), 
	"VERTICAL_COMMENTS" CLOB, 
	"EASE_COMMENTS" CLOB, 
	"DIRECTION_Q1" CLOB, 
	"ATR_Q1" CLOB, 
	"DIRECTION_Q2" CLOB, 
	"ATR_Q2" CLOB, 
	"DIRECTION_Q3" CLOB, 
	"ATR_Q3" CLOB, 
	"DIRECTION_Q4" CLOB, 
	"ATR_Q4" CLOB, 
	"TIMELINE_1" VARCHAR2(500), 
	"TIMELINE_2" VARCHAR2(500), 
	"TIMELINE_3" VARCHAR2(500), 
	"TIMELINE_4" VARCHAR2(500), 
	"STATUS" VARCHAR2(20) DEFAULT 'DRAFT', 
	"SUBMITTED_BY_EMP" VARCHAR2(50), 
	"SUBMITTED_AT" TIMESTAMP (6), 
	"UPDATED_BY_EMP" VARCHAR2(50), 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) ;

  CREATE TABLE "EASE_P1_METRIC" 
   (	"ID" NUMBER DEFAULT "RP_SEQ_GLOBAL"."NEXTVAL", 
	"ROW_ID" NUMBER, 
	"THEME_NO" VARCHAR2(50), 
	"THEME_NAME" VARCHAR2(200), 
	"AP_NO" VARCHAR2(50), 
	"AP_NAME" VARCHAR2(500), 
	"KCI_KPI" VARCHAR2(20), 
	"METRIC_TYPE" VARCHAR2(50), 
	"METRIC_SORT" VARCHAR2(50), 
	"METRIC_ID_CODE" VARCHAR2(100), 
	"METRIC_DESC" CLOB, 
	"EXPLANATORY_COMMENTS" CLOB, 
	"EXPECTED_RESPONSE_TYPE" VARCHAR2(100), 
	"BASELINE" VARCHAR2(2000), 
	"BMO_VERTICAL" VARCHAR2(500), 
	"BMS_VERTICAL" VARCHAR2(500)
   ) ;

  CREATE TABLE "EASE_P1_ROLE" 
   (	"ID" NUMBER DEFAULT "RP_SEQ_GLOBAL"."NEXTVAL", 
	"EMP_CODE" VARCHAR2(50), 
	"ROLE_CODE" VARCHAR2(20), 
	"VERTICAL_NAME" VARCHAR2(200), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) ;

  CREATE TABLE "EV_ACTIVITY_LOG" 
   (	"ID" NUMBER DEFAULT "RP_SEQ_GLOBAL"."NEXTVAL", 
	"ACTIVITY" VARCHAR2(50), 
	"ENTITY_TYPE" VARCHAR2(30), 
	"ENTITY_ID" NUMBER, 
	"ACTOR_EMP" VARCHAR2(20), 
	"VERTICAL_ID" NUMBER, 
	"DETAILS" VARCHAR2(2000), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) ;

  CREATE TABLE "EV_EVENT" 
   (	"ID" NUMBER DEFAULT "RP_SEQ_GLOBAL"."NEXTVAL", 
	"VERTICAL_ID" NUMBER, 
	"NAME" VARCHAR2(300), 
	"EVENT_DATE" DATE, 
	"TIME_TEXT" VARCHAR2(100), 
	"VENUE" VARCHAR2(300), 
	"POSTED_BY_EMP" VARCHAR2(20), 
	"POSTED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1
   ) ;

  CREATE TABLE "EV_POST" 
   (	"ID" NUMBER DEFAULT "RP_SEQ_GLOBAL"."NEXTVAL", 
	"VERTICAL_ID" NUMBER, 
	"EVENT_ID" NUMBER, 
	"TAG_ID" NUMBER, 
	"CAPTION" CLOB, 
	"POSTED_BY_EMP" VARCHAR2(20), 
	"POSTED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"IS_ARCHIVED" NUMBER(1,0) DEFAULT 0, 
	"ARCHIVED_AT" TIMESTAMP (6)
   ) ;

  CREATE TABLE "EV_POST_IMAGE" 
   (	"ID" NUMBER DEFAULT "RP_SEQ_GLOBAL"."NEXTVAL", 
	"POST_ID" NUMBER, 
	"FILE_PATH" VARCHAR2(500), 
	"FILE_NAME" VARCHAR2(300), 
	"CONTENT_TYPE" VARCHAR2(100), 
	"FILE_SIZE" NUMBER, 
	"SEQ_NO" NUMBER DEFAULT 0, 
	"IS_ARCHIVED" NUMBER(1,0) DEFAULT 0
   ) ;

  CREATE TABLE "EV_TAG" 
   (	"ID" NUMBER DEFAULT "RP_SEQ_GLOBAL"."NEXTVAL", 
	"NAME" VARCHAR2(60), 
	"IS_ENABLED" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY_EMP" VARCHAR2(20), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) ;

  CREATE TABLE "HF_AGGREGATED_COUNTER" 
   (	"ID" NUMBER(10,0), 
	"KEY" NVARCHAR2(255), 
	"VALUE" NUMBER(10,0), 
	"EXPIRE_AT" TIMESTAMP (4)
   ) ;

  CREATE TABLE "HF_COUNTER" 
   (	"ID" NUMBER(10,0), 
	"KEY" NVARCHAR2(255), 
	"VALUE" NUMBER(10,0), 
	"EXPIRE_AT" TIMESTAMP (4)
   ) ;

  CREATE TABLE "HF_DISTRIBUTED_LOCK" 
   (	"RESOURCE" NVARCHAR2(100), 
	"CREATED_AT" TIMESTAMP (4)
   ) ;

  CREATE TABLE "HF_HASH" 
   (	"ID" NUMBER(10,0), 
	"KEY" NVARCHAR2(255), 
	"VALUE" NCLOB, 
	"EXPIRE_AT" TIMESTAMP (4), 
	"FIELD" NVARCHAR2(40)
   ) ;

  CREATE TABLE "HF_JOB" 
   (	"ID" NUMBER(10,0), 
	"STATE_ID" NUMBER(10,0), 
	"STATE_NAME" NVARCHAR2(20), 
	"INVOCATION_DATA" NCLOB, 
	"ARGUMENTS" NCLOB, 
	"CREATED_AT" TIMESTAMP (4), 
	"EXPIRE_AT" TIMESTAMP (4)
   ) ;

  CREATE TABLE "HF_JOB_PARAMETER" 
   (	"ID" NUMBER(10,0), 
	"NAME" NVARCHAR2(40), 
	"VALUE" NCLOB, 
	"JOB_ID" NUMBER(10,0)
   ) ;

  CREATE TABLE "HF_JOB_QUEUE" 
   (	"ID" NUMBER(10,0), 
	"JOB_ID" NUMBER(10,0), 
	"QUEUE" NVARCHAR2(50), 
	"FETCHED_AT" TIMESTAMP (4), 
	"FETCH_TOKEN" NVARCHAR2(36)
   ) ;

  CREATE TABLE "HF_JOB_STATE" 
   (	"ID" NUMBER(10,0), 
	"JOB_ID" NUMBER(10,0), 
	"NAME" NVARCHAR2(20), 
	"REASON" NVARCHAR2(100), 
	"CREATED_AT" TIMESTAMP (4), 
	"DATA" NCLOB
   ) ;

  CREATE TABLE "HF_LIST" 
   (	"ID" NUMBER(10,0), 
	"KEY" NVARCHAR2(255), 
	"VALUE" NCLOB, 
	"EXPIRE_AT" TIMESTAMP (4)
   ) ;

  CREATE TABLE "HF_SERVER" 
   (	"ID" NVARCHAR2(100), 
	"DATA" NCLOB, 
	"LAST_HEART_BEAT" TIMESTAMP (4)
   ) ;

  CREATE TABLE "HF_SET" 
   (	"ID" NUMBER(10,0), 
	"KEY" NVARCHAR2(255), 
	"VALUE" NVARCHAR2(255), 
	"SCORE" FLOAT(126), 
	"EXPIRE_AT" TIMESTAMP (4)
   ) ;

  CREATE TABLE "MD_DELEGATION" 
   (	"ID" NUMBER(19,0) DEFAULT "MD_SEQ_GLOBAL"."NEXTVAL", 
	"FROM_EMPL_ID" VARCHAR2(50), 
	"TO_EMPL_ID" VARCHAR2(50), 
	"ROLE_CODE" VARCHAR2(50), 
	"VERTICAL_CODE" VARCHAR2(50), 
	"VALID_FROM" DATE, 
	"VALID_TO" DATE, 
	"REASON" VARCHAR2(500), 
	"MODIFIED_BY_EMP" VARCHAR2(50), 
	"MODIFIED_AT" TIMESTAMP (6), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) ;

  CREATE TABLE "MD_INAPP_NOTIF" 
   (	"ID" NUMBER(19,0) DEFAULT "MD_SEQ_GLOBAL"."NEXTVAL", 
	"EMPL_CODE" VARCHAR2(50), 
	"TITLE" VARCHAR2(200), 
	"BODY" VARCHAR2(2000), 
	"HREF" VARCHAR2(500), 
	"IS_READ" NUMBER(1,0) DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) ;

  CREATE TABLE "MD_NOTIF_OUTBOX" 
   (	"ID" NUMBER(19,0) DEFAULT "MD_SEQ_GLOBAL"."NEXTVAL", 
	"EVENT_CODE" VARCHAR2(100), 
	"CHANNEL" NUMBER(2,0), 
	"TO_ADDRESS" VARCHAR2(200), 
	"TO_EMPL_CODE" VARCHAR2(50), 
	"PAYLOAD_JSON" CLOB, 
	"STATUS" NUMBER(2,0) DEFAULT 0, 
	"ATTEMPTS" NUMBER(3,0) DEFAULT 0, 
	"LAST_ERROR" VARCHAR2(500), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"SENT_AT" TIMESTAMP (6)
   ) ;

  CREATE TABLE "MD_NOTIF_TEMPLATE" 
   (	"ID" NUMBER(19,0) DEFAULT "MD_SEQ_GLOBAL"."NEXTVAL", 
	"EVENT_CODE" VARCHAR2(100), 
	"CHANNEL" NUMBER(2,0), 
	"SUBJECT" VARCHAR2(500), 
	"BODY" CLOB, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1
   ) ;

  CREATE TABLE "MD_RBAC_MENU" 
   (	"ID" NUMBER(19,0) DEFAULT "MD_SEQ_GLOBAL"."NEXTVAL", 
	"MODULE_ID" NUMBER(19,0), 
	"LABEL" VARCHAR2(200), 
	"HREF" VARCHAR2(500), 
	"ICON" VARCHAR2(100), 
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1
   ) ;

  CREATE TABLE "MD_RBAC_MODULE" 
   (	"ID" NUMBER(19,0) DEFAULT "MD_SEQ_GLOBAL"."NEXTVAL", 
	"CODE" VARCHAR2(100), 
	"DISPLAY_NAME" VARCHAR2(200), 
	"PARENT_ID" NUMBER(19,0), 
	"KIND" NUMBER(2,0), 
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1
   ) ;

  CREATE TABLE "MD_ROLE" 
   (	"ID" NUMBER(19,0) DEFAULT "MD_SEQ_GLOBAL"."NEXTVAL", 
	"CODE" NUMBER(5,0), 
	"NAME" VARCHAR2(100)
   ) ;

  CREATE TABLE "MD_ROLE_MODULE_PERM" 
   (	"ID" NUMBER(19,0) DEFAULT "MD_SEQ_GLOBAL"."NEXTVAL", 
	"ROLE_ID" NUMBER(19,0), 
	"MODULE_ID" NUMBER(19,0), 
	"CAN_VIEW" NUMBER(1,0) DEFAULT 0, 
	"CAN_ADD" NUMBER(1,0) DEFAULT 0, 
	"CAN_MODIFY" NUMBER(1,0) DEFAULT 0, 
	"CAN_DELETE" NUMBER(1,0) DEFAULT 0, 
	"CAN_AUTHORIZE" NUMBER(1,0) DEFAULT 0
   ) ;

  CREATE TABLE "MD_USER" 
   (	"ID" NUMBER(19,0) DEFAULT "MD_SEQ_GLOBAL"."NEXTVAL", 
	"EMPL_ID" VARCHAR2(50), 
	"NAME" VARCHAR2(200), 
	"EMAIL" VARCHAR2(200), 
	"MOBILE" VARCHAR2(20), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6)
   ) ;

  CREATE TABLE "MD_USER_MODULE_PERM" 
   (	"ID" NUMBER(19,0) DEFAULT "MD_SEQ_GLOBAL"."NEXTVAL", 
	"EMPL_CODE" VARCHAR2(50), 
	"MODULE_ID" NUMBER(19,0), 
	"CAN_VIEW" NUMBER(1,0) DEFAULT 0, 
	"CAN_ADD" NUMBER(1,0) DEFAULT 0, 
	"CAN_MODIFY" NUMBER(1,0) DEFAULT 0, 
	"CAN_DELETE" NUMBER(1,0) DEFAULT 0, 
	"CAN_AUTHORIZE" NUMBER(1,0) DEFAULT 0, 
	"IS_DENY" NUMBER(1,0) DEFAULT 0
   ) ;

  CREATE TABLE "MD_USER_ROLE" 
   (	"ID" NUMBER(19,0) DEFAULT "MD_SEQ_GLOBAL"."NEXTVAL", 
	"USER_ID" NUMBER(19,0), 
	"ROLE_ID" NUMBER(19,0), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"VALID_FROM" DATE DEFAULT SYSDATE, 
	"VALID_TO" DATE
   ) ;

  CREATE TABLE "MYDIARY_LANDING_SITEMAP" 
   (	"ID" NUMBER(19,0) DEFAULT "MD_SEQ_GLOBAL"."NEXTVAL", 
	"NAME" VARCHAR2(200), 
	"URL" VARCHAR2(500), 
	"CATEGORY" VARCHAR2(100), 
	"SUB_CATEGORY" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(2000), 
	"KEYWORDS" VARCHAR2(2000), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1
   ) ;

  CREATE TABLE "RP_ATTACHMENT_BLOB" 
   (	"STORAGE_KEY" VARCHAR2(80), 
	"CONTENT" BLOB, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) ;

  CREATE TABLE "RP_AUDIT_LOG" 
   (	"ID" NUMBER(19,0), 
	"ENTITY" VARCHAR2(60), 
	"ENTITY_ID" NUMBER(19,0), 
	"ACTION" VARCHAR2(40), 
	"ACTOR_EMP_CODE" VARCHAR2(20), 
	"ACTED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"OLD_JSON" CLOB, 
	"NEW_JSON" CLOB, 
	"IP" VARCHAR2(64), 
	"USER_AGENT" VARCHAR2(500), 
	"HASH_PREV" VARCHAR2(64), 
	"HASH_CURR" VARCHAR2(64)
   ) ;

  CREATE TABLE "RP_DELEGATION" 
   (	"ID" NUMBER(19,0), 
	"FROM_EMP_CODE" VARCHAR2(20), 
	"TO_EMP_CODE" VARCHAR2(20), 
	"ROLE_CODE" VARCHAR2(30), 
	"VERTICAL_CODE" VARCHAR2(50), 
	"VALID_FROM" TIMESTAMP (6) WITH TIME ZONE, 
	"VALID_TO" TIMESTAMP (6) WITH TIME ZONE, 
	"REASON" VARCHAR2(500), 
	"MODIFIED_BY_EMP" VARCHAR2(20), 
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE
   ) ;

  CREATE TABLE "RP_ESCALATION_MATRIX" 
   (	"ID" NUMBER(19,0), 
	"ACTIVITY_ID" NUMBER(19,0), 
	"UNIT_ID" NUMBER(19,0), 
	"LEVEL_NO" NUMBER(2,0), 
	"PF_NUMBER" VARCHAR2(20), 
	"IP_NUMBER" VARCHAR2(50), 
	"GENERIC_MAIL" VARCHAR2(150), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" VARCHAR2(50), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_BY" VARCHAR2(50), 
	"UPDATED_AT" TIMESTAMP (6), 
	"REQUEST_TYPE_ID" NUMBER(19,0)
   ) ;

  CREATE TABLE "RP_M_ACTIVITY" 
   (	"ID" NUMBER(19,0), 
	"DEPARTMENT_ID" NUMBER(19,0), 
	"CODE" VARCHAR2(50), 
	"NAME" VARCHAR2(200), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"MODIFIED_BY" VARCHAR2(20), 
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE
   ) ;

  CREATE TABLE "RP_M_DEPARTMENT" 
   (	"ID" NUMBER(19,0), 
	"VERTICAL_ID" NUMBER(19,0), 
	"CODE" VARCHAR2(50), 
	"NAME" VARCHAR2(200), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"MODIFIED_BY" VARCHAR2(20), 
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE
   ) ;

  CREATE TABLE "RP_M_EMPLOYEE" 
   (	"PF_NUMBER" VARCHAR2(20), 
	"EMP_NAME" VARCHAR2(150), 
	"SCALE" VARCHAR2(20), 
	"EMP_ROLE" VARCHAR2(80), 
	"EMAIL" VARCHAR2(150), 
	"MOBILE" VARCHAR2(20), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1
   ) ;

  CREATE TABLE "RP_M_HOLIDAY" 
   (	"ID" NUMBER(19,0), 
	"CAL_ID" NUMBER(19,0), 
	"HOLIDAY_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(200), 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"MODIFIED_BY" VARCHAR2(20), 
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE
   ) ;

  CREATE TABLE "RP_M_HOLIDAY_CAL" 
   (	"ID" NUMBER(19,0), 
	"CODE" VARCHAR2(50), 
	"NAME" VARCHAR2(200), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"MODIFIED_BY" VARCHAR2(20), 
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE
   ) ;

  CREATE TABLE "RP_M_NOTIF_TEMPLATE" 
   (	"ID" NUMBER(19,0), 
	"EVENT_CODE" VARCHAR2(50), 
	"CHANNEL" NUMBER(1,0), 
	"SUBJECT" VARCHAR2(500), 
	"BODY" CLOB, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"MODIFIED_BY" VARCHAR2(20), 
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE
   ) ;

  CREATE TABLE "RP_M_REPORT_DEF" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"REPORT_NAME" VARCHAR2(200), 
	"VERTICAL_ID" NUMBER, 
	"DEPARTMENT_ID" NUMBER, 
	"SOURCE_TYPE" VARCHAR2(20), 
	"FILE_TYPE" VARCHAR2(10), 
	"FILE_PATH" VARCHAR2(1000), 
	"SFTP_HOST" VARCHAR2(200), 
	"SFTP_PORT" NUMBER, 
	"SFTP_USER" VARCHAR2(100), 
	"SFTP_PASSWORD" VARCHAR2(500), 
	"DB_CONN_STRING" VARCHAR2(1000), 
	"SQL_QUERY" CLOB, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY_EMP" VARCHAR2(20), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6), 
	"RUNNING_FROM" VARCHAR2(2) DEFAULT 'DC', 
	"FILE_PATH_DR" VARCHAR2(1000), 
	"SFTP_HOST_DR" VARCHAR2(200), 
	"SFTP_PORT_DR" NUMBER, 
	"SFTP_USER_DR" VARCHAR2(100), 
	"SFTP_PASSWORD_DR" VARCHAR2(500), 
	"DB_CONN_STRING_DR" VARCHAR2(1000)
   ) ;

  CREATE TABLE "RP_M_REQTYPE_UNITTYPE" 
   (	"ID" NUMBER(19,0), 
	"REQUEST_TYPE_ID" NUMBER(19,0), 
	"UNIT_TYPE_ID" NUMBER(19,0)
   ) ;

  CREATE TABLE "RP_M_REQUEST_TYPE" 
   (	"ID" NUMBER(19,0), 
	"CODE" VARCHAR2(50), 
	"NAME" VARCHAR2(200), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"MODIFIED_BY" VARCHAR2(20), 
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE, 
	"ENTRY_MODE" VARCHAR2(10) DEFAULT 'BOTH'
   ) ;

  CREATE TABLE "RP_M_ROUTING_ASSIGNEE" 
   (	"ID" NUMBER(19,0), 
	"RULE_ID" NUMBER(19,0), 
	"EMP_CODE" VARCHAR2(20), 
	"IS_PRIMARY" NUMBER(1,0) DEFAULT 1
   ) ;

  CREATE TABLE "RP_M_ROUTING_RULE" 
   (	"ID" NUMBER(19,0), 
	"REQUEST_TYPE_ID" NUMBER(19,0), 
	"UNIT_TYPE_ID" NUMBER(19,0), 
	"VERTICAL_ID" NUMBER(19,0), 
	"DEPARTMENT_ID" NUMBER(19,0), 
	"ACTIVITY_ID" NUMBER(19,0), 
	"PRIORITY" NUMBER(5,0), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"MODIFIED_BY" VARCHAR2(20), 
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE
   ) ;

  CREATE TABLE "RP_M_SLA_CONFIG" 
   (	"ID" NUMBER(19,0), 
	"REQUEST_TYPE_ID" NUMBER(19,0), 
	"LEVEL_NO" NUMBER(2,0), 
	"WORKING_DAYS" NUMBER(3,0), 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"MODIFIED_BY" VARCHAR2(20), 
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE
   ) ;

  CREATE TABLE "RP_M_UNIT" 
   (	"ID" NUMBER(19,0), 
	"UNIT_TYPE_ID" NUMBER(19,0), 
	"PARENT_UNIT_ID" NUMBER(19,0), 
	"CODE" VARCHAR2(50), 
	"NAME" VARCHAR2(200), 
	"HOLIDAY_CAL_ID" NUMBER(19,0), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"MODIFIED_BY" VARCHAR2(20), 
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE
   ) ;

  CREATE TABLE "RP_M_UNIT_TYPE" 
   (	"ID" NUMBER(19,0), 
	"CODE" VARCHAR2(20), 
	"NAME" VARCHAR2(100), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"MODIFIED_BY" VARCHAR2(20), 
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE
   ) ;

  CREATE TABLE "RP_M_UNIT_VERTICAL" 
   (	"ID" NUMBER(19,0), 
	"UNIT_ID" NUMBER(19,0), 
	"VERTICAL_ID" NUMBER(19,0)
   ) ;

  CREATE TABLE "RP_M_VERTICAL" 
   (	"ID" NUMBER(19,0), 
	"CODE" VARCHAR2(50), 
	"NAME" VARCHAR2(200), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_BY" VARCHAR2(20), 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"MODIFIED_BY" VARCHAR2(20), 
	"MODIFIED_AT" TIMESTAMP (6) WITH TIME ZONE
   ) ;

  CREATE TABLE "RP_NOTIFICATION" 
   (	"ID" NUMBER(19,0), 
	"TITLE" VARCHAR2(200), 
	"MESSAGE" VARCHAR2(2000), 
	"CATEGORY" VARCHAR2(50), 
	"REDIRECT_URL" VARCHAR2(500), 
	"SOURCE" VARCHAR2(20), 
	"EVENT_CODE" VARCHAR2(50), 
	"REQUEST_ID" NUMBER(19,0), 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"READ_AT" TIMESTAMP (6) WITH TIME ZONE, 
	"USER_ID" NUMBER(19,0)
   ) ;

  CREATE TABLE "RP_NOTIF_OUTBOX" 
   (	"ID" NUMBER(19,0), 
	"EVENT_CODE" VARCHAR2(50), 
	"CHANNEL" NUMBER(1,0), 
	"TO_ADDR" VARCHAR2(300), 
	"PAYLOAD_JSON" CLOB, 
	"STATUS" NUMBER(1,0) DEFAULT 0, 
	"ATTEMPTS" NUMBER(3,0) DEFAULT 0, 
	"LAST_ERROR" VARCHAR2(2000), 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"SENT_AT" TIMESTAMP (6) WITH TIME ZONE
   ) ;

  CREATE TABLE "RP_PAGE_INFO" 
   (	"PAGE_KEY" VARCHAR2(100), 
	"PAGE_NAME" VARCHAR2(200), 
	"PAGE_TYPE" VARCHAR2(50) DEFAULT 'Dashboard', 
	"DESCRIPTION" VARCHAR2(1000), 
	"OWNER_VERTICAL" VARCHAR2(200), 
	"MODULE_OWNER" VARCHAR2(200), 
	"IP_NUMBER" VARCHAR2(100), 
	"MAIL_ID" VARCHAR2(200), 
	"VERSION" VARCHAR2(20) DEFAULT 'v1.0', 
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE', 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"UPDATED_DATE" DATE
   ) ;

  CREATE TABLE "RP_RBAC_APP_ADMIN" 
   (	"ID" NUMBER(19,0), 
	"EMP_CODE" VARCHAR2(20), 
	"ASSIGNED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"ASSIGNED_BY_EMP" VARCHAR2(20), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"NOTE" VARCHAR2(1000)
   ) ;

  CREATE TABLE "RP_RBAC_AUDIT" 
   (	"ID" NUMBER(19,0), 
	"AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"ACTOR_EMP_CODE" VARCHAR2(20), 
	"ACTION" VARCHAR2(40), 
	"TARGET" VARCHAR2(300), 
	"DETAILS" VARCHAR2(2000)
   ) ;

  CREATE TABLE "RP_RBAC_MENU" 
   (	"ID" NUMBER(19,0), 
	"MODULE_ID" NUMBER(19,0), 
	"CODE" VARCHAR2(80), 
	"LABEL" VARCHAR2(200), 
	"ICON" VARCHAR2(60), 
	"ROUTE" VARCHAR2(300), 
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0, 
	"IS_ENABLED" NUMBER(1,0) DEFAULT 1, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP
   ) ;

  CREATE TABLE "RP_RBAC_MODULE" 
   (	"ID" NUMBER(19,0), 
	"CODE" VARCHAR2(60), 
	"NAME" VARCHAR2(200), 
	"KIND" NUMBER(2,0) DEFAULT 1, 
	"PARENT_ID" NUMBER(19,0), 
	"ICON" VARCHAR2(60), 
	"SORT_ORDER" NUMBER(5,0) DEFAULT 0, 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP
   ) ;

  CREATE TABLE "RP_RBAC_ROLE_PERM" 
   (	"ID" NUMBER(19,0), 
	"ROLE_ID" NUMBER(19,0), 
	"MODULE_ID" NUMBER(19,0), 
	"CAN_VIEW" NUMBER(1,0) DEFAULT 0, 
	"CAN_ADD" NUMBER(1,0) DEFAULT 0, 
	"CAN_MODIFY" NUMBER(1,0) DEFAULT 0, 
	"CAN_DELETE" NUMBER(1,0) DEFAULT 0, 
	"CAN_AUTHORIZE" NUMBER(1,0) DEFAULT 0, 
	"UPDATED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"UPDATED_BY_EMP" VARCHAR2(20)
   ) ;

  CREATE TABLE "RP_RBAC_SUPER_ADMIN" 
   (	"ID" NUMBER(19,0), 
	"EMP_CODE" VARCHAR2(20), 
	"ASSIGNED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"ASSIGNED_BY" VARCHAR2(60) DEFAULT 'BOOT'
   ) ;

  CREATE TABLE "RP_RBAC_USER_PERM" 
   (	"ID" NUMBER(19,0), 
	"EMP_CODE" VARCHAR2(20), 
	"MODULE_ID" NUMBER(19,0), 
	"IS_DENY" NUMBER(1,0) DEFAULT 0, 
	"CAN_VIEW" NUMBER(1,0) DEFAULT 0, 
	"CAN_ADD" NUMBER(1,0) DEFAULT 0, 
	"CAN_MODIFY" NUMBER(1,0) DEFAULT 0, 
	"CAN_DELETE" NUMBER(1,0) DEFAULT 0, 
	"CAN_AUTHORIZE" NUMBER(1,0) DEFAULT 0, 
	"UPDATED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"UPDATED_BY_EMP" VARCHAR2(20)
   ) ;

  CREATE TABLE "RP_RBAC_VERTICAL_ADMIN" 
   (	"ID" NUMBER(19,0), 
	"VERTICAL_ID" NUMBER(19,0), 
	"EMP_CODE" VARCHAR2(20), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"ASSIGNED_BY_EMP" VARCHAR2(20), 
	"ASSIGNED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"REVOKED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE
   ) ;

  CREATE TABLE "RP_RBAC_VERTICAL_LEVEL" 
   (	"ID" NUMBER(19,0), 
	"VERTICAL_ID" NUMBER(19,0), 
	"EMP_CODE" VARCHAR2(20), 
	"LEVEL_CODE" VARCHAR2(10), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"ASSIGNED_BY_EMP" VARCHAR2(20), 
	"ASSIGNED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"REVOKED_AT_UTC" TIMESTAMP (6) WITH TIME ZONE
   ) ;

  CREATE TABLE "RP_REPORT_ACCESS_LOG" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"REPORT_ID" NUMBER, 
	"REPORT_NAME" VARCHAR2(200), 
	"ACCESSED_BY" VARCHAR2(20), 
	"ACCESSED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"RUNNING_FROM" VARCHAR2(2), 
	"ROWS_RETURNED" NUMBER, 
	"SUCCESS" NUMBER(1,0), 
	"ERROR_MSG" VARCHAR2(2000)
   ) ;

  CREATE TABLE "RP_REPORT_AUDIT_LOG" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"REPORT_ID" NUMBER, 
	"REPORT_NAME" VARCHAR2(200), 
	"ACTION" VARCHAR2(20), 
	"ACTOR_EMP" VARCHAR2(20), 
	"ACTOR_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"DETAILS" VARCHAR2(2000)
   ) ;

  CREATE TABLE "RP_REQUEST" 
   (	"ID" NUMBER(19,0), 
	"REQ_NO" VARCHAR2(20), 
	"REQUEST_TYPE_ID" NUMBER(19,0), 
	"UNIT_ID" NUMBER(19,0), 
	"VERTICAL_ID" NUMBER(19,0), 
	"DEPARTMENT_ID" NUMBER(19,0), 
	"ACTIVITY_ID" NUMBER(19,0), 
	"RAISED_BY_EMP" VARCHAR2(20), 
	"SUBJECT" VARCHAR2(500), 
	"DESCRIPTION" CLOB, 
	"CURRENT_LEVEL" NUMBER(2,0) DEFAULT 1, 
	"STATUS" NUMBER(2,0) DEFAULT 1, 
	"SLA_DUE_UTC" TIMESTAMP (6) WITH TIME ZONE, 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"CLOSED_AT" TIMESTAMP (6) WITH TIME ZONE, 
	"ROW_VERSION" NUMBER(10,0) DEFAULT 0, 
	"RAISED_BY" NUMBER, 
	"EXT_ALERT_ID" VARCHAR2(100), 
	"EXT_SOURCE" VARCHAR2(30)
   ) ;

  CREATE TABLE "RP_REQUEST_ACTION" 
   (	"ID" NUMBER(19,0), 
	"REQUEST_ID" NUMBER(19,0), 
	"LEVEL_NO" NUMBER(2,0), 
	"ACTOR_EMP_CODE" VARCHAR2(20), 
	"ACTION" VARCHAR2(50), 
	"REMARKS" VARCHAR2(2000), 
	"ACTED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP
   ) ;

  CREATE TABLE "RP_REQUEST_ASSIGNEE" 
   (	"ID" NUMBER(19,0), 
	"REQUEST_ID" NUMBER(19,0), 
	"LEVEL_NO" NUMBER(2,0), 
	"EMP_CODE" VARCHAR2(20), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"ASSIGNED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"ASSIGNED_BY_EMP" VARCHAR2(20)
   ) ;

  CREATE TABLE "RP_REQUEST_ATTACHMENT" 
   (	"ID" NUMBER(19,0), 
	"REQUEST_ID" NUMBER(19,0), 
	"ACTION_ID" NUMBER(19,0), 
	"FILE_NAME" VARCHAR2(300), 
	"MIME" VARCHAR2(100), 
	"SIZE_BYTES" NUMBER(19,0), 
	"STORAGE_KEY" VARCHAR2(500), 
	"UPLOADED_BY_EMP" VARCHAR2(20), 
	"UPLOADED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"SHA256" VARCHAR2(64)
   ) ;

  CREATE TABLE "RP_REQUEST_CLARIFICATION" 
   (	"ID" NUMBER(19,0), 
	"REQUEST_ID" NUMBER(19,0), 
	"ASKED_BY_EMP" VARCHAR2(20), 
	"ASKED_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"REPLIED_AT" TIMESTAMP (6) WITH TIME ZONE, 
	"QUESTION" VARCHAR2(2000), 
	"ANSWER" VARCHAR2(2000)
   ) ;

  CREATE TABLE "RP_REQUEST_FEEDBACK" 
   (	"ID" NUMBER(19,0), 
	"REQUEST_ID" NUMBER(19,0), 
	"RATING" NUMBER(1,0), 
	"COMMENTS" VARCHAR2(2000), 
	"GIVEN_AT" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP
   ) ;

  CREATE TABLE "RP_ROLE" 
   (	"ID" NUMBER(19,0), 
	"CODE" VARCHAR2(30), 
	"NAME" VARCHAR2(100)
   ) ;

  CREATE TABLE "RP_SLA_PAUSE_LOG" 
   (	"ID" NUMBER(19,0), 
	"REQUEST_ID" NUMBER(19,0), 
	"PAUSED_AT" TIMESTAMP (6) WITH TIME ZONE, 
	"RESUMED_AT" TIMESTAMP (6) WITH TIME ZONE, 
	"REASON" VARCHAR2(500)
   ) ;

  CREATE TABLE "RP_UAT_AUTH" 
   (	"EMPLOYEE_CODE" VARCHAR2(20), 
	"PWD_HASH" VARCHAR2(200), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1
   ) ;

  CREATE TABLE "RP_UAT_STAFF" 
   (	"EMPLOYEE_CODE" VARCHAR2(20), 
	"EMPLOYEE_NAME" VARCHAR2(100), 
	"UNIT_TYPE" VARCHAR2(10), 
	"USER_LEVEL" VARCHAR2(10), 
	"UNIT_CODE" VARCHAR2(20), 
	"UNIT_NAME" VARCHAR2(100), 
	"VERTICAL_CODE" VARCHAR2(20), 
	"VERTICAL_NAME" VARCHAR2(100), 
	"IS_HEAD" NUMBER(1,0) DEFAULT 0, 
	"DESIGNATION" VARCHAR2(100), 
	"EMAIL" VARCHAR2(100), 
	"MOBILE" VARCHAR2(15)
   ) ;

  CREATE TABLE "RP_USER" 
   (	"ID" NUMBER, 
	"EMP_CODE" VARCHAR2(20), 
	"AD_SAM" VARCHAR2(50), 
	"NAME" VARCHAR2(200), 
	"EMAIL" VARCHAR2(200), 
	"MOBILE" VARCHAR2(20), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"UPDATED_AT" TIMESTAMP (6)
   ) ;

  CREATE TABLE "RP_USER_ROLE" 
   (	"ID" NUMBER(19,0), 
	"EMP_CODE" VARCHAR2(20), 
	"ROLE_ID" NUMBER(19,0), 
	"UNIT_CODE" VARCHAR2(50), 
	"VERTICAL_CODE" VARCHAR2(50), 
	"VALID_FROM" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP, 
	"VALID_TO" TIMESTAMP (6) WITH TIME ZONE, 
	"GRANTED_BY" VARCHAR2(20)
   ) ;
-- ===================== PRIMARY KEY / UNIQUE / CHECK CONSTRAINTS (as ALTER TABLE, per table) =====================

  ALTER TABLE "EASE_P1_ENTRY" MODIFY ("METRIC_ID" NOT NULL ENABLE);
  ALTER TABLE "EASE_P1_ENTRY" MODIFY ("FY" NOT NULL ENABLE);
  ALTER TABLE "EASE_P1_ENTRY" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "EASE_P1_ENTRY" ADD CONSTRAINT "EASE_P1_ENTRY_UQ" UNIQUE ("METRIC_ID", "FY")
  USING INDEX  ENABLE;

  ALTER TABLE "EASE_P1_METRIC" MODIFY ("ROW_ID" NOT NULL ENABLE);
  ALTER TABLE "EASE_P1_METRIC" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "EASE_P1_ROLE" MODIFY ("EMP_CODE" NOT NULL ENABLE);
  ALTER TABLE "EASE_P1_ROLE" MODIFY ("ROLE_CODE" NOT NULL ENABLE);
  ALTER TABLE "EASE_P1_ROLE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "EASE_P1_ROLE" ADD CONSTRAINT "EASE_P1_ROLE_UQ" UNIQUE ("EMP_CODE", "ROLE_CODE", "VERTICAL_NAME")
  USING INDEX  ENABLE;

  ALTER TABLE "EV_ACTIVITY_LOG" MODIFY ("ACTIVITY" NOT NULL ENABLE);
  ALTER TABLE "EV_ACTIVITY_LOG" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "EV_EVENT" MODIFY ("VERTICAL_ID" NOT NULL ENABLE);
  ALTER TABLE "EV_EVENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "EV_EVENT" MODIFY ("POSTED_BY_EMP" NOT NULL ENABLE);
  ALTER TABLE "EV_EVENT" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "EV_EVENT" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "EV_POST" MODIFY ("VERTICAL_ID" NOT NULL ENABLE);
  ALTER TABLE "EV_POST" MODIFY ("POSTED_BY_EMP" NOT NULL ENABLE);
  ALTER TABLE "EV_POST" MODIFY ("IS_ARCHIVED" NOT NULL ENABLE);
  ALTER TABLE "EV_POST" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "EV_POST_IMAGE" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "EV_POST_IMAGE" MODIFY ("FILE_PATH" NOT NULL ENABLE);
  ALTER TABLE "EV_POST_IMAGE" MODIFY ("IS_ARCHIVED" NOT NULL ENABLE);
  ALTER TABLE "EV_POST_IMAGE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "EV_TAG" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "EV_TAG" MODIFY ("IS_ENABLED" NOT NULL ENABLE);
  ALTER TABLE "EV_TAG" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "EV_TAG" ADD UNIQUE ("NAME")
  USING INDEX  ENABLE;

  ALTER TABLE "HF_AGGREGATED_COUNTER" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "HF_AGGREGATED_COUNTER" ADD UNIQUE ("KEY")
  USING INDEX  ENABLE;

  ALTER TABLE "HF_COUNTER" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "HF_HASH" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "HF_HASH" ADD UNIQUE ("KEY", "FIELD")
  USING INDEX  ENABLE;

  ALTER TABLE "HF_JOB" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "HF_JOB_PARAMETER" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "HF_JOB_QUEUE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "HF_JOB_STATE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "HF_LIST" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "HF_SERVER" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "HF_SET" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "HF_SET" ADD UNIQUE ("KEY", "VALUE")
  USING INDEX  ENABLE;

  ALTER TABLE "MD_DELEGATION" MODIFY ("FROM_EMPL_ID" NOT NULL ENABLE);
  ALTER TABLE "MD_DELEGATION" MODIFY ("TO_EMPL_ID" NOT NULL ENABLE);
  ALTER TABLE "MD_DELEGATION" MODIFY ("ROLE_CODE" NOT NULL ENABLE);
  ALTER TABLE "MD_DELEGATION" MODIFY ("VALID_FROM" NOT NULL ENABLE);
  ALTER TABLE "MD_DELEGATION" MODIFY ("VALID_TO" NOT NULL ENABLE);
  ALTER TABLE "MD_DELEGATION" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MD_DELEGATION" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "MD_INAPP_NOTIF" MODIFY ("EMPL_CODE" NOT NULL ENABLE);
  ALTER TABLE "MD_INAPP_NOTIF" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "MD_INAPP_NOTIF" MODIFY ("IS_READ" NOT NULL ENABLE);
  ALTER TABLE "MD_INAPP_NOTIF" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MD_INAPP_NOTIF" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "MD_NOTIF_OUTBOX" MODIFY ("EVENT_CODE" NOT NULL ENABLE);
  ALTER TABLE "MD_NOTIF_OUTBOX" MODIFY ("CHANNEL" NOT NULL ENABLE);
  ALTER TABLE "MD_NOTIF_OUTBOX" MODIFY ("TO_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "MD_NOTIF_OUTBOX" MODIFY ("TO_EMPL_CODE" NOT NULL ENABLE);
  ALTER TABLE "MD_NOTIF_OUTBOX" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "MD_NOTIF_OUTBOX" MODIFY ("ATTEMPTS" NOT NULL ENABLE);
  ALTER TABLE "MD_NOTIF_OUTBOX" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MD_NOTIF_OUTBOX" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "MD_NOTIF_TEMPLATE" MODIFY ("EVENT_CODE" NOT NULL ENABLE);
  ALTER TABLE "MD_NOTIF_TEMPLATE" MODIFY ("CHANNEL" NOT NULL ENABLE);
  ALTER TABLE "MD_NOTIF_TEMPLATE" MODIFY ("BODY" NOT NULL ENABLE);
  ALTER TABLE "MD_NOTIF_TEMPLATE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "MD_NOTIF_TEMPLATE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MD_NOTIF_TEMPLATE" ADD CONSTRAINT "UQ_NOTIF_TEMPLATE" UNIQUE ("EVENT_CODE", "CHANNEL")
  USING INDEX  ENABLE;

  ALTER TABLE "MD_RBAC_MENU" MODIFY ("MODULE_ID" NOT NULL ENABLE);
  ALTER TABLE "MD_RBAC_MENU" MODIFY ("LABEL" NOT NULL ENABLE);
  ALTER TABLE "MD_RBAC_MENU" MODIFY ("SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "MD_RBAC_MENU" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "MD_RBAC_MENU" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "MD_RBAC_MODULE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "MD_RBAC_MODULE" MODIFY ("DISPLAY_NAME" NOT NULL ENABLE);
  ALTER TABLE "MD_RBAC_MODULE" MODIFY ("KIND" NOT NULL ENABLE);
  ALTER TABLE "MD_RBAC_MODULE" MODIFY ("SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "MD_RBAC_MODULE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "MD_RBAC_MODULE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MD_RBAC_MODULE" ADD CONSTRAINT "UQ_MD_RBAC_MODULE_CODE" UNIQUE ("CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "MD_ROLE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "MD_ROLE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MD_ROLE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MD_ROLE" ADD CONSTRAINT "UQ_MD_ROLE_CODE" UNIQUE ("CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "MD_ROLE_MODULE_PERM" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "MD_ROLE_MODULE_PERM" MODIFY ("MODULE_ID" NOT NULL ENABLE);
  ALTER TABLE "MD_ROLE_MODULE_PERM" MODIFY ("CAN_VIEW" NOT NULL ENABLE);
  ALTER TABLE "MD_ROLE_MODULE_PERM" MODIFY ("CAN_ADD" NOT NULL ENABLE);
  ALTER TABLE "MD_ROLE_MODULE_PERM" MODIFY ("CAN_MODIFY" NOT NULL ENABLE);
  ALTER TABLE "MD_ROLE_MODULE_PERM" MODIFY ("CAN_DELETE" NOT NULL ENABLE);
  ALTER TABLE "MD_ROLE_MODULE_PERM" MODIFY ("CAN_AUTHORIZE" NOT NULL ENABLE);
  ALTER TABLE "MD_ROLE_MODULE_PERM" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MD_ROLE_MODULE_PERM" ADD CONSTRAINT "UQ_ROLE_MODULE" UNIQUE ("ROLE_ID", "MODULE_ID")
  USING INDEX  ENABLE;

  ALTER TABLE "MD_USER" MODIFY ("EMPL_ID" NOT NULL ENABLE);
  ALTER TABLE "MD_USER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MD_USER" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "MD_USER" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MD_USER" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MD_USER" ADD CONSTRAINT "UQ_MD_USER_EMPL_ID" UNIQUE ("EMPL_ID")
  USING INDEX  ENABLE;

  ALTER TABLE "MD_USER_MODULE_PERM" MODIFY ("EMPL_CODE" NOT NULL ENABLE);
  ALTER TABLE "MD_USER_MODULE_PERM" MODIFY ("MODULE_ID" NOT NULL ENABLE);
  ALTER TABLE "MD_USER_MODULE_PERM" MODIFY ("CAN_VIEW" NOT NULL ENABLE);
  ALTER TABLE "MD_USER_MODULE_PERM" MODIFY ("CAN_ADD" NOT NULL ENABLE);
  ALTER TABLE "MD_USER_MODULE_PERM" MODIFY ("CAN_MODIFY" NOT NULL ENABLE);
  ALTER TABLE "MD_USER_MODULE_PERM" MODIFY ("CAN_DELETE" NOT NULL ENABLE);
  ALTER TABLE "MD_USER_MODULE_PERM" MODIFY ("CAN_AUTHORIZE" NOT NULL ENABLE);
  ALTER TABLE "MD_USER_MODULE_PERM" MODIFY ("IS_DENY" NOT NULL ENABLE);
  ALTER TABLE "MD_USER_MODULE_PERM" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "MD_USER_MODULE_PERM" ADD CONSTRAINT "UQ_USER_MODULE" UNIQUE ("EMPL_CODE", "MODULE_ID")
  USING INDEX  ENABLE;

  ALTER TABLE "MD_USER_ROLE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MD_USER_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "MD_USER_ROLE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "MD_USER_ROLE" MODIFY ("VALID_FROM" NOT NULL ENABLE);
  ALTER TABLE "MD_USER_ROLE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "MYDIARY_LANDING_SITEMAP" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MYDIARY_LANDING_SITEMAP" MODIFY ("URL" NOT NULL ENABLE);
  ALTER TABLE "MYDIARY_LANDING_SITEMAP" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "MYDIARY_LANDING_SITEMAP" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_ATTACHMENT_BLOB" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "RP_ATTACHMENT_BLOB" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_ATTACHMENT_BLOB" ADD PRIMARY KEY ("STORAGE_KEY")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_AUDIT_LOG" MODIFY ("ENTITY" NOT NULL ENABLE);
  ALTER TABLE "RP_AUDIT_LOG" MODIFY ("ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_AUDIT_LOG" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "RP_AUDIT_LOG" MODIFY ("ACTED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_AUDIT_LOG" MODIFY ("HASH_CURR" NOT NULL ENABLE);
  ALTER TABLE "RP_AUDIT_LOG" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_DELEGATION" MODIFY ("FROM_EMP_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_DELEGATION" MODIFY ("TO_EMP_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_DELEGATION" MODIFY ("ROLE_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_DELEGATION" MODIFY ("VALID_FROM" NOT NULL ENABLE);
  ALTER TABLE "RP_DELEGATION" MODIFY ("VALID_TO" NOT NULL ENABLE);
  ALTER TABLE "RP_DELEGATION" ADD CONSTRAINT "CK_DELEG_DIFF" CHECK (FROM_EMP_CODE <> TO_EMP_CODE) ENABLE;
  ALTER TABLE "RP_DELEGATION" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_ESCALATION_MATRIX" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RP_ESCALATION_MATRIX" MODIFY ("ACTIVITY_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_ESCALATION_MATRIX" MODIFY ("LEVEL_NO" NOT NULL ENABLE);
  ALTER TABLE "RP_ESCALATION_MATRIX" MODIFY ("PF_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "RP_ESCALATION_MATRIX" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_ESCALATION_MATRIX" ADD CONSTRAINT "CK_RP_ESC_LEVEL" CHECK (LEVEL_NO BETWEEN 1 AND 5) ENABLE;
  ALTER TABLE "RP_ESCALATION_MATRIX" ADD CONSTRAINT "PK_RP_ESC_MATRIX" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_M_ACTIVITY" MODIFY ("DEPARTMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_M_ACTIVITY" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_ACTIVITY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "RP_M_ACTIVITY" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_ACTIVITY" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_M_ACTIVITY" ADD UNIQUE ("CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_M_DEPARTMENT" MODIFY ("VERTICAL_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_M_DEPARTMENT" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_DEPARTMENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "RP_M_DEPARTMENT" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_DEPARTMENT" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_M_DEPARTMENT" ADD UNIQUE ("CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_M_EMPLOYEE" MODIFY ("PF_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "RP_M_EMPLOYEE" MODIFY ("EMP_NAME" NOT NULL ENABLE);
  ALTER TABLE "RP_M_EMPLOYEE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_EMPLOYEE" ADD CONSTRAINT "PK_RP_M_EMPLOYEE" PRIMARY KEY ("PF_NUMBER")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_M_HOLIDAY" MODIFY ("CAL_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_M_HOLIDAY" MODIFY ("HOLIDAY_DATE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_HOLIDAY" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_M_HOLIDAY" ADD CONSTRAINT "UK_HOLIDAY" UNIQUE ("CAL_ID", "HOLIDAY_DATE")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_M_HOLIDAY_CAL" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_HOLIDAY_CAL" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "RP_M_HOLIDAY_CAL" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_HOLIDAY_CAL" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_M_HOLIDAY_CAL" ADD UNIQUE ("CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_M_NOTIF_TEMPLATE" MODIFY ("EVENT_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_NOTIF_TEMPLATE" MODIFY ("CHANNEL" NOT NULL ENABLE);
  ALTER TABLE "RP_M_NOTIF_TEMPLATE" MODIFY ("BODY" NOT NULL ENABLE);
  ALTER TABLE "RP_M_NOTIF_TEMPLATE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_NOTIF_TEMPLATE" ADD CONSTRAINT "CK_NOTIF_CHN" CHECK (CHANNEL IN (1, 2)) ENABLE;
  ALTER TABLE "RP_M_NOTIF_TEMPLATE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_M_NOTIF_TEMPLATE" ADD CONSTRAINT "UK_NOTIF_TPL" UNIQUE ("EVENT_CODE", "CHANNEL")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_M_REPORT_DEF" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RP_M_REPORT_DEF" MODIFY ("REPORT_NAME" NOT NULL ENABLE);
  ALTER TABLE "RP_M_REPORT_DEF" MODIFY ("VERTICAL_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_M_REPORT_DEF" MODIFY ("DEPARTMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_M_REPORT_DEF" MODIFY ("SOURCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_REPORT_DEF" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_REPORT_DEF" MODIFY ("CREATED_BY_EMP" NOT NULL ENABLE);
  ALTER TABLE "RP_M_REPORT_DEF" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_M_REPORT_DEF" ADD CONSTRAINT "CK_RP_REPORT_SRC" CHECK (SOURCE_TYPE IN ('FILE_PATH','SFTP','ORACLE_DB','SQLSERVER_DB')) ENABLE;
  ALTER TABLE "RP_M_REPORT_DEF" ADD CONSTRAINT "PK_RP_M_REPORT_DEF" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_M_REPORT_DEF" MODIFY ("RUNNING_FROM" NOT NULL ENABLE);
  ALTER TABLE "RP_M_REPORT_DEF" ADD CONSTRAINT "CK_RP_REPORT_RUNFROM" CHECK (RUNNING_FROM IN ('DC','DR')) ENABLE;

  ALTER TABLE "RP_M_REQTYPE_UNITTYPE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RP_M_REQTYPE_UNITTYPE" MODIFY ("REQUEST_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_M_REQTYPE_UNITTYPE" MODIFY ("UNIT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_M_REQTYPE_UNITTYPE" ADD CONSTRAINT "PK_RP_RT_UT" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_M_REQTYPE_UNITTYPE" ADD CONSTRAINT "UQ_RP_RT_UT" UNIQUE ("REQUEST_TYPE_ID", "UNIT_TYPE_ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_M_REQUEST_TYPE" ADD CONSTRAINT "CK_RP_REQTYPE_ENTRYMODE" CHECK (ENTRY_MODE IN ('MANUAL','API','BOTH')) ENABLE;
  ALTER TABLE "RP_M_REQUEST_TYPE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_REQUEST_TYPE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "RP_M_REQUEST_TYPE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_REQUEST_TYPE" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_M_REQUEST_TYPE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_M_REQUEST_TYPE" ADD UNIQUE ("CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_M_ROUTING_ASSIGNEE" MODIFY ("RULE_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_M_ROUTING_ASSIGNEE" MODIFY ("EMP_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_ROUTING_ASSIGNEE" MODIFY ("IS_PRIMARY" NOT NULL ENABLE);
  ALTER TABLE "RP_M_ROUTING_ASSIGNEE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_M_ROUTING_RULE" MODIFY ("REQUEST_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_M_ROUTING_RULE" MODIFY ("PRIORITY" NOT NULL ENABLE);
  ALTER TABLE "RP_M_ROUTING_RULE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_ROUTING_RULE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_M_SLA_CONFIG" MODIFY ("REQUEST_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_M_SLA_CONFIG" MODIFY ("LEVEL_NO" NOT NULL ENABLE);
  ALTER TABLE "RP_M_SLA_CONFIG" MODIFY ("WORKING_DAYS" NOT NULL ENABLE);
  ALTER TABLE "RP_M_SLA_CONFIG" ADD CONSTRAINT "CK_SLA_LEVEL" CHECK (LEVEL_NO BETWEEN 1 AND 5) ENABLE;
  ALTER TABLE "RP_M_SLA_CONFIG" ADD CONSTRAINT "CK_SLA_DAYS" CHECK (WORKING_DAYS > 0) ENABLE;
  ALTER TABLE "RP_M_SLA_CONFIG" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_M_SLA_CONFIG" ADD CONSTRAINT "UK_SLA" UNIQUE ("REQUEST_TYPE_ID", "LEVEL_NO")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_M_UNIT" MODIFY ("UNIT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_M_UNIT" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_UNIT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "RP_M_UNIT" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_UNIT" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_M_UNIT" ADD UNIQUE ("CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_M_UNIT_TYPE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_UNIT_TYPE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "RP_M_UNIT_TYPE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_UNIT_TYPE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_M_UNIT_TYPE" ADD UNIQUE ("CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_M_UNIT_VERTICAL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RP_M_UNIT_VERTICAL" MODIFY ("UNIT_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_M_UNIT_VERTICAL" MODIFY ("VERTICAL_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_M_UNIT_VERTICAL" ADD CONSTRAINT "PK_RP_U_V" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_M_UNIT_VERTICAL" ADD CONSTRAINT "UQ_RP_U_V" UNIQUE ("UNIT_ID", "VERTICAL_ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_M_VERTICAL" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_VERTICAL" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "RP_M_VERTICAL" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_M_VERTICAL" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_M_VERTICAL" ADD UNIQUE ("CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_NOTIFICATION" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "RP_NOTIFICATION" MODIFY ("SOURCE" NOT NULL ENABLE);
  ALTER TABLE "RP_NOTIFICATION" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_NOTIFICATION" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_NOTIF_OUTBOX" MODIFY ("EVENT_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_NOTIF_OUTBOX" MODIFY ("CHANNEL" NOT NULL ENABLE);
  ALTER TABLE "RP_NOTIF_OUTBOX" MODIFY ("TO_ADDR" NOT NULL ENABLE);
  ALTER TABLE "RP_NOTIF_OUTBOX" MODIFY ("PAYLOAD_JSON" NOT NULL ENABLE);
  ALTER TABLE "RP_NOTIF_OUTBOX" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "RP_NOTIF_OUTBOX" MODIFY ("ATTEMPTS" NOT NULL ENABLE);
  ALTER TABLE "RP_NOTIF_OUTBOX" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_NOTIF_OUTBOX" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_PAGE_INFO" MODIFY ("PAGE_KEY" NOT NULL ENABLE);
  ALTER TABLE "RP_PAGE_INFO" MODIFY ("PAGE_NAME" NOT NULL ENABLE);
  ALTER TABLE "RP_PAGE_INFO" MODIFY ("PAGE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "RP_PAGE_INFO" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "RP_PAGE_INFO" ADD CONSTRAINT "CHK_PI_STATUS" CHECK (STATUS   IN ('ACTIVE','INACTIVE','DEPRECATED')) ENABLE;
  ALTER TABLE "RP_PAGE_INFO" ADD CONSTRAINT "CHK_PI_TYPE" CHECK (PAGE_TYPE IN ('Dashboard','Report','Upload','Approve','Enquiry','Maintenance','Other')) ENABLE;
  ALTER TABLE "RP_PAGE_INFO" ADD CONSTRAINT "PK_RP_PAGE_INFO" PRIMARY KEY ("PAGE_KEY")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_RBAC_APP_ADMIN" MODIFY ("EMP_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_APP_ADMIN" MODIFY ("ASSIGNED_AT_UTC" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_APP_ADMIN" MODIFY ("ASSIGNED_BY_EMP" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_APP_ADMIN" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_APP_ADMIN" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_RBAC_APP_ADMIN" ADD UNIQUE ("EMP_CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_RBAC_AUDIT" MODIFY ("AT_UTC" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_AUDIT" MODIFY ("ACTOR_EMP_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_AUDIT" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_AUDIT" MODIFY ("TARGET" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_AUDIT" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_RBAC_MENU" MODIFY ("MODULE_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_MENU" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_MENU" MODIFY ("LABEL" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_MENU" MODIFY ("ROUTE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_MENU" MODIFY ("SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_MENU" MODIFY ("IS_ENABLED" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_MENU" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_MENU" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_MENU" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_MENU" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_RBAC_MENU" ADD UNIQUE ("CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_RBAC_MODULE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_MODULE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_MODULE" MODIFY ("KIND" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_MODULE" MODIFY ("SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_MODULE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_MODULE" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_MODULE" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_MODULE" ADD CONSTRAINT "CK_RBAC_MOD_KIND" CHECK (KIND BETWEEN 1 AND 5) ENABLE;
  ALTER TABLE "RP_RBAC_MODULE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_RBAC_MODULE" ADD UNIQUE ("CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_RBAC_ROLE_PERM" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_ROLE_PERM" MODIFY ("MODULE_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_ROLE_PERM" MODIFY ("CAN_VIEW" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_ROLE_PERM" MODIFY ("CAN_ADD" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_ROLE_PERM" MODIFY ("CAN_MODIFY" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_ROLE_PERM" MODIFY ("CAN_DELETE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_ROLE_PERM" MODIFY ("CAN_AUTHORIZE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_ROLE_PERM" MODIFY ("UPDATED_AT_UTC" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_ROLE_PERM" MODIFY ("UPDATED_BY_EMP" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_ROLE_PERM" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_RBAC_ROLE_PERM" ADD CONSTRAINT "UK_RBAC_ROLE_MOD" UNIQUE ("ROLE_ID", "MODULE_ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_RBAC_SUPER_ADMIN" MODIFY ("EMP_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_SUPER_ADMIN" MODIFY ("ASSIGNED_AT_UTC" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_SUPER_ADMIN" MODIFY ("ASSIGNED_BY" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_SUPER_ADMIN" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_RBAC_SUPER_ADMIN" ADD UNIQUE ("EMP_CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_RBAC_USER_PERM" MODIFY ("EMP_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_USER_PERM" MODIFY ("MODULE_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_USER_PERM" MODIFY ("IS_DENY" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_USER_PERM" MODIFY ("CAN_VIEW" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_USER_PERM" MODIFY ("CAN_ADD" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_USER_PERM" MODIFY ("CAN_MODIFY" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_USER_PERM" MODIFY ("CAN_DELETE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_USER_PERM" MODIFY ("CAN_AUTHORIZE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_USER_PERM" MODIFY ("UPDATED_AT_UTC" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_USER_PERM" MODIFY ("UPDATED_BY_EMP" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_USER_PERM" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_RBAC_USER_PERM" ADD CONSTRAINT "UK_RBAC_USER_MOD" UNIQUE ("EMP_CODE", "MODULE_ID", "IS_DENY")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_RBAC_VERTICAL_ADMIN" MODIFY ("VERTICAL_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_VERTICAL_ADMIN" MODIFY ("EMP_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_VERTICAL_ADMIN" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_VERTICAL_ADMIN" MODIFY ("ASSIGNED_BY_EMP" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_VERTICAL_ADMIN" MODIFY ("ASSIGNED_AT_UTC" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_VERTICAL_ADMIN" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_RBAC_VERTICAL_ADMIN" ADD CONSTRAINT "UK_VERT_ADMIN" UNIQUE ("VERTICAL_ID", "EMP_CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_RBAC_VERTICAL_LEVEL" MODIFY ("VERTICAL_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_VERTICAL_LEVEL" MODIFY ("EMP_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_VERTICAL_LEVEL" MODIFY ("LEVEL_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_VERTICAL_LEVEL" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_VERTICAL_LEVEL" MODIFY ("ASSIGNED_BY_EMP" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_VERTICAL_LEVEL" MODIFY ("ASSIGNED_AT_UTC" NOT NULL ENABLE);
  ALTER TABLE "RP_RBAC_VERTICAL_LEVEL" ADD CONSTRAINT "CK_LEVEL_CODE" CHECK (LEVEL_CODE IN ('VERT_L1','VERT_L2','VERT_L3','VERT_L4','VERT_L5')) ENABLE;
  ALTER TABLE "RP_RBAC_VERTICAL_LEVEL" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_RBAC_VERTICAL_LEVEL" ADD CONSTRAINT "UK_VERT_LEVEL" UNIQUE ("VERTICAL_ID", "EMP_CODE", "LEVEL_CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_REPORT_ACCESS_LOG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RP_REPORT_ACCESS_LOG" MODIFY ("REPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_REPORT_ACCESS_LOG" MODIFY ("REPORT_NAME" NOT NULL ENABLE);
  ALTER TABLE "RP_REPORT_ACCESS_LOG" MODIFY ("ACCESSED_BY" NOT NULL ENABLE);
  ALTER TABLE "RP_REPORT_ACCESS_LOG" MODIFY ("ACCESSED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_REPORT_ACCESS_LOG" MODIFY ("SUCCESS" NOT NULL ENABLE);
  ALTER TABLE "RP_REPORT_ACCESS_LOG" ADD CONSTRAINT "PK_RP_REPORT_ACCESS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_REPORT_AUDIT_LOG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RP_REPORT_AUDIT_LOG" MODIFY ("REPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_REPORT_AUDIT_LOG" MODIFY ("REPORT_NAME" NOT NULL ENABLE);
  ALTER TABLE "RP_REPORT_AUDIT_LOG" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "RP_REPORT_AUDIT_LOG" MODIFY ("ACTOR_EMP" NOT NULL ENABLE);
  ALTER TABLE "RP_REPORT_AUDIT_LOG" MODIFY ("ACTOR_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_REPORT_AUDIT_LOG" ADD CONSTRAINT "CK_RP_REPORT_AUDIT_ACT" CHECK (ACTION IN ('CREATE','UPDATE','DELETE','ENABLE','DISABLE')) ENABLE;
  ALTER TABLE "RP_REPORT_AUDIT_LOG" ADD CONSTRAINT "PK_RP_REPORT_AUDIT" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_REQUEST" MODIFY ("REQ_NO" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST" MODIFY ("REQUEST_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST" MODIFY ("UNIT_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST" MODIFY ("VERTICAL_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST" MODIFY ("DEPARTMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST" MODIFY ("ACTIVITY_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST" MODIFY ("RAISED_BY_EMP" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST" MODIFY ("CURRENT_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST" MODIFY ("ROW_VERSION" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_REQUEST" ADD UNIQUE ("REQ_NO")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_REQUEST_ACTION" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ACTION" MODIFY ("LEVEL_NO" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ACTION" MODIFY ("ACTOR_EMP_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ACTION" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ACTION" MODIFY ("ACTED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ACTION" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_REQUEST_ASSIGNEE" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ASSIGNEE" MODIFY ("LEVEL_NO" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ASSIGNEE" MODIFY ("EMP_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ASSIGNEE" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ASSIGNEE" MODIFY ("ASSIGNED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ASSIGNEE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_REQUEST_ATTACHMENT" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ATTACHMENT" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ATTACHMENT" MODIFY ("MIME" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ATTACHMENT" MODIFY ("SIZE_BYTES" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ATTACHMENT" MODIFY ("STORAGE_KEY" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ATTACHMENT" MODIFY ("UPLOADED_BY_EMP" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ATTACHMENT" MODIFY ("UPLOADED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ATTACHMENT" MODIFY ("SHA256" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_ATTACHMENT" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_REQUEST_CLARIFICATION" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_CLARIFICATION" MODIFY ("ASKED_BY_EMP" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_CLARIFICATION" MODIFY ("ASKED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_CLARIFICATION" MODIFY ("QUESTION" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_CLARIFICATION" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_REQUEST_FEEDBACK" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_FEEDBACK" MODIFY ("RATING" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_FEEDBACK" MODIFY ("GIVEN_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_REQUEST_FEEDBACK" ADD CONSTRAINT "CK_FEEDBACK_RATING" CHECK (RATING BETWEEN 1 AND 5) ENABLE;
  ALTER TABLE "RP_REQUEST_FEEDBACK" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_REQUEST_FEEDBACK" ADD UNIQUE ("REQUEST_ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_ROLE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_ROLE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "RP_ROLE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_ROLE" ADD UNIQUE ("CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_SLA_PAUSE_LOG" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_SLA_PAUSE_LOG" MODIFY ("PAUSED_AT" NOT NULL ENABLE);
  ALTER TABLE "RP_SLA_PAUSE_LOG" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_UAT_AUTH" MODIFY ("EMPLOYEE_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_UAT_AUTH" MODIFY ("PWD_HASH" NOT NULL ENABLE);
  ALTER TABLE "RP_UAT_AUTH" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_UAT_AUTH" ADD CONSTRAINT "PK_UAT_AUTH" PRIMARY KEY ("EMPLOYEE_CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_UAT_STAFF" MODIFY ("EMPLOYEE_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_UAT_STAFF" MODIFY ("EMPLOYEE_NAME" NOT NULL ENABLE);
  ALTER TABLE "RP_UAT_STAFF" MODIFY ("UNIT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "RP_UAT_STAFF" MODIFY ("USER_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "RP_UAT_STAFF" MODIFY ("IS_HEAD" NOT NULL ENABLE);
  ALTER TABLE "RP_UAT_STAFF" ADD CONSTRAINT "CK_UAT_UNIT_TYPE" CHECK (UNIT_TYPE  IN ('RO','ZO','CO','ADMIN')) ENABLE;
  ALTER TABLE "RP_UAT_STAFF" ADD CONSTRAINT "CK_UAT_USER_LEVEL" CHECK (USER_LEVEL IN ('BRANCH','RO','ZO','CO','ADMIN')) ENABLE;
  ALTER TABLE "RP_UAT_STAFF" ADD CONSTRAINT "CK_UAT_IS_HEAD" CHECK (IS_HEAD    IN (0,1)) ENABLE;
  ALTER TABLE "RP_UAT_STAFF" ADD CONSTRAINT "PK_UAT_STAFF" PRIMARY KEY ("EMPLOYEE_CODE")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_USER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RP_USER" MODIFY ("EMP_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_USER" MODIFY ("AD_SAM" NOT NULL ENABLE);
  ALTER TABLE "RP_USER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "RP_USER" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "RP_USER" ADD CONSTRAINT "PK_RP_USER" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_USER" ADD CONSTRAINT "UQ_RP_USER_EMP" UNIQUE ("EMP_CODE")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_USER" ADD CONSTRAINT "UQ_RP_USER_SAM" UNIQUE ("AD_SAM")
  USING INDEX  ENABLE;

  ALTER TABLE "RP_USER_ROLE" MODIFY ("EMP_CODE" NOT NULL ENABLE);
  ALTER TABLE "RP_USER_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "RP_USER_ROLE" MODIFY ("VALID_FROM" NOT NULL ENABLE);
  ALTER TABLE "RP_USER_ROLE" MODIFY ("GRANTED_BY" NOT NULL ENABLE);
  ALTER TABLE "RP_USER_ROLE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RP_USER_ROLE" ADD CONSTRAINT "UK_USER_ROLE" UNIQUE ("EMP_CODE", "ROLE_ID")
  USING INDEX  ENABLE;
-- ===================== INDEXES (non-constraint) =====================

  CREATE INDEX "IX_MD_NOTIF_OUTBOX_STATUS" ON "MD_NOTIF_OUTBOX" ("STATUS", "ATTEMPTS") 
  ;

  CREATE INDEX "IX_MD_INAPP_NOTIF_EMP" ON "MD_INAPP_NOTIF" ("EMPL_CODE", "IS_READ", "CREATED_AT") 
  ;

  CREATE INDEX "IX_RP_ESC_ACTIVITY" ON "RP_ESCALATION_MATRIX" ("ACTIVITY_ID", "UNIT_ID", "LEVEL_NO") 
  ;

  CREATE INDEX "IX_EV_EVENT_VERT" ON "EV_EVENT" ("VERTICAL_ID") 
  ;

  CREATE INDEX "IX_EV_POST_VERT" ON "EV_POST" ("VERTICAL_ID") 
  ;

  CREATE INDEX "IX_EV_POST_ARCH" ON "EV_POST" ("IS_ARCHIVED", "POSTED_AT") 
  ;

  CREATE INDEX "IX_EV_IMG_POST" ON "EV_POST_IMAGE" ("POST_ID") 
  ;

  CREATE INDEX "IX_EV_LOG_CREATED" ON "EV_ACTIVITY_LOG" ("CREATED_AT") 
  ;

  CREATE INDEX "IX_RP_REPORT_DEF_FILT" ON "RP_M_REPORT_DEF" ("VERTICAL_ID", "DEPARTMENT_ID", "IS_ACTIVE") 
  ;

  CREATE INDEX "IX_RP_REPORT_AUDIT_RID" ON "RP_REPORT_AUDIT_LOG" ("REPORT_ID", "ACTOR_AT" DESC) 
  ;

  CREATE INDEX "IX_RP_REPORT_ACCESS_RID" ON "RP_REPORT_ACCESS_LOG" ("REPORT_ID", "ACCESSED_AT" DESC) 
  ;

  CREATE INDEX "IX_RP_REQUEST_EXT_ALERT" ON "RP_REQUEST" ("EXT_SOURCE", "EXT_ALERT_ID") 
  ;

  CREATE INDEX "IX_RP_NOTIF_USER" ON "RP_NOTIFICATION" ("USER_ID", SYS_EXTRACT_UTC("READ_AT")) 
  ;
-- ===================== FOREIGN KEY CONSTRAINTS (added last, after all tables exist) =====================

  ALTER TABLE "EASE_P1_ENTRY" ADD FOREIGN KEY ("METRIC_ID")
	  REFERENCES "EASE_P1_METRIC" ("ID") ENABLE;

  ALTER TABLE "EV_POST_IMAGE" ADD FOREIGN KEY ("POST_ID")
	  REFERENCES "EV_POST" ("ID") ENABLE;

  ALTER TABLE "HF_JOB_PARAMETER" ADD CONSTRAINT "FK_JOB_PARAMETER_JOB" FOREIGN KEY ("JOB_ID")
	  REFERENCES "HF_JOB" ("ID") ON DELETE CASCADE ENABLE;

  ALTER TABLE "HF_JOB_QUEUE" ADD CONSTRAINT "FK_JOB_QUEUE_JOB" FOREIGN KEY ("JOB_ID")
	  REFERENCES "HF_JOB" ("ID") ON DELETE CASCADE ENABLE;

  ALTER TABLE "HF_JOB_STATE" ADD CONSTRAINT "FK_JOB_STATE_JOB" FOREIGN KEY ("JOB_ID")
	  REFERENCES "HF_JOB" ("ID") ON DELETE CASCADE ENABLE;

  ALTER TABLE "MD_RBAC_MENU" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "MD_RBAC_MODULE" ("ID") ON DELETE CASCADE ENABLE;

  ALTER TABLE "MD_RBAC_MODULE" ADD FOREIGN KEY ("PARENT_ID")
	  REFERENCES "MD_RBAC_MODULE" ("ID") ENABLE;

  ALTER TABLE "MD_ROLE_MODULE_PERM" ADD FOREIGN KEY ("ROLE_ID")
	  REFERENCES "MD_ROLE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MD_ROLE_MODULE_PERM" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "MD_RBAC_MODULE" ("ID") ON DELETE CASCADE ENABLE;

  ALTER TABLE "MD_USER_MODULE_PERM" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "MD_RBAC_MODULE" ("ID") ON DELETE CASCADE ENABLE;

  ALTER TABLE "MD_USER_ROLE" ADD FOREIGN KEY ("ROLE_ID")
	  REFERENCES "MD_ROLE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MD_USER_ROLE" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "MD_USER" ("ID") ON DELETE CASCADE ENABLE;

  ALTER TABLE "RP_ESCALATION_MATRIX" ADD CONSTRAINT "FK_RP_ESC_ACTIVITY" FOREIGN KEY ("ACTIVITY_ID")
	  REFERENCES "RP_M_ACTIVITY" ("ID") ENABLE;

  ALTER TABLE "RP_M_ACTIVITY" ADD FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "RP_M_DEPARTMENT" ("ID") ENABLE;

  ALTER TABLE "RP_M_DEPARTMENT" ADD FOREIGN KEY ("VERTICAL_ID")
	  REFERENCES "RP_M_VERTICAL" ("ID") ENABLE;

  ALTER TABLE "RP_M_HOLIDAY" ADD FOREIGN KEY ("CAL_ID")
	  REFERENCES "RP_M_HOLIDAY_CAL" ("ID") ENABLE;

  ALTER TABLE "RP_M_REPORT_DEF" ADD CONSTRAINT "FK_RP_REPORT_VERT" FOREIGN KEY ("VERTICAL_ID")
	  REFERENCES "RP_M_VERTICAL" ("ID") ENABLE;
  ALTER TABLE "RP_M_REPORT_DEF" ADD CONSTRAINT "FK_RP_REPORT_DEPT" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "RP_M_DEPARTMENT" ("ID") ENABLE;

  ALTER TABLE "RP_M_REQTYPE_UNITTYPE" ADD CONSTRAINT "FK_RP_RT_UT_RT" FOREIGN KEY ("REQUEST_TYPE_ID")
	  REFERENCES "RP_M_REQUEST_TYPE" ("ID") ENABLE;
  ALTER TABLE "RP_M_REQTYPE_UNITTYPE" ADD CONSTRAINT "FK_RP_RT_UT_UT" FOREIGN KEY ("UNIT_TYPE_ID")
	  REFERENCES "RP_M_UNIT_TYPE" ("ID") ENABLE;

  ALTER TABLE "RP_M_ROUTING_ASSIGNEE" ADD FOREIGN KEY ("RULE_ID")
	  REFERENCES "RP_M_ROUTING_RULE" ("ID") ON DELETE CASCADE ENABLE;

  ALTER TABLE "RP_M_ROUTING_RULE" ADD FOREIGN KEY ("REQUEST_TYPE_ID")
	  REFERENCES "RP_M_REQUEST_TYPE" ("ID") ENABLE;
  ALTER TABLE "RP_M_ROUTING_RULE" ADD FOREIGN KEY ("UNIT_TYPE_ID")
	  REFERENCES "RP_M_UNIT_TYPE" ("ID") ENABLE;
  ALTER TABLE "RP_M_ROUTING_RULE" ADD FOREIGN KEY ("VERTICAL_ID")
	  REFERENCES "RP_M_VERTICAL" ("ID") ENABLE;
  ALTER TABLE "RP_M_ROUTING_RULE" ADD FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "RP_M_DEPARTMENT" ("ID") ENABLE;
  ALTER TABLE "RP_M_ROUTING_RULE" ADD FOREIGN KEY ("ACTIVITY_ID")
	  REFERENCES "RP_M_ACTIVITY" ("ID") ENABLE;

  ALTER TABLE "RP_M_SLA_CONFIG" ADD FOREIGN KEY ("REQUEST_TYPE_ID")
	  REFERENCES "RP_M_REQUEST_TYPE" ("ID") ENABLE;

  ALTER TABLE "RP_M_UNIT" ADD FOREIGN KEY ("UNIT_TYPE_ID")
	  REFERENCES "RP_M_UNIT_TYPE" ("ID") ENABLE;
  ALTER TABLE "RP_M_UNIT" ADD FOREIGN KEY ("PARENT_UNIT_ID")
	  REFERENCES "RP_M_UNIT" ("ID") ENABLE;
  ALTER TABLE "RP_M_UNIT" ADD FOREIGN KEY ("HOLIDAY_CAL_ID")
	  REFERENCES "RP_M_HOLIDAY_CAL" ("ID") ENABLE;

  ALTER TABLE "RP_M_UNIT_VERTICAL" ADD CONSTRAINT "FK_RP_U_V_U" FOREIGN KEY ("UNIT_ID")
	  REFERENCES "RP_M_UNIT" ("ID") ENABLE;
  ALTER TABLE "RP_M_UNIT_VERTICAL" ADD CONSTRAINT "FK_RP_U_V_V" FOREIGN KEY ("VERTICAL_ID")
	  REFERENCES "RP_M_VERTICAL" ("ID") ENABLE;

  ALTER TABLE "RP_RBAC_MENU" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "RP_RBAC_MODULE" ("ID") ENABLE;

  ALTER TABLE "RP_RBAC_MODULE" ADD FOREIGN KEY ("PARENT_ID")
	  REFERENCES "RP_RBAC_MODULE" ("ID") ENABLE;

  ALTER TABLE "RP_RBAC_ROLE_PERM" ADD FOREIGN KEY ("ROLE_ID")
	  REFERENCES "RP_ROLE" ("ID") ENABLE;
  ALTER TABLE "RP_RBAC_ROLE_PERM" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "RP_RBAC_MODULE" ("ID") ENABLE;

  ALTER TABLE "RP_RBAC_USER_PERM" ADD FOREIGN KEY ("MODULE_ID")
	  REFERENCES "RP_RBAC_MODULE" ("ID") ENABLE;

  ALTER TABLE "RP_RBAC_VERTICAL_ADMIN" ADD FOREIGN KEY ("VERTICAL_ID")
	  REFERENCES "RP_M_VERTICAL" ("ID") ENABLE;

  ALTER TABLE "RP_RBAC_VERTICAL_LEVEL" ADD FOREIGN KEY ("VERTICAL_ID")
	  REFERENCES "RP_M_VERTICAL" ("ID") ENABLE;

  ALTER TABLE "RP_REQUEST" ADD FOREIGN KEY ("REQUEST_TYPE_ID")
	  REFERENCES "RP_M_REQUEST_TYPE" ("ID") ENABLE;
  ALTER TABLE "RP_REQUEST" ADD FOREIGN KEY ("UNIT_ID")
	  REFERENCES "RP_M_UNIT" ("ID") ENABLE;
  ALTER TABLE "RP_REQUEST" ADD FOREIGN KEY ("VERTICAL_ID")
	  REFERENCES "RP_M_VERTICAL" ("ID") ENABLE;
  ALTER TABLE "RP_REQUEST" ADD FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "RP_M_DEPARTMENT" ("ID") ENABLE;
  ALTER TABLE "RP_REQUEST" ADD FOREIGN KEY ("ACTIVITY_ID")
	  REFERENCES "RP_M_ACTIVITY" ("ID") ENABLE;

  ALTER TABLE "RP_REQUEST_ACTION" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_REQUEST" ("ID") ENABLE;

  ALTER TABLE "RP_REQUEST_ASSIGNEE" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_REQUEST" ("ID") ENABLE;

  ALTER TABLE "RP_REQUEST_ATTACHMENT" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_REQUEST" ("ID") ENABLE;
  ALTER TABLE "RP_REQUEST_ATTACHMENT" ADD FOREIGN KEY ("ACTION_ID")
	  REFERENCES "RP_REQUEST_ACTION" ("ID") ENABLE;

  ALTER TABLE "RP_REQUEST_CLARIFICATION" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_REQUEST" ("ID") ENABLE;

  ALTER TABLE "RP_REQUEST_FEEDBACK" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_REQUEST" ("ID") ENABLE;

  ALTER TABLE "RP_SLA_PAUSE_LOG" ADD FOREIGN KEY ("REQUEST_ID")
	  REFERENCES "RP_REQUEST" ("ID") ENABLE;

  ALTER TABLE "RP_UAT_AUTH" ADD CONSTRAINT "FK_UAT_AUTH_STAFF" FOREIGN KEY ("EMPLOYEE_CODE")
	  REFERENCES "RP_UAT_STAFF" ("EMPLOYEE_CODE") ENABLE;

  ALTER TABLE "RP_USER_ROLE" ADD FOREIGN KEY ("ROLE_ID")
	  REFERENCES "RP_ROLE" ("ID") ENABLE;
-- ===================== VIEWS =====================

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_STAFF_USER_SUMMARY" ("EMPLOYEE_CODE", "EMPLOYEE_NAME", "UNIT_TYPE", "USER_LEVEL", "UNIT_CODE", "UNIT_NAME", "VERTICAL_CODE", "VERTICAL_NAME", "IS_HEAD", "DESIGNATION", "EMAIL", "MOBILE") AS
  SELECT
  EMPLOYEE_CODE,
  EMPLOYEE_NAME,
  UNIT_TYPE,
  USER_LEVEL,
  UNIT_CODE,
  UNIT_NAME,
  VERTICAL_CODE,
  VERTICAL_NAME,
  IS_HEAD,
  DESIGNATION,
  EMAIL,
  MOBILE
FROM RP_UAT_STAFF;

-- ===================== PROCEDURES =====================
-- ===================== FUNCTIONS =====================
-- ===================== PACKAGES (spec) =====================
-- ===================== PACKAGE BODIES =====================
-- ===================== TRIGGERS =====================
-- ===================== SYNONYMS =====================
